"use client";
import SectionGuideTemplate, { type SectionGuideData } from "@/components/SectionGuideTemplate";

const TABS: string[] = [
  "Overview",
  "The Linen Loincloth",
  "Give Glory Before Darkness",
  "Can the Leopard Change His Spots?",
  "Application",
];

const sections = [
  {
    id: "Overview",
    heading: "Overview of Jeremiah 13",
    reference: "Jeremiah 13:1&ndash;27",
    paragraphs: [
      "Jeremiah 13 opens with one of the prophet's strangest and most tender sign-acts. God commands Jeremiah to buy a linen loincloth, wear it against his skin, then hide it in a cleft of the rock by the Euphrates. When he returns to retrieve it, the garment is ruined &mdash; &lsquo;good for nothing&rsquo; (13:7). God himself interprets the parable: &ldquo;For as the loincloth clings to the waist of a man, so I made the whole house of Israel and the whole house of Judah cling to me&hellip; that they might be for me a people, a name, a praise, and a glory, but they would not listen&rdquo; (13:11). Israel was made for intimacy with God as close as a garment to the body, and pride has spoiled what was made for closeness.",
      "The chapter unfolds in three movements. First, the sign-act of the loincloth and its interpretation: the pride of Judah and Jerusalem will be spoiled like the ruined garment (13:1-11). Second, the oracle of the wine jars &mdash; every inhabitant of the land will be filled with the drunkenness of judgment and dashed against one another &mdash; followed by a tender plea to give glory to God before darkness falls, and by Jeremiah's secret tears over a people who will not listen (13:12-17). Third, a word to the king and the queen mother to humble themselves, the exposure of Jerusalem's shame, and the chapter's climactic verse on moral inability: &lsquo;Can the Ethiopian change his skin or the leopard his spots?&rsquo; (13:18-27).",
      "The thread binding these oracles together is pride. God declares, &ldquo;Even so will I spoil the pride of Judah and the great pride of Jerusalem&rdquo; (13:9); the plea of verse 15 is &lsquo;be not proud, for the Lord has spoken&rsquo;; and Jeremiah weeps in secret precisely &lsquo;for your pride&rsquo; (13:17). Pride is the refusal to cling &mdash; the insistence on standing apart from the God we were made to hang upon. And the chapter presses the diagnosis to its terrible depth: sin is not merely a series of bad choices but a settled nature. Those &lsquo;accustomed to do evil&rsquo; can no more do good than a leopard can change his spots (13:23).",
      "That is why Jeremiah 13 belongs to the gospel. Its closing question &mdash; &ldquo;Woe to you, O Jerusalem! How long before you are made clean?&rdquo; (13:27) &mdash; hangs unanswered over the whole Old Testament until it is answered at the cross, where &lsquo;the blood of Jesus his Son cleanses us from all sin&rsquo; (1 John 1:7). The people who cannot change their own spots need what God later promises through this same prophet: &lsquo;I will write my law on their hearts&rsquo; (Jeremiah 31:33), a heart of flesh in place of stone (Ezekiel 36:26). Jesus says it plainly to Nicodemus: &lsquo;You must be born again&rsquo; (John 3:7). Jeremiah 13 strips away every hope of self-reform so that we will seek, not reformation, but rebirth &mdash; and cling again to the God who made us for himself.",
    ],
  },
  {
    id: "The Linen Loincloth",
    heading: "Made to Cling to Me",
    reference: "Jeremiah 13:1&ndash;11",
    paragraphs: [
      "The chapter begins with a command as intimate as it is strange: &ldquo;Thus says the Lord to me, &lsquo;Go and buy a linen loincloth and put it around your waist, and do not dip it in water&rsquo;&rdquo; (13:1). Jeremiah is to wear the garment against his own skin. Then comes the second word: &ldquo;Take the loincloth that you have bought&hellip; and arise, go to the Euphrates and hide it there in a cleft of the rock&rdquo; (13:4). After many days God sends him back, and the prophet digs out the buried garment only to find the parable complete: &ldquo;behold, the loincloth was spoiled; it was good for nothing&rdquo; (13:7). A garment made for closeness, buried far from the body it was meant to clothe, has rotted into uselessness.",
      "God supplies the interpretation himself: &ldquo;Thus says the Lord: Even so will I spoil the pride of Judah and the great pride of Jerusalem. This evil people, who refuse to hear my words, who stubbornly follow their own heart and have gone after other gods&hellip; shall be like this loincloth, which is good for nothing&rdquo; (13:9-10). The Euphrates is no accidental detail &mdash; it points toward Babylon, where the pride of Judah will be buried in exile and ruined. What sin buries far from God, sin spoils. Separated from the one it was made to clothe, the garment does not become free; it becomes rotten.",
      "Then comes the verse that turns the sign-act from threat to heartbreak: &ldquo;For as the loincloth clings to the waist of a man, so I made the whole house of Israel and the whole house of Judah cling to me, declares the Lord, that they might be for me a people, a name, a praise, and a glory, but they would not listen&rdquo; (13:11). The image is stunning in its intimacy. Israel was not created for distant, formal religion but to cling to God as closely as a garment clings to the body &mdash; nothing between, nothing nearer. And the fabric matters: linen was the priestly cloth, prescribed for those who drew near to God in the sanctuary (Exodus 28:39-42). Israel was called to be &lsquo;a kingdom of priests&rsquo; (Exodus 19:6) &mdash; a whole people worn close to God's heart, his name and praise and glory before the nations. Pride ruined a priesthood.",
      "The New Testament takes up both sides of this image and answers them in Christ. The calling Judah spoiled is renewed in the church: &lsquo;you are a chosen race, a royal priesthood&hellip; that you may proclaim the excellencies of him who called you out of darkness&rsquo; (1 Peter 2:9) &mdash; a people, a name, a praise, and a glory at last. And the clinging that Israel refused is restored by union with Jesus, who commands, &lsquo;Abide in me, and I in you. As the branch cannot bear fruit by itself, unless it abides in the vine, neither can you, unless you abide in me&rsquo; (John 15:4). Paul even reaches for the garment language itself: &lsquo;As many of you as were baptized into Christ have put on Christ&rsquo; (Galatians 3:27). What we could not be for God, God in Christ has become for us &mdash; and now he wears his people close, never to be buried and lost again.",
    ],
  },
  {
    id: "Give Glory Before Darkness",
    heading: "Before Your Feet Stumble on the Twilight Mountains",
    reference: "Jeremiah 13:12&ndash;17",
    paragraphs: [
      "The second oracle begins with what sounds like a proverb too obvious to say: &ldquo;Every jar shall be filled with wine&rdquo; (13:12). Jeremiah's hearers scoff &mdash; of course jars are for wine; tell us something we do not know. But God turns the truism into terror: &ldquo;Behold, I will fill with drunkenness all the inhabitants of this land: the kings who sit on David's throne, the priests, the prophets, and all the inhabitants of Jerusalem. And I will dash them one against another, fathers and sons together&hellip; I will not pity or spare or have compassion, that I should not destroy them&rdquo; (13:13-14). Every jar &mdash; king, priest, prophet, commoner &mdash; will be filled with the staggering wine of judgment and shattered against its neighbor. The cup of God's wrath, poured out on a proud people, leaves no vessel standing.",
      "Yet before the darkness falls, mercy makes one more appeal, and it is among the most tender in the book: &ldquo;Hear and give ear; be not proud, for the Lord has spoken. Give glory to the Lord your God before he brings darkness, before your feet stumble on the twilight mountains, and while you look for light he turns it into gloom and makes it deep darkness&rdquo; (13:15-16). The picture is a traveler overtaken by nightfall in the hill country &mdash; the light fading, the path vanishing, every step a stumble. There is still light, the verse pleads; there is still time. Give glory to God now &mdash; humble yourself, own his word as true, return &mdash; before the twilight thickens into a night in which no repentance can find the road.",
      "Jesus took up this very warning on the eve of his cross: &ldquo;The light is among you for a little while longer. Walk while you have the light, lest darkness overtake you&hellip; While you have the light, believe in the light, that you may become sons of light&rdquo; (John 12:35-36). Grace has a daylight, and daylight has an end. Scripture never treats the offer of mercy as an indefinite standing option; it says, &lsquo;now is the favorable time; behold, now is the day of salvation&rsquo; (2 Corinthians 6:2), and &lsquo;Today, if you hear his voice, do not harden your hearts&rsquo; (Hebrews 3:15). The most dangerous word in the sinner's vocabulary is &lsquo;tomorrow,&rsquo; for no one is promised that the light will last until then.",
      "And then the prophet's own heart breaks through the oracle: &ldquo;But if you will not listen, my soul will weep in secret for your pride; my eyes will weep bitterly and run down with tears, because the Lord's flock has been taken captive&rdquo; (13:17). Jeremiah does not announce judgment with relish; he announces it with tears he cannot hold back. The weeping prophet here again foreshadows the weeping Savior, who came near Jerusalem &lsquo;and when he saw the city, he wept over it, saying, &lsquo;Would that you, even you, had known on this day the things that make for peace! But now they are hidden from your eyes&rsquo;&rsquo; (Luke 19:41-42). God takes no pleasure in the death of the wicked (Ezekiel 33:11). Behind every warning of darkness stand the tears of the One who gives it &mdash; and that is itself a reason to come into the light while it shines.",
    ],
  },
  {
    id: "Can the Leopard Change His Spots?",
    heading: "Accustomed to Do Evil",
    reference: "Jeremiah 13:18&ndash;27",
    paragraphs: [
      "The final oracle begins at the top: &ldquo;Say to the king and the queen mother: &lsquo;Take a lowly seat, for your beautiful crown has come down from your head&rsquo;&rdquo; (13:18). The word is likely for young Jehoiachin and his mother Nehushta, who would surrender to Babylon in 597 BC (2 Kings 24:8-12). Thrones do not exempt anyone from the summons to humility &mdash; they intensify it. &ldquo;The cities of the Negeb are shut up, with none to open them; all Judah is taken into exile&rdquo; (13:19). To the shepherd-rulers God poses the question every leader must one day answer: &ldquo;Where is the flock that was given you, your beautiful flock?&rdquo; (13:20). Those who would not humble themselves under God's hand will be humbled by it &mdash; the pattern Jesus fixed forever: &lsquo;whoever exalts himself will be humbled, and whoever humbles himself will be exalted&rsquo; (Matthew 23:12).",
      "Then the oracle turns to Jerusalem herself, pictured as a woman publicly disgraced: &ldquo;And if you say in your heart, &lsquo;Why have these things come upon me?&rsquo; it is for the greatness of your iniquity that your skirts are lifted up&hellip; I myself will lift up your skirts over your face, and your shame will be seen&rdquo; (13:22, 26). The image is deliberately shocking: the city that flaunted her spiritual adulteries &lsquo;on the hills in the field&rsquo; (13:27) will have her hidden corruption dragged into daylight. Sin promises secrecy and delivers exposure. &lsquo;You have forgotten me and trusted in lies&rsquo; (13:25) is the root; the scattering &lsquo;like chaff driven by the wind&rsquo; (13:24) is the fruit. What Judah would not confess, God will uncover &mdash; for &lsquo;nothing is covered up that will not be revealed&rsquo; (Luke 12:2).",
      "At the center of this exposure stands the chapter's most famous and most devastating sentence: &ldquo;Can the Ethiopian change his skin or the leopard his spots? Then also you can do good who are accustomed to do evil&rdquo; (13:23). This is perhaps the strongest statement of human moral inability in the Old Testament. Sin, Jeremiah says, is not a habit to be adjusted but a nature that cannot change itself. Skin and spots are not garments to be swapped; they are what the creature is. A people &lsquo;accustomed to do evil&rsquo; &mdash; trained in it, natured in it &mdash; can no more will themselves into goodness than they can will a new complexion. Jesus and the apostles say the same: &lsquo;everyone who practices sin is a slave to sin&rsquo; (John 8:34); &lsquo;the mind that is set on the flesh is hostile to God&hellip; it cannot submit to God's law; those who are in the flesh cannot please God&rsquo; (Romans 8:7-8). The verse slams every door marked self-improvement.",
      "But the God who slams that door has promised to open another. The prophet of the leopard's spots is also the prophet of the new covenant: &ldquo;I will put my law within them, and I will write it on their hearts&rdquo; (Jeremiah 31:33); and Ezekiel carries the promise further &mdash; &ldquo;I will give you a new heart&hellip; I will remove the heart of stone from your flesh and give you a heart of flesh&rdquo; (Ezekiel 36:26). What the sinner cannot do to himself, God does to the sinner. That is why Jesus does not tell Nicodemus &mdash; a moral, learned, religious man &mdash; to try harder, but declares, &ldquo;You must be born again&rdquo; (John 3:7). And so the chapter's aching last line, &ldquo;Woe to you, O Jerusalem! How long before you are made clean?&rdquo; (13:27), finds its answer not in Judah's resolve but in Judah's Redeemer: &lsquo;the blood of Jesus his Son cleanses us from all sin&rsquo; (1 John 1:7); Christ loved the church and gave himself up for her, &lsquo;that he might sanctify her, having cleansed her&rsquo; (Ephesians 5:25-26). The leopard cannot change his spots &mdash; but the Lamb can.",
    ],
  },
  {
    id: "Application",
    heading: "Living Jeremiah 13",
    reference: "Reflections on Pride, Repentance, and the New Heart",
    paragraphs: [
      "<strong>Cling to God as the garment clings &mdash; you were made for nothing less.</strong> The loincloth parable says your deepest purpose is intimacy: to be worn close to God as &lsquo;a people, a name, a praise, and a glory&rsquo; (13:11). Distance from him is not neutral; buried away from the body it was made to clothe, the garment rots. Examine what pride has put between you and God, and close the gap today. &lsquo;Abide in me, and I in you&rsquo; (John 15:4) is not one option for the Christian life &mdash; it is the Christian life.",
      "<strong>Give glory to God before the darkness falls.</strong> The plea of 13:16 is urgent because twilight does not last: repent, humble yourself, and own God's word as true while there is still light on the path. Do not bank on tomorrow's repentance; no one is promised that the light will hold until then. &lsquo;Walk while you have the light, lest darkness overtake you&rsquo; (John 12:35). If God is convicting you of anything as you read, the time to respond is now &mdash; &lsquo;behold, now is the day of salvation&rsquo; (2 Corinthians 6:2).",
      "<strong>Let your warnings be wet with tears.</strong> Jeremiah wept in secret for the pride of a people who mocked him (13:17), and Jesus wept over the Jerusalem that would crucify him (Luke 19:41). If you speak of judgment without grief, you have not yet felt what God feels &mdash; he takes no pleasure in the death of the wicked (Ezekiel 33:11). Pray for the people you are tempted to write off, and let compassion, not contempt, carry every hard truth you tell.",
      "<strong>Stop trying to change your own spots &mdash; come to Christ for a new heart.</strong> Jeremiah 13:23 ends every project of self-reformation: those accustomed to evil cannot make themselves good, any more than a leopard can repaint his coat. So bring your unchangeable nature to the God who gives new natures &mdash; who writes his law on hearts (Jeremiah 31:33), swaps stone for flesh (Ezekiel 36:26), and says, &lsquo;You must be born again&rsquo; (John 3:7). The question &lsquo;How long before you are made clean?&rsquo; has an answer, and it is the cross. <strong>Prayer prompt:</strong> &ldquo;Lord my God, you made me to cling to you as a garment clings, and my pride has put distance where you designed closeness. Forgive me. While the light still shines, I give you glory and turn from my sin today, not tomorrow. Give me Jeremiah's tears for the people around me who are stumbling toward the dark. And Lord, I confess I cannot change my own spots &mdash; so do what only you can do: give me the new heart you promised, and wash me clean in the blood of Jesus. Amen.&rdquo;",
    ],
  },
];

const data: SectionGuideData = {
  accent: "#3a7d56",
  badge: "Jeremiah 13",
  title: "Jeremiah 13: Can the Leopard Change His Spots?",
  intro: "God tells Jeremiah to bury a linen loincloth by the Euphrates and retrieve it ruined -- 'good for nothing' -- for as a loincloth clings to the waist, 'so I made the whole house of Israel cling to me... but they would not listen.' Made for intimacy, spoiled by pride. Then a wine-jar oracle of judgment, a tender plea to 'give glory to the Lord your God before he brings darkness,' and Jeremiah weeping in secret for his people's pride. The chapter climaxes in the Bible's starkest verdict on self-change: 'Can the leopard change his spots? Then also you can do good who are accustomed to do evil.'",
  tabs: TABS,
  sections,
  calloutTitle: "Not Reformation but Rebirth",
  calloutBody: "Israel was made to cling to God as closely as a garment to the body -- 'a people, a name, a praise, and a glory' (13:11) -- and pride ruined what was made for closeness. Worse, the ruin runs deeper than habit: 'Can the leopard change his spots? Then also you can do good who are accustomed to do evil' (13:23). Sin is a nature that cannot change itself, which is why the chapter's last cry -- 'How long before you are made clean?' -- is answered not by our resolve but by God's promise of a new heart (Jer 31:33; Ezek 36:26), Jesus' word 'You must be born again' (John 3:7), and the blood that 'cleanses us from all sin' (1 John 1:7). We need not reformation but rebirth.",
};

export default function Page() {
  return <SectionGuideTemplate data={data} />;
}
