"use client";
import SectionGuideTemplate, { type SectionGuideData } from "@/components/SectionGuideTemplate";

const TABS: string[] = [
  "Overview",
  "Do Not Take a Wife",
  "A Greater Exodus",
  "Fishers, Hunters, and the Nations",
  "Application",
];

const sections = [
  {
    id: "Overview",
    heading: "Overview of Jeremiah 16",
    reference: "Jeremiah 16:1&ndash;21",
    paragraphs: [
      "In Jeremiah 16 the prophet's life itself becomes the sermon. God lays three prohibitions on him that strip away the most basic consolations of human existence: he must not marry or father children, he must not enter a house of mourning, and he must not enter a house of feasting. Every absence is a sign. The children of this generation will die unlamented; the funerals will be so many that mourning customs collapse; the voice of bridegroom and bride is about to fall silent in the streets. Jeremiah's celibate, solitary figure walking through Jerusalem was a living oracle that ordinary life was about to end.",
      "The chapter unfolds in three movements. First, the three prohibitions and their meanings &mdash; no wife, no wake, no wedding &mdash; because God has taken away his peace, his steadfast love, and his mercy from this people (16:1-9). Second, the people's question &lsquo;Why has the Lord pronounced all this great evil against us?&rsquo; and God's unsparing answer &mdash; your fathers forsook me, and you have done worse &mdash; followed, astonishingly, by the promise of a new exodus that will eclipse the exodus from Egypt itself (16:10-15). Third, the sending of &lsquo;many fishers&rsquo; and &lsquo;many hunters&rsquo; as agents of inescapable judgment, closing with Jeremiah's confidence in God his stronghold and a breathtaking vision of the nations coming from the ends of the earth to renounce their inherited lies (16:16-21).",
      "The structure of the chapter is one of the marvels of prophetic literature: the darkest oracle in Jeremiah so far is pierced, right at its center, by one of the brightest promises in the book. Into the very sentence of exile &mdash; &lsquo;I will hurl you out of this land&rsquo; (16:13) &mdash; God inserts the words &lsquo;Therefore, behold, the days are coming&rsquo; (16:14), and what comes is not more wrath but a restoration so great that Israel's foundational confession will be rewritten. No longer &lsquo;the Lord who brought us out of Egypt,&rsquo; but &lsquo;the Lord who brought us out of the north country.&rsquo; Judgment is real, but it is not the last word; God buries the seed of a new exodus inside the oracle of exile.",
      "For the Christian reader, the chapter's trajectories converge on Christ. The prophet whose very life embodied his message points to the Word made flesh, whose whole existence &mdash; birth, homelessness, singleness, sorrow, death &mdash; was itself the message of God (John 1:14). The new exodus from the north country points to the greater exodus Jesus accomplished at Jerusalem &mdash; Luke records that Moses and Elijah spoke with him about &lsquo;his departure,&rsquo; literally his <em>exodus</em> (Luke 9:31) &mdash; the deliverance of God's people from the deeper bondage of sin and death (Colossians 1:13-14). And the &lsquo;many fishers&rsquo; sent to catch a people for judgment are transfigured on the lips of Jesus into fishers of another kind: &lsquo;Follow me, and I will make you fishers of men&rsquo; (Matthew 4:19). In Christ, the net of judgment becomes the net of rescue.",
    ],
  },
  {
    id: "Do Not Take a Wife",
    heading: "A Life That Preaches the End of Ordinary Days",
    reference: "Jeremiah 16:1&ndash;9",
    paragraphs: [
      "The first prohibition cuts to the root of human hope: &ldquo;You shall not take a wife, nor shall you have sons or daughters in this place&rdquo; (16:2). In ancient Israel, marriage and children were not lifestyle options but the very meaning of continuity, blessing, and covenant future; celibacy was almost unheard of. God's reason is unbearably specific: &ldquo;Concerning the sons and daughters who are born in this place&hellip; They shall die of deadly diseases. They shall not be lamented, nor shall they be buried. They shall be as dung on the surface of the ground&rdquo; (16:3-4). Jeremiah's empty house was a warning posted in flesh: this is no generation into which to be born. Every time his neighbors asked why he had no wife, the answer was a sermon.",
      "The second prohibition severs him from the community of grief: &ldquo;Do not enter the house of mourning, or go to lament or grieve for them, for I have taken away my peace from this people, my steadfast love and mercy&rdquo; (16:5). The wording is among the most chilling in the prophets &mdash; God withdraws his <em>shalom</em>, his <em>hesed</em>, his compassion. And the sign fits the sentence: so many will die that the culture of mourning itself will collapse &mdash; &ldquo;no one shall lament for them or cut himself&hellip; No one shall break bread for the mourner&hellip; no one shall give him the cup of consolation&rdquo; (16:6-7). When death becomes total, even grief becomes impossible. Jeremiah's absence from funerals declared that comfort was being withdrawn from a people who had refused the Comforter.",
      "The third prohibition silences celebration: &ldquo;You shall not go into the house of feasting to sit with them, to eat and drink&rdquo; (16:8). For God is about to still the oldest and sweetest sounds of human life: &ldquo;Behold, I will silence in this place, before your eyes and in your days, the voice of mirth and the voice of gladness, the voice of the bridegroom and the voice of the bride&rdquo; (16:9). Weddings and feasts assume a future; Judah's future is forfeit. Jeremiah's empty chair at every banquet preached what his words could not get through: the music is about to stop. It is the same fourfold phrase that will return, gloriously reversed, in the promise of restoration (33:10-11) &mdash; proof that God silences the song only for a time.",
      "The prophet's costly, embodied obedience prefigures the Servant whose whole life was the message. Jesus, too, renounced marriage and home &mdash; &lsquo;the Son of Man has nowhere to lay his head&rsquo; (Matthew 8:20) &mdash; and became &lsquo;a man of sorrows, and acquainted with grief&rsquo; (Isaiah 53:3), embodying in his own flesh both the judgment and the mercy of God. And the New Testament honors the Jeremiah-like calling: some renounce even good gifts &lsquo;for the sake of the kingdom of heaven&rsquo; (Matthew 19:12; 1 Corinthians 7:32-35). Every believer's life, married or single, feasting or fasting, is meant to preach something true about God (1 Corinthians 10:31). Jeremiah reminds us that discipleship may claim not only our words but our calendars, our comforts, and our deepest earthly hopes &mdash; and that a life wholly surrendered becomes a word the world cannot ignore.",
    ],
  },
  {
    id: "A Greater Exodus",
    heading: "No Longer Egypt, but the North Country",
    reference: "Jeremiah 16:10&ndash;15",
    paragraphs: [
      "God anticipates the people's protest: &ldquo;And when you tell this people all these words, and they say to you, &lsquo;Why has the Lord pronounced all this great evil against us? What is our iniquity?&rsquo;&rdquo; (16:10). The question drips with wounded innocence &mdash; as if the sentence had arrived without a crime. God's answer reaches back and then presses home: &ldquo;Because your fathers have forsaken me&hellip; and have gone after other gods&hellip; and because you have done worse than your fathers, for behold, every one of you follows his stubborn, evil will, refusing to listen to me&rdquo; (16:11-12). Each generation had a choice, and each chose worse. The children cannot hide behind the fathers; their own stubborn wills condemn them.",
      "The sentence falls with terrible fitness: &ldquo;Therefore I will hurl you out of this land into a land that neither you nor your fathers have known, and there you shall serve other gods day and night, for I will show you no favor&rdquo; (16:13). The punishment is the sin ripened into consequence &mdash; the people who chose foreign gods in God's land will serve foreign gods in a foreign land, to the full. As with Israel's craving in the wilderness, God sometimes judges idolatry by handing people over to it (Psalm 106:15; Romans 1:24-25). There is no crueler sentence than getting, without restraint, the thing we preferred to God.",
      "And then, mid-oracle, the sky tears open: &ldquo;Therefore, behold, the days are coming, declares the Lord, when it shall no longer be said, &lsquo;As the Lord lives who brought up the people of Israel out of the land of Egypt,&rsquo; but &lsquo;As the Lord lives who brought up the people of Israel out of the north country and out of all the countries where he had driven them.&rsquo; For I will bring them back to their own land that I gave to their fathers&rdquo; (16:14-15). The exodus from Egypt was Israel's foundational confession, the event by which God was named. Now God promises a deliverance so great it will rewrite the confession itself. The God who hurls into exile has already scheduled the homecoming &mdash; and it will eclipse the greatest saving act in Israel's memory.",
      "The New Testament announces that this greater exodus has come. At the transfiguration, Moses &mdash; the man of the first exodus &mdash; stands with Elijah speaking to Jesus &lsquo;of his departure [Greek: <em>exodos</em>], which he was about to accomplish at Jerusalem&rsquo; (Luke 9:31). At the cross and empty tomb, Christ led the true exodus &mdash; not from Pharaoh but from the deeper slavery: &lsquo;He has delivered us from the domain of darkness and transferred us to the kingdom of his beloved Son, in whom we have redemption, the forgiveness of sins&rsquo; (Colossians 1:13-14). And as Jeremiah promised a rewritten confession, so the church sings a new song to the Lamb (Revelation 5:9). Every believer's testimony follows Jeremiah 16:14-15 in miniature: the God by whom we swear is no longer only the God of past mercies but the God of the latest one &mdash; the living Lord who brought <em>me</em> up out of the pit (Psalm 40:2-3).",
    ],
  },
  {
    id: "Fishers, Hunters, and the Nations",
    heading: "To You Shall the Nations Come",
    reference: "Jeremiah 16:16&ndash;21",
    paragraphs: [
      "The oracle returns to judgment with an image of total thoroughness: &ldquo;Behold, I am sending for many fishers, declares the Lord, and they shall catch them. And afterward I will send for many hunters, and they shall hunt them from every mountain and every hill, and out of the clefts of the rocks&rdquo; (16:16). In context these are the agents of Babylon &mdash; first sweeping the people up in nets like fish, then hunting down every straggler hiding in the hills. The reason is God's total sight: &ldquo;For my eyes are on all their ways. They are not hidden from me, nor is their iniquity concealed from my eyes&rdquo; (16:17). No cleft of rock hides from the God who sees; their iniquity and the &lsquo;carcasses of their detestable idols&rsquo; polluting his land will be repaid in full measure (16:18).",
      "Yet Jesus reached into this very verse and turned it inside out. Walking by the Sea of Galilee, he said to Simon and Andrew: &ldquo;Follow me, and I will make you fishers of men&rdquo; (Matthew 4:19). The echo is deliberate and stunning. In Jeremiah, the fishers are sent to catch a people <em>for judgment</em>; in the gospel, the fishers are sent to catch people <em>for salvation</em>. The same inescapable thoroughness &mdash; every sea, every hill, every hiding place &mdash; now serves rescue rather than wrath. The God whose eyes are on all our ways, from whom nothing is hidden, is the God who sends his church to the ends of the earth with a net of grace (Luke 5:10; Acts 1:8). What sin made a manhunt, Christ made a mission.",
      "Jeremiah responds to the darkness around him with one of his most confident confessions: &ldquo;O Lord, my strength and my stronghold, my refuge in the day of trouble&rdquo; (16:19). The prophet forbidden every human consolation &mdash; wife, children, funerals, feasts &mdash; has learned to find them all in God. And from that stronghold he sees the farthest horizon in the book so far: &ldquo;to you shall the nations come from the ends of the earth and say: &lsquo;Our fathers have inherited nothing but lies, worthless things in which there is no profit. Can man make for himself gods? Such are not gods!&rsquo;&rdquo; (16:19-20). The nations &mdash; the very peoples whose idols seduced Israel &mdash; will one day stream to the living God, renouncing their inherited falsehoods with their own lips.",
      "That vision is the missionary hope of the whole Bible, and the gospel is its fulfillment. Paul describes the Thessalonian converts in exactly Jeremiah's terms: &lsquo;you turned to God from idols to serve the living and true God&rsquo; (1 Thessalonians 1:9). Peter tells Gentile believers they were ransomed &lsquo;from the futile ways inherited from your forefathers&hellip; with the precious blood of Christ&rsquo; (1 Peter 1:18-19) &mdash; inherited lies exchanged for inherited glory. And the chapter's last word gives the goal of it all: &ldquo;Therefore, behold, I will make them know&hellip; my power and my might, and they shall know that my name is the Lord&rdquo; (16:21). From the ends of the earth to the end of the age, the purpose of both judgment and salvation is the same: that the world may know the living God &mdash; the knowledge that is eternal life (John 17:3).",
    ],
  },
  {
    id: "Application",
    heading: "Living Jeremiah 16",
    reference: "Reflections on a Life That Preaches",
    paragraphs: [
      "<strong>Let your whole life preach, not only your words.</strong> Jeremiah's empty house, his absence from funerals and feasts &mdash; his very calendar was a sermon. Your choices about money, time, marriage, celebration, and grief all say something about what you believe concerning God and the future. Ask whether your life, watched silently by neighbors and coworkers, preaches the same message as your lips. &lsquo;Whether you eat or drink, or whatever you do, do all to the glory of God&rsquo; (1 Corinthians 10:31).",
      "<strong>Do not hide behind the sins of the fathers.</strong> When Judah asked &lsquo;What is our iniquity?&rsquo;, God answered that they had done worse than their fathers, each following his own stubborn will. It is always easier to blame inherited dysfunction than to repent of present rebellion. Own your own choices before God &mdash; the generation that repents is never the generation that excuses itself. &lsquo;If we confess our sins, he is faithful and just to forgive us&rsquo; (1 John 1:9).",
      "<strong>In your darkest sentence, look for the buried promise.</strong> God tucked the new exodus inside the oracle of exile &mdash; &lsquo;the days are coming&rsquo; spoken in the same breath as &lsquo;I will hurl you out.&rsquo; If you are under discipline or walking through loss, do not conclude that judgment is God's last word; he schedules homecomings in the middle of exiles. Watch for the greater deliverance he has already accomplished in Christ, who led the true exodus at Jerusalem (Luke 9:31; Colossians 1:13-14).",
      "<strong>Take your place among the fishers of men.</strong> Jesus transformed Jeremiah's net of judgment into a net of rescue: &lsquo;Follow me, and I will make you fishers of men&rsquo; (Matthew 4:19). The nations are still coming to renounce their inherited lies, and God still sends ordinary people to cast the net. Speak of Christ to someone this week; you may be the fisher God sends to a hiding heart. <strong>Prayer prompt:</strong> &ldquo;Lord, my strength and my stronghold, my refuge in the day of trouble &mdash; make my whole life a true sermon, not just my words. Keep me from excusing my sin by my inheritance, and let me own it and be forgiven. When I am under your discipline, help me find the promise you have buried in it &mdash; the greater exodus accomplished by Christ. And make me a fisher of men, until the nations come from the ends of the earth and know that your name is the Lord. Amen.&rdquo;",
    ],
  },
];

const data: SectionGuideData = {
  accent: "#6B4FBB",
  badge: "Jeremiah 16",
  title: "Jeremiah 16: A Greater Exodus and Many Fishers",
  intro: "The prophet's life itself becomes the sermon: God forbids Jeremiah to marry, to mourn, or to feast, because children born in this place will die unlamented and the voice of bridegroom and bride is about to fall silent. Yet into the very sentence of exile -- 'I will hurl you out of this land' -- God buries the brightest promise so far: a new exodus from the north country that will eclipse Egypt and rewrite Israel's confession. Fishers and hunters are sent as agents of inescapable judgment, but the chapter ends with the nations streaming from the ends of the earth to renounce their inherited lies.",
  tabs: TABS,
  sections,
  calloutTitle: "The Net of Judgment Becomes the Net of Rescue",
  calloutBody: "In Jeremiah, 'many fishers' are sent to catch a people for judgment, from whom no cleft of rock can hide (16:16-17). Jesus reached into that very image and turned it inside out: 'Follow me, and I will make you fishers of men' (Matt 4:19) -- the same thoroughness, now serving rescue rather than wrath. And the new exodus promised inside the oracle of exile (16:14-15) was accomplished by Christ at Jerusalem -- Luke calls his death and resurrection his 'exodus' (Luke 9:31) -- delivering God's people from the deeper bondage of sin and death (Col 1:13-14). What sin made a manhunt, Christ made a mission.",
};

export default function Page() {
  return <SectionGuideTemplate data={data} />;
}
