"use client";
import SectionGuideTemplate, { type SectionGuideData } from "@/components/SectionGuideTemplate";

const TABS: string[] = [
  "Overview",
  "Twenty-Three Years of Speaking",
  "Seventy Years and My Servant",
  "The Cup of the Wine of Wrath",
  "Application",
];

const sections = [
  {
    id: "Overview",
    heading: "Overview of Jeremiah 25",
    reference: "Jeremiah 25:1&ndash;38",
    paragraphs: [
      "Jeremiah 25 is a hinge chapter, and it is dated to a hinge year: &lsquo;the fourth year of Jehoiakim&hellip; which was the first year of Nebuchadnezzar king of Babylon&rsquo; (25:1) &mdash; 605 BC, the year of Carchemish, when Babylon shattered Egypt and inherited the world. Standing at that turning point, Jeremiah looks back over twenty-three years of unheeded preaching, announces the length of the coming captivity, and then lifts his eyes from Judah to the whole earth, handing a cup of wine to every nation in turn. The chapter moves from a local sermon to a global assize.",
      "It unfolds in three movements. First, the indictment: for twenty-three years Jeremiah has spoken persistently and the people have not listened, and God has sent all his servants the prophets, &lsquo;rising early and sending them,&rsquo; to no effect (25:1-7). Second, the sentence and its limit: Nebuchadnezzar &mdash; called, astonishingly, &lsquo;my servant&rsquo; &mdash; will devastate the land, and these nations will serve Babylon seventy years; then God will punish Babylon itself and make it an everlasting waste (25:8-14). Third, the vision of the cup: Jeremiah is handed &lsquo;the cup of the wine of wrath&rsquo; and made to carry it to all the nations, who must drink and stagger, with Babylon drinking last of all, while the Lord roars from on high against all the inhabitants of the earth (25:15-38).",
      "Two of the chapter's phrases changed the course of biblical history. The first is &lsquo;Nebuchadnezzar&hellip; my servant&rsquo; (25:9) &mdash; a title of honor given to a pagan conqueror who did not know the Lord. It is one of Scripture's strongest statements of God's sovereignty over world politics: empires rise and fall as instruments in his hand, whether or not they acknowledge him (compare Isaiah's &lsquo;Cyrus, my shepherd,&rsquo; Isaiah 44:28). The second is &lsquo;seventy years&rsquo; (25:11) &mdash; a number that turns an open-ended catastrophe into a bounded discipline. Daniel would later read this very verse and set himself to pray (Daniel 9:2), and the Chronicler would record its fulfillment when Cyrus released the captives (2 Chronicles 36:21-23; Ezra 1:1).",
      "But the image that towers over the chapter, and over the whole Bible, is the cup. To drink the cup of God's wrath is to receive the full measure of what sin deserves &mdash; a picture that runs from the Psalms (75:8) through Isaiah (51:17) to Revelation (14:10). Every nation must drink; judgment begins &lsquo;at the city that is called by my name&rsquo; (25:29). And then, in the garden of Gethsemane, the Son of God knelt before that same cup and prayed, &lsquo;Father, if you are willing, remove this cup from me. Nevertheless, not my will, but yours, be done&rsquo; (Luke 22:42); and to Peter he said, &lsquo;shall I not drink the cup that the Father has given me?&rsquo; (John 18:11). The cup Jeremiah carried to the nations, Christ drank to the dregs for his people.",
    ],
  },
  {
    id: "Twenty-Three Years of Speaking",
    heading: "Rising Early and Sending Them",
    reference: "Jeremiah 25:1&ndash;7",
    paragraphs: [
      "The chapter opens with an accounting of the prophet's own ministry: &ldquo;For twenty-three years, from the thirteenth year of Josiah&hellip; to this day, the word of the Lord has come to me, and I have spoken persistently to you, but you have not listened&rdquo; (25:3). Twenty-three years &mdash; more than two decades of preaching through three kings, with beatings, mockery, plots, and stocks along the way, and the summary verdict is four words: &lsquo;you have not listened.&rsquo; It is worth sitting with that. Faithfulness is not measured by visible results; Jeremiah is among the most faithful men in Scripture and among the least successful by any metric his contemporaries would have recognized.",
      "Nor was Jeremiah the only voice: &ldquo;You have neither listened nor inclined your ears to hear, although the Lord persistently sent to you all his servants the prophets&rdquo; (25:4). The Hebrew idiom behind &lsquo;persistently&rsquo; is vivid &mdash; literally &lsquo;rising early and sending.&rsquo; It pictures God as a householder who gets up before dawn, day after day, to dispatch another messenger to a house that will not open the door. It is one of the tenderest pictures of divine patience in the Old Testament: God is not reluctant to warn but eager, not slow to speak but early. &lsquo;The Lord is not slow to fulfill his promise&hellip; but is patient toward you, not wishing that any should perish&rsquo; (2 Peter 3:9).",
      "And what did all those early-rising messengers say? &ldquo;Turn now, every one of you, from his evil way and evil deeds, and dwell upon the land that the Lord has given to you and your fathers from of old and forever. Do not go after other gods to serve and worship them, or provoke me to anger with the work of your hands&rdquo; (25:5-6). The message across two centuries of prophets compresses to a single word: <em>turn</em>. And the offer attached to it is not austerity but home &mdash; dwell in the land, forever. Repentance in Scripture is never God grudgingly granting a reprieve; it is God holding open the door of his house.",
      "The refusal is stated twice for emphasis: &ldquo;Yet you have not listened to me&hellip; that you might provoke me to anger with the work of your hands to your own harm&rdquo; (25:7). That last phrase is the quiet tragedy of all idolatry: <em>to your own harm</em>. God is not diminished when we worship the work of our hands; we are. The parable Jesus told of the vineyard owner who sent servant after servant, and finally his son, is the New Testament's retelling of Jeremiah 25:4 (Mark 12:1-8) &mdash; and it ends with the astonishing measure of God's patience, and the terrible measure of the response. The God who rose early to send prophets finally sent his Son.",
    ],
  },
  {
    id: "Seventy Years and My Servant",
    heading: "A Sentence with a Limit",
    reference: "Jeremiah 25:8&ndash;14",
    paragraphs: [
      "The sentence falls with a formula that must have stunned its first hearers: &ldquo;Because you have not obeyed my words, behold, I will send for all the tribes of the north, declares the Lord, and for Nebuchadnezzar the king of Babylon, my servant, and I will bring them against this land&rdquo; (25:8-9). <em>My servant.</em> The title elsewhere belongs to Abraham, Moses, David, and the suffering Servant of Isaiah &mdash; and here God places it on a pagan emperor who worships Marduk and has never prayed to the Lord in his life. Nebuchadnezzar is not a believer; he is an instrument. He will do exactly what God intends while pursuing his own ambitions entirely (compare Isaiah 10:5-7, where Assyria is God's rod and does not know it).",
      "This is the Bible's unflinching doctrine of providence over history. &lsquo;The king's heart is a stream of water in the hand of the Lord; he turns it wherever he will&rsquo; (Proverbs 21:1). No empire, election, or invasion falls outside that governance &mdash; a truth that is terrifying when God's instrument is marching toward you and unshakably comforting when the world seems to be spinning free. The desolation is described without euphemism: God will banish &ldquo;the voice of mirth and the voice of gladness, the voice of the bridegroom and the voice of the bride, the grinding of the millstones and the light of the lamp&rdquo; (25:10) &mdash; the sounds of ordinary human joy, silenced.",
      "And then, in the middle of the sentence, mercy sets a boundary: &ldquo;This whole land shall become a ruin and a waste, and these nations shall serve the king of Babylon seventy years&rdquo; (25:11). A number changes everything. An unmeasured judgment is despair; a measured one is discipline. Seventy years is long enough that most who heard it would die in exile, and short enough that their children would come home. God's chastisement of his people always has a term written into it: &lsquo;he does not retain his anger forever&rsquo; (Micah 7:18); &lsquo;for his anger is but for a moment, and his favor is for a lifetime&rsquo; (Psalm 30:5).",
      "Nor is Babylon exempt from the justice it administers: &ldquo;Then after seventy years are completed, I will punish the king of Babylon and that nation&hellip; for their iniquity, declares the Lord, making the land an everlasting waste&rdquo; (25:12). The rod is not righteous merely because God wields it; instruments of judgment are themselves judged. This verse became one of the most consequential in Scripture: &lsquo;I, Daniel, perceived in the books the number of years that, according to the word of the Lord to Jeremiah the prophet, must pass before the end of the desolations of Jerusalem, namely, seventy years&rsquo; (Daniel 9:2) &mdash; and Daniel responded not by waiting passively but by praying. A promise with a date on it is an invitation to intercede. The Chronicler recorded the fulfillment: &lsquo;to fulfill the word of the Lord by the mouth of Jeremiah&hellip; the Lord stirred up the spirit of Cyrus&rsquo; (2 Chronicles 36:21-22). God keeps the calendar he announces.",
    ],
  },
  {
    id: "The Cup of the Wine of Wrath",
    heading: "You Must Drink",
    reference: "Jeremiah 25:15&ndash;38",
    paragraphs: [
      "The final movement widens from Judah to the world: &ldquo;Take from my hand this cup of the wine of wrath, and make all the nations to whom I send you drink it. They shall drink and stagger and be crazed because of the sword that I am sending among them&rdquo; (25:15-16). In the ancient world a cup passed around a banquet table could mean fellowship or fate; here it is the draught of judgment, and the drinkers reel like men who have drunk far past their capacity. Jeremiah must serve it: &ldquo;So I took the cup from the Lord's hand, and made all the nations to whom the Lord sent me drink it&rdquo; (25:17).",
      "The guest list is long and deliberately comprehensive &mdash; Jerusalem and the cities of Judah first, then Pharaoh and all Egypt, Uz, the Philistine cities, Edom, Moab, Ammon, Tyre, Sidon, Dedan, Tema, Buz, Arabia, Zimri, Elam, Media, &ldquo;all the kingdoms of the world that are on the face of the earth&rdquo; (25:18-26). Small nations and superpowers, near neighbors and distant empires, all receive the same cup from the same hand. God's moral government is not tribal; there is no nation with diplomatic immunity before the Judge of all the earth. And the list ends with a coded name: &ldquo;and after them the king of Babylon shall drink&rdquo; (25:26) &mdash; the cupbearer empire drinks last.",
      "Two lines in this section are especially weighty. The first is God's refusal to let anyone decline: &ldquo;And if they refuse to accept the cup from your hand to drink, then you shall say to them, &lsquo;Thus says the Lord of hosts: You must drink!&rsquo;&rdquo; (25:28). The second is the ordering principle of divine judgment: &ldquo;For behold, I begin to work disaster at the city that is called by my name, and shall you go unpunished? You shall not go unpunished&rdquo; (25:29). Judgment starts with the people who bear God's name. Peter says exactly this to the church: &lsquo;it is time for judgment to begin at the household of God; and if it begins with us, what will be the outcome for those who do not obey the gospel of God?&rsquo; (1 Peter 4:17). Privilege accelerates accountability; it never exempts.",
      "The chapter closes with the Lord as both lion and storm: &ldquo;The Lord will roar from on high, and from his holy habitation utter his voice&hellip; he shall give a shout, like those who tread grapes, against all the inhabitants of the earth&rdquo; (25:30), while the shepherds of the nations wail and their flocks are scattered (25:34-36). It is a terrifying close &mdash; and it is the exact backdrop against which Gethsemane must be read. In that garden, the Son of God looked at this cup &mdash; the accumulated wrath owed to every nation on Jeremiah's list &mdash; and prayed, &lsquo;Father, if you are willing, remove this cup from me. Nevertheless, not my will, but yours, be done&rsquo; (Luke 22:42). He did not refuse it: &lsquo;shall I not drink the cup that the Father has given me?&rsquo; (John 18:11). The wine of God's wrath was pressed out, and Christ drained it, so that his people might receive instead a different cup: &lsquo;this cup is the new covenant in my blood&rsquo; (Luke 22:20). Two cups stand at the center of the Bible, and everything depends on which one you drink.",
    ],
  },
  {
    id: "Application",
    heading: "Living Jeremiah 25",
    reference: "Reflections on Patience, Providence, and the Cup",
    paragraphs: [
      "<strong>Measure faithfulness by obedience, not by results.</strong> Jeremiah preached for twenty-three years to a nation that would not listen, and Scripture counts him among its greatest servants. If you are teaching, parenting, witnessing, or serving with little visible fruit, you are in the best company there is. &lsquo;It is required of stewards that they be found faithful&rsquo; (1 Corinthians 4:2) &mdash; faithful, not successful. Keep speaking; the harvest belongs to God.",
      "<strong>Marvel at a God who rises early to send messengers.</strong> The picture of God getting up before dawn, day after day, to send another warning to a house that will not open is the picture of his patience toward you. Every conviction, every sermon that landed, every friend who spoke the truth &mdash; these were early-morning messengers. Do not let today's be the one you ignore. &lsquo;Today, if you hear his voice, do not harden your hearts&rsquo; (Hebrews 3:15).",
      "<strong>Rest in God's sovereignty over the headlines.</strong> Nebuchadnezzar was called God's servant while worshiping other gods and pursuing his own empire. The powers that trouble our age &mdash; political, economic, cultural &mdash; are not outside God's governance, however loudly they boast. &lsquo;The king's heart is a stream of water in the hand of the Lord&rsquo; (Proverbs 21:1). Pray for rulers, work for justice, and refuse both panic and despair.",
      "<strong>Give thanks that Christ drank the cup you deserved.</strong> The cup passed to every nation in Jeremiah 25 was lifted in Gethsemane by the only truly innocent Man, and drained at Calvary. Because he drank the cup of wrath, believers are handed the cup of the new covenant instead. Let the Lord's Supper never become routine &mdash; it is the cup of blessing purchased by the cup of judgment. <strong>Prayer prompt:</strong> &ldquo;Father, thank you for rising early, again and again, to send your word to me &mdash; and forgive me for the times I did not open the door. Make me faithful where I see no fruit, and keep me trusting your hand over nations and news that frighten me. Above all, thank you that the Lord Jesus took the cup of wrath from your hand and drank it to the dregs, so that I may drink the cup of the new covenant in his blood. Amen.&rdquo;",
    ],
  },
];

const data: SectionGuideData = {
  accent: "#E11D48",
  badge: "Jeremiah 25",
  title: "Jeremiah 25: Seventy Years and the Cup of Wrath",
  intro: "Dated to 605 BC -- the year Babylon inherited the world -- this hinge chapter looks back on twenty-three years of unheeded preaching and a God who kept 'rising early and sending' his prophets. Then comes the sentence with a limit: Nebuchadnezzar, called astonishingly 'my servant,' will devastate the land, and the nations will serve Babylon seventy years -- a number Daniel would later read and pray over. Finally Jeremiah is handed the cup of the wine of wrath and made to carry it to every nation on earth, beginning with the city called by God's name.",
  tabs: TABS,
  sections,
  calloutTitle: "Two Cups at the Center of the Bible",
  calloutBody: "To drink the cup of God's wrath is to receive the full measure of what sin deserves -- an image running from Psalm 75:8 through Isaiah 51:17 to Revelation 14:10. Every nation must drink, and judgment begins 'at the city that is called by my name' (25:29; cf. 1 Pet 4:17). Then in Gethsemane the Son of God knelt before that same cup: 'Father, if you are willing, remove this cup from me. Nevertheless, not my will, but yours' (Luke 22:42), and 'shall I not drink the cup that the Father has given me?' (John 18:11). He drained the cup of wrath so his people could receive another: 'this cup is the new covenant in my blood' (Luke 22:20).",
};

export default function Page() {
  return <SectionGuideTemplate data={data} />;
}
