"use client";
import SectionGuideTemplate, { type SectionGuideData } from "@/components/SectionGuideTemplate";

const TABS: string[] = [
  "Overview",
  "Do Justice, O House of David",
  "Is Not This to Know Me?",
  "The Signet Ring Torn Off",
  "Application",
];

const sections = [
  {
    id: "Overview",
    heading: "Overview of Jeremiah 22",
    reference: "Jeremiah 22:1&ndash;30",
    paragraphs: [
      "Jeremiah 22 is the prophet's audit of the royal house &mdash; a series of oracles naming Judah's last kings one by one and measuring each against the only standard that matters on David's throne: justice and righteousness. Sent down to the king's palace itself, Jeremiah declares the terms &mdash; do justice, deliver the robbed, protect the sojourner, the fatherless, and the widow &mdash; and then walks through the royal succession like a man reading gravestones: Shallum, who will die in exile; Jehoiakim, who built his cedar splendor on unpaid labor and will be buried like a donkey; and Coniah, the signet ring torn from God's finger and hurled into Babylon.",
      "The chapter unfolds in three movements. First, the standing charge to the dynasty: the throne of David exists for justice, and the palace that abandons justice becomes a desolation &mdash; passersby will ask why, and the answer will be the abandoned covenant (22:1-9). Second, the oracles against Shallum (Jehoahaz), carried to Egypt never to return, and against Jehoiakim, the king who enlarged his palace by fraud while his father's justice rotted in his memory &mdash; climaxing in the most searching definition of true religion in the prophets: &lsquo;He judged the cause of the poor and needy&hellip; Is not this to know me? declares the Lord&rsquo; (22:10-19). Third, the lament over Jerusalem and the terrible word to Coniah (Jehoiachin) &mdash; the signet ring removed, the man written down &lsquo;childless,&rsquo; no offspring of his to prosper on David's throne (22:20-30).",
      "The chapter's center of gravity is the contrast between two kings and two definitions of kingship. Josiah &lsquo;ate and drank and did justice and righteousness&hellip; He judged the cause of the poor and needy; then it was well&rsquo; (22:15-16) &mdash; a king who lived normally and ruled righteously. His son Jehoiakim &lsquo;built his house by unrighteousness&hellip; making his neighbor serve him for nothing&rsquo; (22:13), competing in cedar as though paneling were proof of majesty. And into that contrast God drops his thunderbolt: caring for the poor and needy &mdash; &lsquo;is not this to know me?&rsquo; Knowing God, in the grammar of this verse, is not first mystical experience or doctrinal mastery; it is the practiced love of justice, because the God being known is the Father of the fatherless (Psalm 68:5). Theology and ethics are one fabric.",
      "And yet the chapter ends at the edge of an abyss that only the gospel bridges. Coniah's curse &mdash; &lsquo;none of his offspring shall succeed in sitting on the throne of David&rsquo; (22:30) &mdash; seems to slam the door on the Davidic promise itself. But God's grace outmaneuvers even his own judgments: Coniah's grandson Zerubbabel is later chosen and called God's &lsquo;signet ring&rsquo; (Haggai 2:23), the curse's image deliberately reversed; and Matthew's genealogy runs the legal line of Jesus straight through &lsquo;Jechoniah&rsquo; (Matthew 1:11-12) &mdash; the Messiah inheriting David's throne legally through Joseph while born of Mary, untouched by the curse on Coniah's bloodline. Where human kingship dies childless, God raises up the King whose right is everlasting (Luke 1:32-33).",
    ],
  },
  {
    id: "Do Justice, O House of David",
    heading: "The Palace Measured by the Covenant",
    reference: "Jeremiah 22:1&ndash;12",
    paragraphs: [
      "The oracle begins with a descent: &ldquo;Thus says the Lord: Go down to the house of the king of Judah and speak there this word&rdquo; (22:1). Jeremiah must carry the word into the palace itself &mdash; to the king on David's throne, his servants, and his people at the gates. The charge is the dynasty's original job description: &ldquo;Do justice and righteousness, and deliver from the hand of the oppressor him who has been robbed. And do no wrong or violence to the resident alien, the fatherless, and the widow, nor shed innocent blood in this place&rdquo; (22:3). The throne exists for the protection of precisely the people who cannot repay a king &mdash; the foreigner, the orphan, the widow, the robbed. Power, in God's economy, is a trust held on behalf of the weak (Psalm 72:4, 12-14).",
      "The alternative futures are set out with covenant clarity: obedience means &ldquo;there shall enter the gates of this house kings who sit on the throne of David&hellip; But if you will not obey these words, I swear by myself, declares the Lord, that this house shall become a desolation&rdquo; (22:4-5). God swears by himself &mdash; the strongest oath heaven can give (Hebrews 6:13) &mdash; that the dynasty's continuance rides on its justice. Even the beloved palace, &lsquo;like Gilead to me, like the summit of Lebanon&rsquo; (22:6), will be made a wilderness; cutters will fell its choicest cedars and cast them into the fire (22:7). The cedar that impressed men would not impress the flames.",
      "Then a scene from the aftermath: &ldquo;And many nations will pass by this city, and every man will say to his neighbor, &lsquo;Why has the Lord dealt thus with this great city?&rsquo; And they will answer, &lsquo;Because they abandoned the covenant of the Lord their God and worshiped other gods and served them&rsquo;&rdquo; (22:8-9). The ruins themselves will catechize the nations &mdash; the fallen city becoming a public lesson in covenant theology, exactly as Deuteronomy foresaw (Deuteronomy 29:24-26). When the people of God fall, the watching world reads the sermon.",
      "The first named king follows: &ldquo;Weep not for him who is dead, nor grieve for him, but weep bitterly for him who goes away, for he shall return no more to see his native land&rdquo; (22:10). The dead king is Josiah, killed at Megiddo; the one who &lsquo;goes away&rsquo; is his son Shallum &mdash; Jehoahaz &mdash; deposed by Pharaoh Neco after three months and dragged to Egypt, &ldquo;and he shall never return&hellip; but in the place where they have carried him captive, there shall he die&rdquo; (22:11-12). Exile without homecoming, Jeremiah says, is a fate worth more tears than death itself. It is the first tolling of a bell that will ring through the rest of the chapter: the throne that forgot the covenant forfeits the land, king by king by king.",
    ],
  },
  {
    id: "Is Not This to Know Me?",
    heading: "Josiah's Justice and Jehoiakim's Cedar",
    reference: "Jeremiah 22:13&ndash;19",
    paragraphs: [
      "The oracle against Jehoiakim opens with a woe: &ldquo;Woe to him who builds his house by unrighteousness, and his upper rooms by injustice, who makes his neighbor serve him for nothing and does not give him his wages&rdquo; (22:13). Installed by Pharaoh and squeezed by tribute, Jehoiakim chose that moment of national poverty to enlarge his palace &mdash; &ldquo;a great house with spacious upper rooms&hellip; paneling it with cedar and painting it with vermilion&rdquo; (22:14) &mdash; and paid for it with conscripted, unpaid labor. The sin is specific and social: wages withheld, neighbors enslaved to a king's vanity. Scripture never forgets this sin; James hears the withheld wages themselves crying out to the Lord of hosts (James 5:4; cf. Leviticus 19:13).",
      "Then comes the devastating question: &ldquo;Do you think you are a king because you compete in cedar?&rdquo; (22:15). Jehoiakim had confused the furniture of royalty with its function &mdash; as though paneling were proof of majesty. Against him God raises the memory of his father: &ldquo;Did not your father eat and drink and do justice and righteousness? Then it was well with him&rdquo; (22:15). Josiah lived an ordinary human life &mdash; he ate and drank &mdash; and did the king's true work; and &lsquo;it was well with him,&rsquo; a quiet refrain repeated like a bell. Majesty is not cedar; majesty is justice.",
      "And then the verse that towers over the chapter: &ldquo;He judged the cause of the poor and needy; then it was well. Is not this to know me? declares the Lord&rdquo; (22:16). Here is the prophets' most compressed definition of the knowledge of God. To know the Lord is not merely to hold correct opinions about him or to feel warmly toward him; it is to be conformed to what he loves &mdash; and he is &lsquo;Father of the fatherless and protector of widows&rsquo; (Psalm 68:5). John writes the same grammar into the new covenant: &lsquo;whoever does not love does not know God, because God is love&rsquo; (1 John 4:8); and Jesus locates the verdict of the last day in bread given, strangers welcomed, prisoners visited &mdash; &lsquo;as you did it to one of the least of these&hellip; you did it to me&rsquo; (Matthew 25:40). Doctrine divorced from justice is not knowledge of God but information about a stranger.",
      "Jehoiakim's heart is read aloud &mdash; &ldquo;you have eyes and heart only for your dishonest gain, for shedding innocent blood, and for practicing oppression and violence&rdquo; (22:17) &mdash; and his end is announced with shocking indignity: no one will lament him; &ldquo;with the burial of a donkey he shall be buried, dragged and dumped beyond the gates of Jerusalem&rdquo; (22:18-19). The king who competed in cedar receives a carcass's disposal. It is the Bible's grim epitaph over every life that mistakes accumulation for greatness: the paneling stays behind, and the verdict follows the deeds. &lsquo;For what does it profit a man to gain the whole world and forfeit his soul?&rsquo; (Mark 8:36). The true King would later say of true greatness: &lsquo;let the greatest among you become as the youngest, and the leader as one who serves&rsquo; (Luke 22:26).",
    ],
  },
  {
    id: "The Signet Ring Torn Off",
    heading: "Write This Man Down Childless",
    reference: "Jeremiah 22:20&ndash;30",
    paragraphs: [
      "Before the final king, a lament over the city herself: &ldquo;Go up to Lebanon, and cry out&hellip; for all your lovers are destroyed&rdquo; (22:20). Jerusalem's &lsquo;lovers&rsquo; &mdash; her foreign allies and idols &mdash; have failed her, and God names the long history behind the collapse: &ldquo;I spoke to you in your prosperity, but you said, &lsquo;I will not listen.&rsquo; This has been your way from your youth, that you have not obeyed my voice&rdquo; (22:21). There is the anatomy of a hardened heart in a single line: prosperity made her deaf. Comfort, not crisis, is where most apostasy is manufactured; the ears close while the barns fill (Deuteronomy 8:11-14; Revelation 3:17).",
      "Then the word falls on Coniah &mdash; Jehoiachin, Jehoiakim's son, three months on the throne before the first deportation: &ldquo;As I live, declares the Lord, though Coniah&hellip; were the signet ring on my right hand, yet I would tear you off and give you into the hand of those who seek your life&rdquo; (22:24-25). The signet ring was the instrument of royal authority &mdash; the king's own identity pressed into wax; to wear it on God's hand was the Davidic king's glory (cf. Psalm 89:20-27). And God says: even that I will tear off. No office, however sacred its origin, shields the unfaithful from judgment. Coniah and his mother will be &lsquo;hurled&rsquo; into another country, &ldquo;and to the land to which they long to return, there they shall not return&rdquo; (22:26-27).",
      "The oracle closes with a triple summons and a sentence like a tomb door closing: &ldquo;O land, land, land, hear the word of the Lord! Thus says the Lord: &lsquo;Write this man down as childless, a man who shall not succeed in his days, for none of his offspring shall succeed in sitting on the throne of David and ruling again in Judah&rsquo;&rdquo; (22:29-30). Jehoiachin was not literally childless &mdash; his sons appear in the records (1 Chronicles 3:17-18) &mdash; but dynastically he was: no descendant of his would reign. With that, the lamp of David seems to gutter out. The chapter that began with &lsquo;do justice, O house of David&rsquo; ends with the house written off.",
      "But watch what grace does with a dead end. A generation later, God speaks to Zerubbabel &mdash; Jehoiachin's own grandson, governor but never king &mdash; and deliberately reverses the image: &ldquo;I will take you, O Zerubbabel&hellip; and make you like a signet ring, for I have chosen you&rdquo; (Haggai 2:23). The ring torn off is, in mercy, put back on. And Matthew's genealogy carries the line forward: &lsquo;Josiah the father of Jechoniah&hellip; and Jacob the father of Joseph the husband of Mary, of whom Jesus was born&rsquo; (Matthew 1:11-16). Jesus receives David's throne <em>legally</em> through Joseph &mdash; heir of the royal line &mdash; while being born of Mary by the Spirit, so that the curse on Coniah's bloodline never touches him. The judgment stands, and the promise stands, and both are satisfied in one Person. &lsquo;The Lord God will give to him the throne of his father David&hellip; and of his kingdom there will be no end&rsquo; (Luke 1:32-33). Where every earthly succession fails, God's King reigns forever.",
    ],
  },
  {
    id: "Application",
    heading: "Living Jeremiah 22",
    reference: "Reflections on Power, Justice, and Knowing God",
    paragraphs: [
      "<strong>Measure greatness by justice, not by cedar.</strong> Jehoiakim thought paneling proved majesty; God asked, &lsquo;Do you think you are a king because you compete in cedar?&rsquo; Our age competes in square footage, follower counts, and titles &mdash; the same contest with new materials. Whatever platform or resources you hold, they are a trust for the protection of the weak, not a scoreboard. &lsquo;Let the greatest among you become as the youngest, and the leader as one who serves&rsquo; (Luke 22:26).",
      "<strong>Let your knowledge of God prove itself in care for the vulnerable.</strong> &lsquo;He judged the cause of the poor and needy&hellip; Is not this to know me?&rsquo; (22:16). Doctrine and devotion that never reach the orphan, the widow, the stranger, or the underpaid worker are information about a stranger, not knowledge of the living God. Choose one concrete act of justice or mercy this week &mdash; and pay every wage you owe promptly and fully (James 5:4).",
      "<strong>Beware the deafness that prosperity breeds.</strong> &lsquo;I spoke to you in your prosperity, but you said, &ldquo;I will not listen&rdquo;&rsquo; (22:21). Comfort closes ears more surely than crisis; most drifting happens in good times. Build listening into your abundance &mdash; Scripture before screens, sabbath before schedule, generosity before accumulation &mdash; so that ease does not do to you what siege could not.",
      "<strong>Trust the King who stands on the far side of every dead end.</strong> The Coniah curse looked like the end of God's promise &mdash; and God threaded his grace through it, restoring the signet in Zerubbabel and seating Jesus on David's throne, legally heir yet untouched by the curse. No failure, yours or your family's, outruns his ability to keep his promises. <strong>Prayer prompt:</strong> &ldquo;Lord God, strip me of the cedar-competition &mdash; the itch to prove myself by what I build and own. Teach me that to know you is to love justice, and make my hands quick for the poor, the fatherless, and the wronged. Do not let prosperity make me deaf; I choose to listen now, in the good days. And thank you that when every human line dies childless, your King still reigns &mdash; Jesus, Son of David, whose kingdom has no end. Amen.&rdquo;",
    ],
  },
];

const data: SectionGuideData = {
  accent: "#0D9488",
  badge: "Jeremiah 22",
  title: "Jeremiah 22: Is Not This to Know Me?",
  intro: "Jeremiah walks into the palace and audits Judah's last kings against the throne's one job: justice. Shallum will die in exile; Jehoiakim, who built cedar splendor on unpaid wages, will be buried like a donkey -- 'Do you think you are a king because you compete in cedar?' Against him stands Josiah, who 'judged the cause of the poor and needy... Is not this to know me? declares the Lord.' Then Coniah: the signet ring torn from God's hand, written down childless -- a dead end for David's line that only the gospel threads: the ring restored in Zerubbabel, and the throne given forever to Jesus.",
  tabs: TABS,
  sections,
  calloutTitle: "Knowing God Means Loving Justice",
  calloutBody: "The chapter's thunderbolt: 'He judged the cause of the poor and needy; then it was well. Is not this to know me? declares the Lord' (22:16). Knowing God is not first mystical experience or doctrinal mastery but conformity to what he loves -- for he is 'Father of the fatherless' (Ps 68:5). John writes the same grammar: 'whoever does not love does not know God' (1 John 4:8). And the Coniah curse that seemed to end David's line is outmaneuvered by grace: the signet restored (Hag 2:23), and Jesus -- legal heir through Joseph, born of Mary -- reigning on David's throne forever (Matt 1:11-16; Luke 1:32-33).",
};

export default function Page() {
  return <SectionGuideTemplate data={data} />;
}
