"use client";
import SectionGuideTemplate, { type SectionGuideData } from "@/components/SectionGuideTemplate";

const TABS: string[] = [
  "Overview",
  "Why Do the Wicked Prosper?",
  "If You Have Raced with Men on Foot",
  "I Have Forsaken My House",
  "Application",
];

const sections = [
  {
    id: "Overview",
    heading: "Overview of Jeremiah 12",
    reference: "Jeremiah 12:1&ndash;17",
    paragraphs: [
      "Jeremiah 12 records the prophet's second great &lsquo;confession&rsquo; &mdash; and one of the most honest prayers in all of Scripture. Fresh from discovering that his own townsmen of Anathoth were plotting his murder (11:18-23), Jeremiah brings his bewilderment straight to God: &ldquo;Righteous are you, O Lord, when I complain to you; yet I would plead my case before you. Why does the way of the wicked prosper?&rdquo; (12:1). It is the ancient question of the faithful &mdash; the question of Job 21, of Psalm 73, of every believer who has watched treachery thrive while integrity suffers. And God's answer is one of the most bracing in the Bible: not an explanation, but a summons to endurance. &ldquo;If you have raced with men on foot, and they have wearied you, how will you compete with horses?&rdquo; (12:5).",
      "The chapter unfolds in three movements. First, Jeremiah files his complaint like a lawsuit he already knows he will lose &mdash; conceding God's righteousness before pressing his charge, protesting the prosperity of the treacherous, and asking God to drag them off &lsquo;like sheep for the slaughter&rsquo; (12:1-4). Second, God answers his prophet not with a theodicy but with a challenge: harder races are coming, and even his own family has turned against him (12:5-6). Third, God opens his own heart in lament &mdash; &ldquo;I have given the beloved of my soul into the hands of her enemies&rdquo; (12:7) &mdash; describing the ruin of his heritage, before closing with an astonishing promise of compassion and inclusion for the very nations that ravaged it (12:7-17).",
      "The deep theological movement of the chapter is from Jeremiah's grief to God's grief. The prophet complains that the wicked prosper; God replies that he himself is about to hand over &lsquo;the beloved of my soul&rsquo; to her enemies. Jeremiah's pain over Anathoth is real, but it is a small window into the far greater pain of a God whose own covenant people have become &lsquo;like a lion in the forest&rsquo; roaring against him (12:8). The chapter refuses to let us imagine a detached deity dispensing cold verdicts. The Judge weeps over the sentence. The Owner of the vineyard grieves what the shepherds have trampled (12:10). And no one lays it to heart (12:11).",
      "Read in the light of the gospel, Jeremiah 12 points forward at every turn. The servant wearied by footmen and summoned to run with horses anticipates the call of Hebrews: &ldquo;let us run with endurance the race that is set before us, looking to Jesus&hellip; who endured from sinners such hostility against himself&rdquo; (Hebrews 12:1-3). The God who gave &lsquo;the beloved of my soul&rsquo; into the hands of her enemies foreshadows the Father who &ldquo;did not spare his own Son but gave him up for us all&rdquo; (Romans 8:32). And the closing promise that repentant pagan nations &ldquo;shall be built up in the midst of my people&rdquo; (12:16) is an early sunrise of the mystery Paul proclaimed &mdash; Gentiles once &lsquo;far off&rsquo; brought near by the blood of Christ (Ephesians 2:12-13).",
    ],
  },
  {
    id: "Why Do the Wicked Prosper?",
    heading: "Righteous Are You, O Lord, Yet I Would Plead My Case",
    reference: "Jeremiah 12:1&ndash;4",
    paragraphs: [
      "Jeremiah opens with the language of the courtroom: &ldquo;Righteous are you, O Lord, when I complain to you; yet I would plead my case before you&rdquo; (12:1). He is filing a lawsuit he already knows he will lose &mdash; before a Judge he confesses to be perfectly just. This is crucial. Jeremiah's complaint is not the sneer of the skeptic but the anguish of the believer; he begins by affirming God's righteousness and only then dares his question: &ldquo;Why does the way of the wicked prosper? Why do all who are treacherous thrive?&rdquo; (12:1). Faith does not forbid such questions; faith is precisely what makes them agonizing. Because Jeremiah believes God is righteous, the prosperity of traitors &mdash; likely the very men of Anathoth who plotted his death &mdash; feels like a contradiction demanding an answer.",
      "What sharpens the complaint is that God himself seems responsible: &ldquo;You plant them, and they take root; they grow and produce fruit&rdquo; (12:2). The treacherous are not weeds that sprang up behind God's back; they are, in Jeremiah's protest, trees the Lord himself planted and watered. Worse still, their religion is intact while their hearts are absent: &ldquo;you are near in their mouth and far from their heart&rdquo; (12:2). They speak of God fluently &mdash; perhaps the smooth words of 12:6 &mdash; while he is a stranger to their inner life. Jesus took up this very indictment: &ldquo;This people honors me with their lips, but their heart is far from me&rdquo; (Matthew 15:8, citing Isaiah 29:13). Prosperous hypocrisy is an old wound, and it wounds most those who serve God with their whole heart.",
      "Jeremiah's counter-plea is startling in its ferocity: &ldquo;But you, O Lord, know me; you see me, and test my heart toward you. Pull them out like sheep for the slaughter, and set them apart for the day of slaughter&rdquo; (12:3). The image deliberately reverses the previous chapter: there Jeremiah was &lsquo;a gentle lamb led to the slaughter&rsquo; (11:19); now he asks that his would-be butchers be dragged off as sheep themselves. He appeals to what God alone can verify &mdash; the tested sincerity of his own heart against the polished emptiness of theirs. Like the psalmist of Psalm 73, who nearly stumbled at &lsquo;the prosperity of the wicked&rsquo; until he went into the sanctuary and &lsquo;discerned their end&rsquo; (Psalm 73:3, 17), Jeremiah takes his protest into God's presence rather than nursing it in bitterness.",
      "The complaint widens from personal grievance to creation itself: &ldquo;How long will the land mourn and the grass of every field wither? For the evil of those who dwell in it the beasts and the birds are swept away&rdquo; (12:4). Human treachery is not a private affair; the ground groans under it, the drought bites, the animals perish. Sin unravels the very fabric of the world &mdash; a truth Paul universalizes when he writes that &ldquo;the creation was subjected to futility&rdquo; and &ldquo;has been groaning together in the pains of childbirth until now&rdquo; (Romans 8:20-22). And the wicked shrug it all off: &ldquo;He will not see our latter end&rdquo; (12:4) &mdash; God, they wager, is not watching and will never call the account due. Jeremiah's whole complaint hangs on the conviction that they are wrong &mdash; that the Judge of all the earth does see, and will do right (Genesis 18:25).",
    ],
  },
  {
    id: "If You Have Raced with Men on Foot",
    heading: "How Will You Compete with Horses?",
    reference: "Jeremiah 12:5&ndash;6",
    paragraphs: [
      "God's answer to Jeremiah's lawsuit is one of the most bracing replies in Scripture &mdash; not a verdict, not an explanation, but a question: &ldquo;If you have raced with men on foot, and they have wearied you, how will you compete with horses? And if in a safe land you are so trusting, what will you do in the thicket of the Jordan?&rdquo; (12:5). God does not tell Jeremiah why the wicked prosper. He tells him, in effect: the race you have run so far is the easy one. Anathoth was the footrace; Jerusalem's kings, priests, and mobs will be the horses. The quiet countryside was the safe land; the &lsquo;thicket of the Jordan&rsquo; &mdash; the tangled jungle along the river where lions lurked (49:19) &mdash; still lies ahead. If the prophet is winded now, he must find deeper strength, for harder days are coming.",
      "This answer can sound almost harsh until we see the love in it. God treats Jeremiah not as a complaint to be pacified but as a servant to be strengthened. He answers lament the way a trainer answers an athlete &mdash; by preparing him for the greater contest rather than excusing him from it. And the history of the book proves the mercy of this severity: Jeremiah will face the burning of his scroll, the stocks, the cistern, the fall of Jerusalem. Had God merely soothed him in chapter 12, he would have collapsed in chapter 38. Instead, God builds in his prophet the endurance that will carry him through forty years of rejection. So it is with us: God often strengthens his servants for greater races rather than removing the small ones.",
      "Then comes the wound within the wound: &ldquo;For even your brothers and the house of your father, even they have dealt treacherously with you; they are in full cry after you; do not believe them, though they speak friendly words to you&rdquo; (12:6). The Anathoth conspiracy of chapter 11 reached into Jeremiah's own family. The smooth speech &mdash; God near in their mouths (12:2) &mdash; masks pursuit. Here Jeremiah again prefigures his Lord: Jesus was rejected in his hometown synagogue at Nazareth (Luke 4:24-29), declared that &ldquo;a prophet is not without honor, except in his hometown and among his relatives&rdquo; (Mark 6:4), and knew what it was that &ldquo;not even his brothers believed in him&rdquo; (John 7:5). The servant of God's word must sometimes stand alone even at the family table &mdash; as Christ warned, &ldquo;a person's enemies will be those of his own household&rdquo; (Matthew 10:36).",
      "The New Testament takes up God's answer to Jeremiah and presses it upon every believer. &ldquo;Let us run with endurance the race that is set before us, looking to Jesus, the founder and perfecter of our faith&hellip; Consider him who endured from sinners such hostility against himself, so that you may not grow weary or fainthearted&rdquo; (Hebrews 12:1-3). The cure for weariness in the footrace is not a lighter course but a steadier gaze &mdash; fixed on the One who ran the hardest race of all and finished it. Paul says the same to Timothy: &ldquo;Share in suffering as a good soldier of Christ Jesus&rdquo; (2 Timothy 2:3). God's question to Jeremiah is his question to us: he is not mocking our weariness but enlarging our capacity, for &ldquo;he who began a good work in you will bring it to completion&rdquo; (Philippians 1:6), and his grace is sufficient for horses as well as footmen (2 Corinthians 12:9).",
    ],
  },
  {
    id: "I Have Forsaken My House",
    heading: "The Beloved of My Soul Given to Her Enemies",
    reference: "Jeremiah 12:7&ndash;17",
    paragraphs: [
      "Now God does something extraordinary: he answers his prophet's lament with a lament of his own. &ldquo;I have forsaken my house; I have abandoned my heritage; I have given the beloved of my soul into the hands of her enemies&rdquo; (12:7). Jeremiah grieved over Anathoth; God grieves over all Judah. And notice the tenderness in the very sentence of judgment &mdash; &lsquo;the beloved of my soul.&rsquo; Even as he hands her over, she is still his darling. The reason follows: &ldquo;My heritage has become to me like a lion in the forest; she has lifted up her voice against me; therefore I hate her&rdquo; (12:8). The people God carried out of Egypt now roar against him like a predator. The judgment of God is never the indifference of a distant tyrant; it is the broken-hearted verdict of wounded love.",
      "The images tumble out, each more desolate than the last. Judah is &ldquo;a speckled bird of prey&rdquo; that the other birds surround and attack (12:9) &mdash; strange among the nations and savaged by them. &ldquo;Many shepherds have destroyed my vineyard; they have trampled down my portion&rdquo; (12:10) &mdash; the rulers, foreign and domestic, have made God's pleasant portion &lsquo;a desolate wilderness.&rsquo; The sword of the Lord devours &ldquo;from one end of the land to the other&rdquo; (12:12); the people &ldquo;have sown wheat and have reaped thorns&rdquo; (12:13), all their labor come to nothing under God's fierce anger. And over it all hangs the saddest line in the chapter: &ldquo;The whole land is made desolate, but no man lays it to heart&rdquo; (12:11). The tragedy is not only the ruin but the numbness &mdash; devastation without repentance, judgment falling on a people too hardened to ask why.",
      "Then, with no warning, the chapter pivots to grace &mdash; and grace for the least likely recipients. Concerning the &lsquo;evil neighbors&rsquo; who ravaged Israel's heritage, God announces uprooting; but then: &ldquo;And after I have plucked them up, I will again have compassion on them&rdquo; (12:14-15). More astonishing still, God opens to pagan nations a place inside his own people: &ldquo;if they will diligently learn the ways of my people, to swear by my name, &lsquo;As the Lord lives,&rsquo; even as they taught my people to swear by Baal, then they shall be built up in the midst of my people&rdquo; (12:16). The nations that taught Judah idolatry may, through repentance and faith in Judah's God, be built into Judah's blessing. Here, in the middle of a judgment oracle, Gentile inclusion is foreseen &mdash; the promise to Abraham that in him &ldquo;all the families of the earth shall be blessed&rdquo; (Genesis 12:3) refusing to die even in the ashes.",
      "The gospel shines through both halves of this passage. First, the terrible sentence &mdash; &ldquo;I have given the beloved of my soul into the hands of her enemies&rdquo; (12:7) &mdash; is ultimately answered at the cross, where the Father spoke over Jesus, &ldquo;This is my beloved Son&rdquo; (Matthew 3:17), and then &ldquo;did not spare his own Son but gave him up for us all&rdquo; (Romans 8:32). The Son of Man was &ldquo;betrayed into the hands of sinners&rdquo; (Matthew 26:45) so that the beloved-but-treacherous people might be forgiven. Second, the promise to the nations is fulfilled in the gospel going to the Gentiles: those who were &ldquo;separated from Christ, alienated from the commonwealth of Israel&hellip; have been brought near by the blood of Christ&rdquo; (Ephesians 2:12-13), wild branches grafted into the ancient olive tree (Romans 11:17). Jeremiah 12 ends where the Bible ends &mdash; with people from every nation built up in the midst of God's people, swearing by the name of the living Lord.",
    ],
  },
  {
    id: "Application",
    heading: "Living Jeremiah 12",
    reference: "Reflections on Lament, Endurance, and the God Who Also Grieves",
    paragraphs: [
      "<strong>Bring your hardest questions to God, not away from him.</strong> Jeremiah did not suppress his bewilderment at prospering treachery, and he did not let it fester into unbelief &mdash; he carried it into God's presence and pleaded his case there (12:1). That is the difference between the lament of faith and the sneer of cynicism. Like Asaph, who was &lsquo;envious of the arrogant&rsquo; until he &ldquo;went into the sanctuary of God&rdquo; and &ldquo;discerned their end&rdquo; (Psalm 73:3, 17), take your protest to the throne. God is not threatened by honest questions; he is grieved by hearts that stop speaking to him. &ldquo;Cast all your anxieties on him, because he cares for you&rdquo; (1 Peter 5:7).",
      "<strong>Let today's footraces train you for tomorrow's horses.</strong> God answered Jeremiah's weariness not by shrinking the course but by strengthening the runner (12:5). Do not despise the smaller trials of this season &mdash; the difficult coworker, the thankless service, the private discipline &mdash; for God is using them to build the endurance you will need for races you cannot yet see. &ldquo;Let us run with endurance the race that is set before us, looking to Jesus&rdquo; (Hebrews 12:1-2), and &ldquo;share in suffering as a good soldier of Christ Jesus&rdquo; (2 Timothy 2:3). The God who calls you to compete with horses will himself supply the strength (Isaiah 40:31).",
      "<strong>Do not be surprised when opposition comes from those closest to you.</strong> Jeremiah's own brothers spoke friendly words while running in full cry after him (12:6), and Jesus warned that &ldquo;a person's enemies will be those of his own household&rdquo; (Matthew 10:36). If faithfulness to Christ has cost you standing in your own family, you are walking a road your Savior walked first &mdash; despised in Nazareth, disbelieved by his brothers (John 7:5), yet enduring without bitterness. Keep loving, keep truthful, refuse both naivety and revenge, and entrust your cause, as Jeremiah did, to the God who tests hearts (12:3; 1 Peter 2:23).",
      "<strong>Behold the God who gave up the beloved of his soul &mdash; for you.</strong> The deepest answer to &lsquo;why do the wicked prosper?&rsquo; is not an argument but a cross: God handed his own Beloved into the hands of enemies (12:7; Romans 8:32) so that the treacherous &mdash; including us &mdash; might be forgiven, and so that people from every nation might be &ldquo;built up in the midst of my people&rdquo; (12:16; Ephesians 2:13). Injustice does not get the last word; the Judge who sees our latter end has already borne the judgment himself. <strong>Prayer prompt:</strong> &ldquo;Righteous Father, I bring you my honest questions about the prosperity of the wicked and the weariness of the race. Do not let my complaint curdle into cynicism; meet me in the sanctuary and show me the end of the story. Strengthen me to run with horses &mdash; to endure harder days with a steadier gaze fixed on Jesus, who endured such hostility from sinners for me. When those closest to me deal treacherously, keep me from bitterness, and remind me that you gave the Beloved of your soul into the hands of enemies so that I could be built up in the midst of your people. Amen.&rdquo;",
    ],
  },
];

const data: SectionGuideData = {
  accent: "#E11D48",
  badge: "Jeremiah 12",
  title: "Jeremiah 12: Why Does the Way of the Wicked Prosper?",
  intro: "Fresh from the Anathoth plot, Jeremiah files a lawsuit he knows he will lose: 'Righteous are you, O Lord, when I complain to you... Why does the way of the wicked prosper?' God planted the treacherous and they took root; he is near in their mouths and far from their hearts. God's answer is not an explanation but a summons: 'If you have raced with men on foot, and they have wearied you, how will you compete with horses?' Then God opens his own grief -- 'I have given the beloved of my soul into the hands of her enemies' -- before ending with astonishing grace: even the evil neighbor nations, if they learn the ways of his people, 'shall be built up in the midst of my people.'",
  tabs: TABS,
  sections,
  calloutTitle: "God's Answer to Lament Is Strength -- and a Cross",
  calloutBody: "God answers Jeremiah's 'why do the wicked prosper?' not with explanations but with strengthening for harder races: 'If you have raced with men on foot... how will you compete with horses?' (12:5). And his deepest answer is that he too knows the cost of treachery -- 'I have given the beloved of my soul into the hands of her enemies' (12:7). At the cross the Father did not spare his own beloved Son but gave him up for us all (Rom 8:32), so that the treacherous might be forgiven and the far-off nations built up in the midst of his people (12:16; Eph 2:12-13).",
};

export default function Page() {
  return <SectionGuideTemplate data={data} />;
}
