"use client";
import { useState, useEffect } from "react";
import VideoEmbed from "@/components/VideoEmbed";

const BG = "#07070F";
const CARD = "#12121F";
const BORDER = "#1E1E32";
const ACCENT = "#0D9488";
const TEXT = "#F2F2F8";
const MUTED = "#9898B3";

const TABS = ["What Is Trauma", "Trauma in Scripture", "Theology of Suffering", "Healing and Therapy", "The Path to Wholeness", "Videos"] as const;
type Tab = (typeof TABS)[number];

interface Section {
  id: Tab;
  heading: string;
  paragraphs: string[];
}

const sections: Section[] = [
  {
    id: "What Is Trauma",
    heading: "What Is Trauma: Neuroscience and Theology",
    paragraphs: [
      "Trauma is not simply a difficult experience. It is a specific kind of wound to the nervous system &mdash; one in which the ordinary mechanisms by which human beings process and integrate experience are overwhelmed and disrupted. Bessel van der Kolk, the psychiatrist whose landmark 2014 book &ldquo;The Body Keeps the Score&rdquo; brought trauma science to a broad audience, defines trauma not by what happened but by what it did: &ldquo;Trauma is not the story of something that happened back then. It&rsquo;s the current imprint of that pain, horror, and fear living inside people.&rdquo; This distinction &mdash; between the event and its ongoing neurological effect &mdash; is essential. Two people can experience the same event and one may be traumatized while the other is not; what determines trauma is not the objective severity of what happened but the degree to which the person&rsquo;s capacity to integrate and survive the experience was exceeded.",
      "Post-Traumatic Stress Disorder (PTSD) is the clinical diagnostic category for the most recognized form of trauma response, characterized by intrusive re-experiencing of the traumatic event (flashbacks, nightmares), hyperarousal (heightened startle response, difficulty sleeping, hypervigilance), and avoidance of stimuli associated with the trauma. But complex trauma &mdash; sometimes called C-PTSD &mdash; describes the effects of prolonged, repeated trauma, often occurring in childhood or within relationships of dependency: chronic abuse, neglect, domestic violence, institutional abuse. Complex trauma disrupts not just specific memories but the development of the self, the capacity for secure attachment, and the fundamental sense of safety in the world. Developmental trauma &mdash; trauma experienced in childhood during critical developmental windows &mdash; can reshape the architecture of the growing brain in ways that affect emotional regulation, relational capacity, and cognitive function for decades.",
      "The neuroscience of trauma reveals why it is not simply a matter of thinking differently about the past. When a person is traumatized, the event is stored not only as a narrative memory (available to the prefrontal cortex, the thinking brain) but as a somatic, sensory, emotional memory encoded in the body and the limbic system. This is why trauma &ldquo;keeps the score&rdquo; in the body: a smell, a sound, a touch, a tone of voice can activate the body&rsquo;s threat-response system as if the original danger were present again, bypassing conscious cognition entirely. The body goes into fight, flight, or freeze &mdash; a state of physiological emergency. Trauma therapy is therefore not simply cognitive therapy; it requires working with the body, with sensation, with the nervous system&rsquo;s stored alarm states, not only with the narrative account of what happened.",
      "The theological question that trauma raises is sharp and urgent: why does trauma disrupt the sense of God&rsquo;s presence? Many trauma survivors report not only the loss of their sense of safety but the loss of their sense of God &mdash; the felt experience of divine presence that had previously anchored their spiritual life goes silent or disappears entirely. This is not apostasy; it is the neurological reality that trauma disrupts the integrative functions through which spiritual experience is processed and felt. The person who has been deeply traumatized may have intact theological beliefs about God while being neurologically unable to access the felt sense of those beliefs. This distinction &mdash; between holding a belief and feeling its reality &mdash; is crucial for pastoral care of the traumatized. It prevents the category error of treating a neurological disruption as a spiritual failure.",
      "The body is the locus of suffering in ways that Christian theology has not always adequately honored. The Greek philosophical tradition that influenced much of Western Christianity tended toward a dualism that valued the soul and marginalized the body &mdash; treating embodied suffering as less spiritually significant than &ldquo;spiritual&rdquo; forms of distress. But Scripture is consistently embodied: the Psalms describe suffering in somatic language (&ldquo;I am poured out like water, and all my bones are out of joint&rdquo; &mdash; Psalm 22:14), the incarnation is God taking on a body, and the resurrection of Jesus is bodily. Trauma is an embodied reality: it lives in the nervous system, in the musculature, in the patterns of physiological response. A theology that takes trauma seriously must take the body seriously &mdash; not as the seat of spiritual weakness but as the site of suffering that God himself, in the incarnation, has entered.",
      "The distinction between trauma and ordinary stress matters pastorally. Not every difficult experience is trauma; the word has been somewhat diluted in popular usage. Trauma, properly understood, involves the overwhelming of the person&rsquo;s capacity to integrate the experience &mdash; an objective excess that the nervous system cannot adequately process. Recognizing what qualifies as trauma is not about gatekeeping suffering but about providing appropriate care. The person who has been traumatized needs something different than the person who is stressed or grieving, though there is overlap. They need approaches that address the body and the nervous system, safety and stabilization before processing, and a pace that respects the limits of what the traumatized system can bear. The church that offers prayer and Scripture alone to the traumatized person &mdash; without also providing or connecting them to trauma-informed care &mdash; has confused spiritual truth with clinical sufficiency.",
    ],
  },
  {
    id: "Trauma in Scripture",
    heading: "Trauma in Scripture: The Bible Does Not Sanitize Suffering",
    paragraphs: [
      "Joseph&rsquo;s story, spanning Genesis 37 to 50, is the Bible&rsquo;s most developed narrative of trauma and redemption. At seventeen, Joseph is sold by his own brothers into slavery &mdash; a catastrophic betrayal by the very people who should have protected him. In Egypt, he is falsely accused of sexual assault by Potiphar&rsquo;s wife and imprisoned for years for a crime he did not commit. The text does not editorialize about Joseph&rsquo;s inner state; it records his experience with compressed economy. What is theologically significant is the repeated phrase &ldquo;but the Lord was with Joseph&rdquo; (Genesis 39:2, 21, 23) &mdash; not that Joseph was spared suffering, but that God was present within it. The suffering is real, the injustice is real, and God&rsquo;s presence is real alongside both. This is not the theology of exemption but the theology of accompaniment.",
      "Hagar is one of the most overlooked figures in the Old Testament and one of the most important for a theology of trauma. An Egyptian slave in Abraham&rsquo;s household, she is used as a surrogate mother for Sarah, who cannot conceive. When Hagar becomes pregnant and tension escalates, Sarah treats her harshly and Hagar flees into the wilderness &mdash; alone, pregnant, vulnerable, with no resources and no safety. There, in the wilderness, the angel of the Lord appears to her. She is given a name for the God who found her: &ldquo;She gave this name to the Lord who spoke to her: &lsquo;You are the God who sees me&rsquo;&rdquo; (Genesis 16:13). The Hebrew is El Roi &mdash; the God who sees. Hagar&rsquo;s theology is forged in abandonment and wilderness: a God who sees those whom others do not see, who finds those who have been discarded, who names and values the person whom the social order has treated as instrumental. This is a crucial theological resource for the traumatized.",
      "The rape of Tamar (2 Samuel 13) is one of the most disturbing passages in the Bible and one of the most pastorally significant. Tamar is the daughter of King David, raped by her half-brother Amnon. The text does not look away. It records her devastation, her tearing of her robe, her silence, her desolation. What the text also records is the failure of the systems around her: her father David, &ldquo;furious&rdquo; when he heard, does nothing. Her full brother Absalom tells her to be quiet. She remains desolate in his house. The Bible preserves her story, gives her name, records her suffering &mdash; and records with equal clarity the failures of the men around her to respond with justice. This text is not a comfortable text; it has no redemptive resolution, no healing, no justice in the narrative. It simply witnesses. And its presence in Scripture is a form of theological solidarity: God knows what happened to Tamar. Her story is not forgotten, even when the world tried to suppress it.",
      "The Psalms&rsquo; somatic language of distress is one of their most striking features and one of their most important gifts to the traumatized. Psalm 22 describes suffering not in abstract spiritual terms but in bodily ones: &ldquo;I am poured out like water, and all my bones are out of joint; my heart has turned to wax; it has melted within me. My mouth is dried up like a potsherd, and my tongue sticks to the roof of my mouth; you lay me in the dust of death&rdquo; (22:14-15). This is somatic distress &mdash; the kind of embodied description that van der Kolk&rsquo;s trauma research would recognize as characteristic of traumatic experience. The psalmist is not describing theological depression; they are describing what trauma does to a body. The Psalms&rsquo; willingness to describe suffering in bodily terms is part of what makes them such a powerful resource for the traumatized: the language of the body under siege is already in Scripture.",
      "Job&rsquo;s experience is the Bible&rsquo;s most extended engagement with what we might call the collapse of the world &mdash; the shattering of the assumptive framework through which a person has understood their life and their God. Job is righteous, and his world falls apart. The framework he had inhabited &mdash; in which righteousness is protected and blessed &mdash; no longer describes his experience. This is one of the psychological effects of severe trauma: the collapse of the assumptive world, the framework through which a person has understood how reality works, who they are, and what they can expect. Job&rsquo;s spiritual journey is the journey from a pre-traumatic faith (in which God&rsquo;s justice and human righteousness produce protection) through the collapse of that framework into a post-traumatic encounter with the living God &mdash; not the God of the system, but the God of the whirlwind who is larger than any system.",
      "The Bible&rsquo;s refusal to look away from trauma is one of its most distinctive and countercultural features. Ancient literature often suppresses the suffering of the powerless; those without social standing rarely appear, and when they do their suffering is typically minimized or instrumentalized. The Old Testament records the suffering of slaves, women, the poor, and the outcast with a specificity and moral seriousness that is remarkable in its historical context. The preservation of Tamar&rsquo;s story, of Hagar&rsquo;s wilderness encounter, of the lament psalms&rsquo; raw despair &mdash; these are not theological accidents. They are the testimony of a God who sees what others do not see, who names what others do not name, and whose Word makes room for the suffering of the most vulnerable rather than erasing it in favor of more comfortable narratives.",
    ],
  },
  {
    id: "Theology of Suffering",
    heading: "Theology of Suffering: God Who Enters Trauma",
    paragraphs: [
      "The question of why God allows trauma is the hardest question in Christian theology, and it does not have an answer that satisfies on the level of explanation. What Christian theology offers in response to trauma is not a theodicy &mdash; a logical account that justifies God&rsquo;s permission of suffering &mdash; but a lament and a solidarity. The theology of lament does not explain suffering; it gives it a voice and a direction. The theology of the incarnation does not justify God&rsquo;s permission of suffering; it demonstrates God&rsquo;s entry into it. These are not the same as an answer. They are something different: the assertion that God does not cause trauma and does not stand outside it, but enters it and weeps within it.",
      "The incarnation is God taking on vulnerability. The Son of God was born into a world of oppression and violence &mdash; the massacre of the infants of Bethlehem is the shadow that falls over the nativity &mdash; and lived under Roman occupation, experienced poverty, social rejection, betrayal by his closest friends, false accusation, torture, and execution. The Word became flesh not in a protected bubble of divine insulation but in the full exposure of human vulnerability. This is not incidental to the Christian gospel; it is its center. The God revealed in Jesus Christ is a God who has not watched suffering from a distance but has entered it, taken it into himself, and carried it. This does not explain why trauma exists. But it means that the traumatized person is not alone in a cosmos of divine indifference.",
      "The crucifixion is the place where all trauma is brought. The cry of dereliction &mdash; &ldquo;My God, my God, why have you forsaken me?&rdquo; (Mark 15:34, quoting Psalm 22) &mdash; is the most theologically significant moment in the New Testament for a theology of trauma. The Son of God, on the cross, experiences the felt abandonment of God. This is not an act; it is a reality. Within the mystery of the Trinity, the eternal relationship of love between Father and Son bears the weight of human sin and godforsakenness &mdash; the Son experiences what the traumatized so often experience: the absence of God in the place of greatest need. The cross is not an explanation for trauma; it is the entry of God into the place of trauma&rsquo;s deepest wound, the sense of divine abandonment.",
      "J&uuml;rgen Moltmann&rsquo;s &ldquo;The Crucified God&rdquo; (1972) is the most important twentieth-century theological resource for a theology of trauma. Moltmann argued that the crucifixion is not merely an event that God permitted from outside but an event that God experienced from within. God suffers. The Father suffers the death of the Son; the Son suffers godforsakenness; the Spirit is the grief that holds the event together. This &ldquo;theology of the cross&rdquo; refuses the God of philosophical theism &mdash; the God of pure power and impassibility who cannot be affected by what happens in creation &mdash; in favor of the God revealed in Jesus: a God who is vulnerable to suffering because God is love, and love is inherently capable of suffering. For the traumatized person, this means: your suffering reaches into God. It is not a peripheral event in a universe of divine indifference. It falls within the life of God.",
      "Trauma and theodicy &mdash; the defense of God&rsquo;s goodness in the face of evil &mdash; intersect in ways that require careful pastoral sensitivity. The traumatized person may have very legitimate anger at God: Why did you let this happen? Where were you? Why didn&rsquo;t you protect me? These are not merely philosophical questions; they are the wounds of a relationship. And the Christian tradition, at its best, does not try to answer them with argument but with lament. The psalms of accusation give permission for the full weight of anger at God to be addressed directly to him &mdash; not as an act of apostasy but as an act of faith that believes God is present enough to be addressed and large enough to receive the anger without being destroyed by it. The theodicy that convinces is not usually an argument; it is the experience, over time, of a God who was present in the trauma, even when unfelt.",
      "The distinction between God causing trauma and God being present within it is one of the most important theological moves in the pastoral care of the traumatized. Christian theology &mdash; properly understood &mdash; does not teach that God orchestrates abuse, violence, or catastrophic loss as pedagogical tools. It teaches that God&rsquo;s will is for shalom &mdash; the flourishing of all people in all dimensions of life &mdash; and that sin, evil, and structural injustice are genuine violations of God&rsquo;s will. Trauma is the wound that evil leaves. God does not cause it. But in a world where trauma occurs, God is present within it: in the people who show up, in the unexpected mercy, in the small survivals that look like miracles, and ultimately in the cross, where God went all the way into the place where evil does its worst work and refused to stay dead.",
    ],
  },
  {
    id: "Healing and Therapy",
    heading: "Healing and Therapy: Evidence-Based Care for Trauma",
    paragraphs: [
      "EMDR &mdash; Eye Movement Desensitization and Reprocessing &mdash; is one of the most well-evidenced treatments for trauma and PTSD, endorsed by the World Health Organization, the American Psychological Association, and major mental health bodies worldwide. Developed by Francine Shapiro in the late 1980s, EMDR works by using bilateral stimulation (typically alternating eye movements following a therapist&rsquo;s moving finger, though tapping or sound can also be used) while the person holds in mind a disturbing memory, belief, and body sensation. The mechanism is not fully understood, but the most widely supported theory is that bilateral stimulation activates the brain&rsquo;s natural information-processing system &mdash; similar to what happens in REM sleep &mdash; allowing traumatic memories that have been &ldquo;frozen&rdquo; in an unprocessed state to be integrated into the broader memory system. When successfully processed, the memory loses its capacity to intrude and dysregulate; it becomes a past event rather than an ongoing present experience.",
      "Somatic experiencing, developed by Peter Levine, addresses trauma through the body&rsquo;s physiological response rather than primarily through narrative or cognitive processing. Levine observed that animals in the wild frequently shake and tremble after a life-threatening encounter &mdash; a neurological discharge of the mobilized fight-or-flight energy &mdash; and rarely develop chronic trauma symptoms. Humans, who inhibit these physical discharge responses for social reasons, often become &ldquo;stuck&rdquo; with the mobilized energy trapped in the nervous system. Somatic experiencing guides the person to track bodily sensations &mdash; the place in the chest where tension lives, the constriction in the throat, the quality of the breath &mdash; and to gradually, carefully, complete the interrupted physiological responses of the original survival situation. It works not with the story of what happened but with the body&rsquo;s current state, which is the ongoing imprint of the trauma.",
      "Trauma-informed CBT (Cognitive Behavioral Therapy) adapts the evidence-based framework of CBT to address the specific distortions and patterns that trauma produces: beliefs such as &ldquo;I am permanently damaged,&rdquo; &ldquo;The world is entirely dangerous,&rdquo; &ldquo;It was my fault,&rdquo; or &ldquo;I cannot trust anyone.&rdquo; Trauma-informed CBT does not rush the person into cognitive restructuring before they have been stabilized; it begins with psychoeducation (helping the person understand what trauma is and what it does to the brain and body), builds coping skills, and only then, when the person is sufficiently resourced, moves toward processing the traumatic material. The effectiveness of CBT-based approaches for PTSD is well-established in the research literature, particularly for single-event trauma.",
      "The relationship between therapy and spiritual direction is a question that many Christian trauma survivors navigate with anxiety: is it faithless to need therapy? Is secular therapy compatible with Christian faith? The answer that pastoral and therapeutic practice has increasingly converged on is: therapy and spiritual direction address different (though overlapping) dimensions of the person, and the traumatized person often needs both. Therapy addresses the neurological, psychological, and behavioral dimensions of trauma response. Spiritual direction attends to the relationship with God, the meaning of suffering within a larger narrative, the practices of prayer and lament, and the integration of the experience into a faithful life. Peter Scazzero, whose work on emotional health and spirituality has influenced thousands of pastors and churches, argues that emotional and spiritual health are inseparable: the person who has not attended to their emotional and psychological wounds cannot flourish spiritually, however doctrinally sophisticated they may be.",
      "The question of whether Christians can use secular therapy deserves a direct answer: yes. The assumption that psychological knowledge is inherently antithetical to Christian faith is not supported by the tradition. Theology has always drawn on the intellectual resources of its cultural moment &mdash; Augustine drew on Platonism, Aquinas on Aristotle, the Reformers on Renaissance humanism. The scientific study of how the human mind and nervous system work is part of what Calvin called &ldquo;general revelation&rdquo; &mdash; the knowledge of God available to all through creation, including the study of the human creature. That van der Kolk&rsquo;s research on the body and trauma is not written from a Christian perspective does not make it false or incompatible with a Christian anthropology. The church that refuses psychology for its traumatized members in the name of theological purity is refusing created knowledge to people who are suffering, and this is not faithfulness.",
      "The church&rsquo;s role in creating safe communities for the traumatized is distinct from and irreplaceable by clinical care. Therapy addresses the wound; community addresses the isolation. Many trauma survivors &mdash; particularly those whose trauma occurred within religious contexts, or whose communities failed to protect them &mdash; experience profound ambivalence or fear around church communities. The church that takes this seriously must earn trust rather than assume it, must create transparency and accountability structures, must preach and teach in ways that do not inadvertently replicate the dynamics of the original trauma (shame-based preaching, coercive authority, the suppression of difficult questions), and must make space in its pastoral care for the long, non-linear work of healing. This is not easy. It requires communities that are willing to be disrupted, to sit with complexity, and to resist the pressure to produce simple spiritual answers to complicated human suffering.",
    ],
  },
  {
    id: "The Path to Wholeness",
    heading: "The Path to Wholeness: Healing That Is Not Going Back",
    paragraphs: [
      "Wholeness is not the same as being &ldquo;back to normal.&rdquo; One of the most important things to say to a trauma survivor who is in the middle of healing is that the goal is not to recover the person they were before the trauma. The trauma has happened. It is part of the history of this person&rsquo;s life. The work of healing is not to undo the past but to integrate it &mdash; to move from a state in which the trauma is an active, intrusive, dysregulating presence in the present, to a state in which the trauma is a past event that the person can remember, that belongs to their story, that they carry with them but that no longer defines the totality of who they are. Integration is not resolution; it does not mean that the person is no longer affected by what happened. It means that they are not controlled by it.",
      "The redemption of Joseph&rsquo;s story provides one of the most powerful biblical images of post-traumatic transformation. When Joseph reveals himself to his brothers who had sold him into slavery decades earlier, he does not minimize what they did or perform a performance of easy forgiveness. He weeps &mdash; the text records his weeping three times. And then he says: &ldquo;You intended to harm me, but God intended it for good to accomplish what is now being done, the saving of many lives&rdquo; (Genesis 50:20). This is not a statement that the harm was not harm, or that his suffering was not suffering. It is a statement about the scope of God&rsquo;s redemptive capacity &mdash; that even the worst of what human beings do to each other can be entered by a purposive divine love that brings life from the wreckage. This is not a formula for trauma survivors to apply to their own experiences. It is a testimony that has its own timetable and cannot be rushed or performed.",
      "Post-traumatic growth is the term researchers use for the positive psychological change that can emerge in the aftermath of highly challenging life crises and trauma. It does not mean that the trauma was good, or that everyone who is traumatized experiences growth, or that growth cancels the damage. It is the observation that some people, after working through trauma with appropriate support, report positive changes in areas such as relating to others, appreciation of life, personal strength, new possibilities, and spiritual change. The Christian narrative of redemption &mdash; that God can bring life from death, meaning from chaos, growth from suffering &mdash; is not invalidated by the observation that this does not always happen, or that it happens on a timeline not of the survivor&rsquo;s choosing. It is validated by the many testimonies of survivors who have found, in the wreckage of their lives, something they would not otherwise have found.",
      "The New Jerusalem, described in Revelation 21-22, is the eschatological horizon for a Christian theology of healing. &ldquo;He will wipe every tear from their eyes. There will be no more death or mourning or crying or pain, for the old order of things has passed away&rdquo; (21:4). The &ldquo;healing of the nations&rdquo; (22:2) by the leaves of the tree of life implies that the New Jerusalem is not only a place where future suffering is absent but where the wounds of the past are healed. This is the ultimate promise to the traumatized: not only that the suffering is over, but that the wound is healed. Not only that the past is past, but that the past is redeemed. This eschatological horizon does not make present healing unnecessary; it orients present healing within a larger frame. We pursue healing now because God&rsquo;s desire is for wholeness now, and because the healing we experience now is a partial anticipation of the wholeness promised for the age to come.",
      "The witness of trauma survivors in the church is one of the most powerful and underutilized testimonies available to Christian communities. The survivor who has walked through the darkness of trauma and come out the other side &mdash; not the same as before, not without scars, but alive and integrated and capable of speaking truthfully about both the darkness and the light &mdash; carries a form of authority that cannot be replicated by those who have not been there. Their testimony is not the easy testimony of &ldquo;God fixed everything&rdquo; but the harder and more truthful testimony of &ldquo;God was with me in the place where everything was broken, and something I did not expect emerged from the ruins.&rdquo; The church that creates space for these testimonies &mdash; that does not require them to be tidied up, that allows the complexity to remain &mdash; is the church that looks most like the Gospel.",
      "Faithful accompaniment of the traumatized person means accepting the long, non-linear, often setback-ridden nature of healing without withdrawing when the road gets longer than expected. The person who was traumatized in childhood may be working on its effects for decades. The person who experienced combat trauma or sexual violence may cycle through periods of relative stability and acute symptom activation for years. The friend, pastor, or community that commits to accompany someone in trauma healing must accept this non-linearity &mdash; must not interpret a setback as failure, must not withdraw when the person is harder to be with, must not offer the implicit message that healing should be progressing faster. What faithful accompaniment looks like in practice is specific and humble: showing up consistently, not requiring the person to perform wellness for the community&rsquo;s comfort, learning what the person&rsquo;s triggers and needs are and responding to them with care, and trusting the God who began a good work to complete it &mdash; on his timetable, not the community&rsquo;s.",
    ],
  },
];

const videoItems = [
  { videoId: "OkiV6dLj3vs", title: "Trauma and the Christian Faith" },
  { videoId: "KTQcaRnnTbI", title: "Bessel van der Kolk on Healing Trauma" },
  { videoId: "ssPEBSWwLIg", title: "Peter Scazzero on Emotional Health and Spirituality" },
];

export default function ChristianTraumaHealingPage() {
  const [tab, setTab] = useState<Tab>(TABS[0]);
  const [loaded, setLoaded] = useState(false);
  useEffect(() => { setLoaded(true); }, []);
  if (!loaded) return null;

  const currentSection = sections.find((s) => s.id === tab);

  return (
    <div style={{ paddingTop: "var(--header-height, 80px)", minHeight: "100vh", background: BG, color: TEXT, fontFamily: "var(--font-jost, system-ui, sans-serif)" }}>
      <main style={{ maxWidth: 860, margin: "0 auto", padding: "2.5rem 1.25rem 5rem" }}>
        {/* Hero */}
        <header style={{ marginBottom: "2.5rem" }}>
          <div style={{ fontSize: "0.78rem", color: ACCENT, letterSpacing: "0.12em", textTransform: "uppercase", fontWeight: 600, marginBottom: "0.6rem" }}>
            Faith &amp; Healing
          </div>
          <h1 style={{ fontSize: "clamp(1.8rem, 4.5vw, 2.6rem)", fontWeight: 800, lineHeight: 1.15, marginBottom: "1rem" }}>
            Christian Guide to Trauma and Healing
          </h1>
          <p style={{ color: MUTED, lineHeight: 1.75, fontSize: "1.02rem", maxWidth: 700 }}>
            Trauma and the Christian faith &mdash; what trauma is, biblical figures who experienced trauma, the theology of suffering and redemption, evidence-based therapy for Christians, and the hope of wholeness that is not going back but going deeper.
          </p>
          <div style={{ marginTop: "1.75rem", background: CARD, border: `1px solid ${BORDER}`, borderLeft: `3px solid ${ACCENT}`, borderRadius: 12, padding: "1.25rem 1.5rem" }}>
            <p style={{ fontStyle: "italic", lineHeight: 1.7, marginBottom: 8 }}>&ldquo;You intended to harm me, but God intended it for good to accomplish what is now being done, the saving of many lives.&rdquo;</p>
            <p style={{ color: ACCENT, fontSize: "0.85rem", fontWeight: 600 }}>Genesis 50:20</p>
          </div>
        </header>

        {/* Tab navigation */}
        <nav aria-label="Page sections" style={{ display: "flex", gap: 8, flexWrap: "wrap", marginBottom: "2.25rem" }}>
          {TABS.map((t) => (
            <button key={t} type="button" onClick={() => setTab(t)} style={{
              padding: "0.5rem 1.1rem", borderRadius: 8,
              border: `1px solid ${tab === t ? ACCENT : BORDER}`,
              background: tab === t ? `rgba(13, 148, 136, 0.12)` : "transparent",
              color: tab === t ? ACCENT : MUTED,
              cursor: "pointer", fontSize: "0.88rem", fontWeight: tab === t ? 600 : 400,
              transition: "all 0.15s ease", whiteSpace: "nowrap" as const,
            }}>
              {t}
            </button>
          ))}
        </nav>

        {/* Text tab content */}
        {currentSection && (
          <section style={{ display: "flex", flexDirection: "column", gap: 20 }}>
            <h2 style={{ fontSize: "1.4rem", fontWeight: 700, marginBottom: 4 }}>{currentSection.heading}</h2>
            {currentSection.paragraphs.map((para, i) => (
              <p key={i} style={{ color: MUTED, lineHeight: 1.78, fontSize: "0.95rem" }} dangerouslySetInnerHTML={{ __html: para }} />
            ))}
          </section>
        )}

        {/* Videos tab */}
        {tab === "Videos" && (
          <section style={{ display: "flex", flexDirection: "column", gap: 20 }}>
            <h2 style={{ fontSize: "1.4rem", fontWeight: 700, marginBottom: 4 }}>Videos</h2>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))", gap: 20 }}>
              {videoItems.map((video) => (
                <div key={video.videoId} style={{ background: CARD, border: `1px solid ${BORDER}`, borderRadius: 12, overflow: "hidden" }}>
                  <VideoEmbed videoId={video.videoId} title={video.title} />
                  <div style={{ padding: "0.9rem 1.1rem" }}>
                    <h3 style={{ fontSize: "0.92rem", fontWeight: 600, lineHeight: 1.45 }}>{video.title}</h3>
                  </div>
                </div>
              ))}
            </div>
          </section>
        )}

        {/* Closing callout */}
        <div style={{ marginTop: "3rem", background: CARD, border: `1px solid ${BORDER}`, borderLeft: `3px solid ${ACCENT}`, borderRadius: 12, padding: "1.5rem" }}>
          <h3 style={{ fontSize: "1rem", fontWeight: 700, marginBottom: 10 }}>You Are Not Beyond Healing</h3>
          <p style={{ color: MUTED, lineHeight: 1.78, fontSize: "0.93rem" }}>The God who saw Hagar in the wilderness, who was with Joseph in the pit, who entered godforsakenness on the cross and refused to stay dead &mdash; this is the God who is present in your trauma. Healing is not going back to who you were. It is being brought through the darkness by the God who has already walked there, and finding on the other side someone you could not have become without the journey.</p>
        </div>
      </main>
    </div>
  );
}
