"use client";
import SectionGuideTemplate, { type SectionGuideData } from "@/components/SectionGuideTemplate";

const TABS: string[] = [
  "Overview",
  "The Great Drought",
  "Prophets of Delusion",
  "We Set Our Hope on You",
  "Application",
];

const sections = [
  {
    id: "Overview",
    heading: "Overview of Jeremiah 14",
    reference: "Jeremiah 14:1&ndash;22",
    paragraphs: [
      "Jeremiah 14 opens with one of the most haunting drought poems in Scripture. The word of the Lord comes to Jeremiah &lsquo;concerning the drought&rsquo; (14:1), and what follows is a landscape of desolation: Judah mourns, her gates languish, nobles send servants for water who return with empty vessels and covered heads, the ground is cracked, and even the doe abandons her newborn fawn because there is no grass (14:2-6). The drought is no accident of weather; it is one of the covenant curses falling due on a people who have forsaken &lsquo;the fountain of living waters&rsquo; (2:13). The physical thirst of the land is a parable of the spiritual thirst of the people &mdash; a thirst that only God himself can quench, as Jesus would later declare: &lsquo;whoever drinks of the water that I will give him will never be thirsty again&rsquo; (John 4:14).",
      "The chapter then becomes a dialogue of extraordinary tension. Twice the people offer a beautiful communal lament &mdash; confessing sin, appealing to God's name, calling him &lsquo;hope of Israel, its savior in time of trouble&rsquo; (14:8) &mdash; and twice God answers with devastating clarity. The words are right, but the feet are wrong: &ldquo;They have loved to wander thus; they have not restrained their feet&rdquo; (14:10). For the third time in the book, God forbids Jeremiah to intercede: &lsquo;Do not pray for the welfare of this people&rsquo; (14:11). Fasting, offerings, and eloquent liturgy will not be accepted from a people whose repentance is words without turning.",
      "Into this crisis Jeremiah raises the problem of the false prophets: the people are being told by religious professionals that no sword or famine will come, only &lsquo;assured peace in this place&rsquo; (14:13). God's verdict is one of the most searching statements on false religion ever spoken: &ldquo;The prophets are prophesying lies in my name. I did not send them&hellip; They are prophesying to you a lying vision, worthless divination, and the deceit of their own minds&rdquo; (14:14). Both the prophets who sold the delusion and the people who loved to buy it will fall to the very sword and famine they denied (14:15-16). Jesus warned of the same peril: &lsquo;Beware of false prophets, who come to you in sheep's clothing but inwardly are ravenous wolves&rsquo; (Matthew 7:15).",
      "Yet the chapter does not end in cynicism but in one of the Old Testament's clearest confessions of where hope must finally rest. The closing lament asks the unbearable questions &mdash; &lsquo;Have you utterly rejected Judah?&rsquo; (14:19) &mdash; acknowledges wickedness, pleads God's name, throne, and covenant (14:20-21), and then reasons its way to bedrock: &ldquo;Are there any among the false gods of the nations that can bring rain?&hellip; Are you not he, O Lord our God? We set our hope on you, for you do all these things&rdquo; (14:22). The idols cannot water a field, much less save a soul. The chapter thus drives us toward the Prophet God truly did send (Deuteronomy 18:18; John 7:16), who stood up on the last day of the feast and cried, &lsquo;If anyone thirsts, let him come to me and drink&rsquo; (John 7:37).",
    ],
  },
  {
    id: "The Great Drought",
    heading: "Judah Mourns and Her Gates Languish",
    reference: "Jeremiah 14:1&ndash;9",
    paragraphs: [
      "The drought poem moves from the city to the field to the wilderness, and at every level the land is dying. &ldquo;Judah mourns, and her gates languish; her people lament on the ground, and the cry of Jerusalem goes up&rdquo; (14:2). The city gates &mdash; the bustling centers of commerce, justice, and community life &mdash; sag in silence. The nobles, accustomed to command, &ldquo;send their servants for water; they come to the cisterns; they find no water; they return with their vessels empty; they are ashamed and confounded and cover their heads&rdquo; (14:3). Rank cannot purchase rain. The empty cistern is a bitter echo of God's earlier indictment: the people had forsaken the fountain of living waters and hewn out for themselves &lsquo;broken cisterns that can hold no water&rsquo; (2:13). Now even the literal cisterns stand dry, and shame covers every head.",
      "The devastation reaches the farmers and then the animals: &ldquo;Because of the ground that is dismayed, since there is no rain on the land, the farmers are ashamed; they cover their heads&rdquo; (14:4). Then two images of piercing tenderness: &ldquo;Even the doe in the field forsakes her newborn fawn because there is no grass. The wild donkeys stand on the bare heights; they pant for air like jackals; their eyes fail because there is no vegetation&rdquo; (14:5-6). When a mother abandons her newborn, creation itself has been bent out of shape by human sin. The land suffers for the people's rebellion &mdash; a truth Paul universalizes when he writes that &lsquo;the whole creation has been groaning together&rsquo; under the futility to which sin subjected it, awaiting redemption (Romans 8:20-22).",
      "Then the people speak, and their liturgy is genuinely beautiful: &ldquo;Though our iniquities testify against us, act, O Lord, for your name's sake; for our backslidings are many; we have sinned against you&rdquo; (14:7). They confess sin. They appeal not to their own merit but to God's name and reputation. They reach for his most tender titles: &ldquo;O you hope of Israel, its savior in time of trouble, why should you be like a stranger in the land, like a traveler who turns aside to tarry for a night?&rdquo; (14:8). Why, they ask, does the covenant God act like a passing tourist in his own country, &lsquo;like a mighty warrior who cannot save&rsquo; (14:9)?",
      "The prayer closes with words that ought to move heaven itself: &ldquo;Yet you, O Lord, are in the midst of us, and we are called by your name; do not leave us&rdquo; (14:9). Every phrase is theologically correct. God is their hope; he is savior in time of trouble; they do bear his name. If prayers were graded on doctrine and eloquence, this one would stand with the psalms. And that is precisely the trap the next verse will spring: beautiful words can coexist with unbent lives. Jesus named this exact condition when he quoted Isaiah against his own generation: &lsquo;This people honors me with their lips, but their heart is far from me&rsquo; (Matthew 15:8). The drought poem teaches us to look past the eloquence of a prayer to the direction of the feet that pray it.",
    ],
  },
  {
    id: "Prophets of Delusion",
    heading: "Lying Visions and the Deceit of Their Own Minds",
    reference: "Jeremiah 14:10&ndash;18",
    paragraphs: [
      "God's answer to the beautiful liturgy is a single sentence that cuts to the bone: &ldquo;They have loved to wander thus; they have not restrained their feet; therefore the Lord does not accept them; now he will remember their iniquity and punish their sins&rdquo; (14:10). The problem is not the vocabulary of the confession but the love underneath it &mdash; they &lsquo;have loved to wander.&rsquo; Their words say &lsquo;do not leave us&rsquo; while their feet keep leaving him. So for the third time God tells Jeremiah, &ldquo;Do not pray for the welfare of this people&rdquo; (14:11; compare 7:16; 11:14), and adds that the machinery of religion has lost its power: &ldquo;Though they fast, I will not hear their cry, and though they offer burnt offering and grain offering, I will not accept them&rdquo; (14:12). Repentance that consists of words without turning cannot avert judgment; it is what Paul calls a &lsquo;worldly grief&rsquo; that produces death, not the &lsquo;godly grief&rsquo; that produces genuine repentance leading to salvation (2 Corinthians 7:10).",
      "Jeremiah, ever the intercessor even when forbidden to intercede, pleads a mitigating circumstance: the people have been misled by their preachers. &ldquo;Ah, Lord God, behold, the prophets say to them, &lsquo;You shall not see the sword, nor shall you have famine, but I will give you assured peace in this place&rsquo;&rdquo; (14:13). If anyone deserves blame, is it not the men who kept promising peace? God's reply is a fourfold demolition of their credentials: &ldquo;The prophets are prophesying lies in my name. I did not send them, nor did I command them or speak to them. They are prophesying to you a lying vision, worthless divination, and the deceit of their own minds&rdquo; (14:14). Everything about their ministry is counterfeit &mdash; the commission, the message, the vision, the source. They speak in God's name, but the words rise from their own imaginations.",
      "The judgment is precise and terrible: the prophets who said &lsquo;sword and famine shall not come upon this land&rsquo; will themselves &lsquo;be consumed by sword and famine&rsquo; (14:15), and the people to whom they prophesy will be cast out in the streets, victims of the very disasters they were assured could never happen (14:16). God adds a piercing note: &lsquo;them, their wives, their sons, and their daughters. For I will pour out their evil upon them&rsquo; (14:16). The people are not innocent victims of clerical fraud; they loved the message. As Jeremiah says elsewhere, &lsquo;the prophets prophesy falsely&hellip; my people love to have it so&rsquo; (5:31). Paul foresaw the same market for delusion in the church age: people &lsquo;will not endure sound teaching, but having itching ears they will accumulate for themselves teachers to suit their own passions&rsquo; (2 Timothy 4:3).",
      "Then, astonishingly, the God who forbade prayer commands tears: &ldquo;Let my eyes run down with tears night and day, and let them not cease, for the virgin daughter of my people is shattered with a great wound, with a very grievous blow&rdquo; (14:17). Jeremiah is to walk the land and see prophet and priest plying their trade without knowledge while the slain of the sword lie in the field and the diseases of famine fill the city (14:18). Judgment is settled, but grief is not forbidden &mdash; it is commanded, and it is God's own grief flowing through his prophet's eyes. Here the weeping prophet again prefigures his Lord, who looked out over the same city centuries later and wept: &lsquo;Would that you, even you, had known on this day the things that make for peace! But now they are hidden from your eyes&rsquo; (Luke 19:41-42). The true prophet never announces judgment with dry eyes.",
    ],
  },
  {
    id: "We Set Our Hope on You",
    heading: "Only God Gives the Rain",
    reference: "Jeremiah 14:19&ndash;22",
    paragraphs: [
      "The chapter closes with a second communal lament, rawer and more desperate than the first: &ldquo;Have you utterly rejected Judah? Does your soul loathe Zion? Why have you struck us down so that there is no healing for us? We looked for peace, but no good came; for a time of healing, but behold, terror&rdquo; (14:19). The questions are almost unbearable &mdash; can the covenant God actually loathe the city he chose? The complaint that they &lsquo;looked for peace&rsquo; but found terror is the bitter fruit of the false prophets' message: they had been promised peace by men God never sent, and the promised peace never came. Delusion always presents its bill eventually, and the payment is terror.",
      "Yet this lament goes deeper than the first. &ldquo;We acknowledge our wickedness, O Lord, and the iniquity of our fathers, for we have sinned against you&rdquo; (14:20). No excuses, no appeal to circumstances &mdash; wickedness owned in the first person, stretching back through generations. Then three appeals, each anchored in God rather than in Judah: &ldquo;Do not spurn us, for your name's sake; do not dishonor your glorious throne; remember and do not break your covenant with us&rdquo; (14:21). Your name, your throne, your covenant. This is the grammar of all true prayer: not &lsquo;we deserve better&rsquo; but &lsquo;your glory is at stake in our salvation.&rsquo; It is the logic Moses used at Sinai (Exodus 32:11-13) and the logic behind every prayer offered &lsquo;in Jesus' name&rsquo; &mdash; appeal grounded in who God is, not in what we are.",
      "The lament's final verse is the theological summit of the chapter: &ldquo;Are there any among the false gods of the nations that can bring rain? Or can the heavens give showers? Are you not he, O Lord our God? We set our hope on you, for you do all these things&rdquo; (14:22). The drought has burned away every rival. Baal, the Canaanite storm-god whose entire portfolio was rain, stands exposed as a fiction; the sky itself is not a power but a servant. Only the Lord gives rain &mdash; a truth Paul preached to pagans at Lystra, that the living God &lsquo;did good by giving you rains from heaven and fruitful seasons&rsquo; (Acts 14:17). When every false hope has failed, the confession that remains is the only one that was ever true: &lsquo;We set our hope on you.&rsquo;",
      "Whether that confession was yet joined to turned feet, the next chapter will grimly answer &mdash; but the confession itself points beyond the drought to the gospel. Israel's deepest problem was never rainfall; it was a thirst no cistern could hold water for. God promised to raise up a prophet unlike the deluded peace-preachers, one into whose mouth he would put his own words (Deuteronomy 18:18). Jesus claimed exactly that credential in exactly the terms of Jeremiah 14: &lsquo;My teaching is not mine, but his who sent me&hellip; the one who seeks the glory of him who sent him is true, and in him there is no falsehood&rsquo; (John 7:16-18). The false prophets ran unsent and spoke their own minds; the true Prophet was sent and spoke the Father's words. And he stood up in the temple and answered the drought of every human heart: &ldquo;If anyone thirsts, let him come to me and drink. Whoever believes in me&hellip; &lsquo;Out of his heart will flow rivers of living water&rsquo;&rdquo; (John 7:37-38). The God who alone gives rain has given his Son, and whoever drinks of that water &lsquo;will never be thirsty again&rsquo; (John 4:14).",
    ],
  },
  {
    id: "Application",
    heading: "Living Jeremiah 14",
    reference: "Reflections on Drought, Delusion, and True Hope",
    paragraphs: [
      "<strong>Let your repentance turn your feet, not just your words.</strong> Judah's liturgy was doctrinally flawless &mdash; &lsquo;we have sinned against you&hellip; do not leave us&rsquo; (14:7-9) &mdash; and God rejected it because &lsquo;they have not restrained their feet&rsquo; (14:10). Examine your own confession: does it change your direction, or does it merely decorate your wandering? Godly grief &lsquo;produces a repentance that leads to salvation without regret&rsquo; (2 Corinthians 7:10). Bring God more than beautiful words; bring him a turned life.",
      "<strong>Test every message of peace against the whole counsel of God.</strong> The prophets of Jeremiah's day promised &lsquo;assured peace&rsquo; to people under judgment, and the people loved the message (14:13). Comfortable lies still outsell hard truths, and &lsquo;itching ears&rsquo; still accumulate teachers to suit their passions (2 Timothy 4:3). Ask of every voice you follow: was this message sent by God &mdash; does it square with his written word &mdash; or is it the deceit of a mind telling me what I want to hear? &lsquo;Beware of false prophets&rsquo; (Matthew 7:15).",
      "<strong>Weep for those under judgment even when you cannot excuse them.</strong> God commanded his prophet's eyes to &lsquo;run down with tears night and day&rsquo; for the shattered daughter of his people (14:17), and Jesus wept over the very city whose judgment he pronounced (Luke 19:41). Truth-telling without tears hardens into self-righteousness. If you can speak of a neighbor's ruin, a nation's drift, or a prodigal's rebellion without grief, you have God's verdict without God's heart. Pray for both.",
      "<strong>Set your hope on the God who alone gives rain &mdash; and the Son who gives living water.</strong> The drought exposed every idol: no false god of the nations could bring a single shower (14:22). Whatever you have been trusting to water your life &mdash; income, ability, approval, institutions &mdash; will crack like dry ground in the day of testing. Only the Lord does &lsquo;all these things,&rsquo; and only Christ satisfies the deeper thirst: &lsquo;If anyone thirsts, let him come to me and drink&rsquo; (John 7:37). <strong>Prayer prompt:</strong> &ldquo;Lord God, hope of Israel and Savior in time of trouble, deliver me from confession that never turns my feet. Search my heart for the wanderings I have loved, and grant me the godly grief that leads to real repentance. Guard me from every voice that promises peace you have not spoken, and give me tears for those who are perishing. You alone give rain; you alone do all these things. I set my hope on you, and I come thirsty to Christ, the Prophet you truly sent, to drink the living water that means I will never thirst again. Amen.&rdquo;",
    ],
  },
];

const data: SectionGuideData = {
  accent: "#D97706",
  badge: "Jeremiah 14",
  title: "Jeremiah 14: The Drought and the Prophets of Delusion",
  intro: "A great drought grips the land -- gates languish, cisterns stand empty, the doe forsakes her newborn fawn -- and Judah responds with a beautiful liturgy: 'O you hope of Israel... we are called by your name; do not leave us.' But God sees through the words to the unturned feet: 'They have loved to wander.' He again forbids Jeremiah to pray, exposes the prophets promising peace as men he never sent -- 'a lying vision, worthless divination, the deceit of their own minds' -- and yet commands his prophet to weep night and day. The chapter closes at bedrock: no false god can bring rain. 'Are you not he, O Lord our God? We set our hope on you.'",
  tabs: TABS,
  sections,
  calloutTitle: "Words Without Turning Cannot Avert Judgment",
  calloutBody: "Twice in this chapter Judah prays gorgeous prayers of confession, and twice God refuses them -- not because the words were wrong but because 'they have not restrained their feet' (14:10). Liturgy without repentance is delusion in devotional dress, cousin to the prophets' promises of peace God never spoke. Yet the lament's final cry is exactly right: only God gives rain (14:22). The thirst behind the drought is answered not by eloquence but by the Prophet God truly did send, who cries to every dry soul, 'If anyone thirsts, let him come to me and drink' (John 7:37).",
};

export default function Page() {
  return <SectionGuideTemplate data={data} />;
}
