import { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const base = "https://vine.community";
  const now = new Date();

  const routes = [
    { path: "/", priority: 1.0, changeFreq: "daily" as const },
    { path: "/discussions", priority: 0.9, changeFreq: "hourly" as const },
    { path: "/bible", priority: 0.9, changeFreq: "weekly" as const },
    { path: "/daily", priority: 0.9, changeFreq: "daily" as const },
    { path: "/prayer", priority: 0.9, changeFreq: "hourly" as const },
    { path: "/topics", priority: 0.9, changeFreq: "hourly" as const },
    { path: "/resources", priority: 0.8, changeFreq: "daily" as const },
    { path: "/explore", priority: 0.8, changeFreq: "hourly" as const },
    { path: "/community", priority: 0.8, changeFreq: "daily" as const },
    { path: "/blog", priority: 0.8, changeFreq: "daily" as const },
    { path: "/worship", priority: 0.7, changeFreq: "weekly" as const },
    { path: "/mental-health", priority: 0.7, changeFreq: "weekly" as const },
    { path: "/life-hacks", priority: 0.7, changeFreq: "weekly" as const },
    { path: "/relationships", priority: 0.7, changeFreq: "weekly" as const },
    { path: "/finances", priority: 0.7, changeFreq: "weekly" as const },
    { path: "/parenting", priority: 0.7, changeFreq: "weekly" as const },
    { path: "/work-leadership", priority: 0.7, changeFreq: "weekly" as const },
    { path: "/events", priority: 0.7, changeFreq: "daily" as const },
    { path: "/creators", priority: 0.7, changeFreq: "weekly" as const },
    { path: "/reading-plan", priority: 0.7, changeFreq: "weekly" as const },
    { path: "/ai-companion", priority: 0.8, changeFreq: "monthly" as const },
    { path: "/quiz", priority: 0.6, changeFreq: "monthly" as const },
    { path: "/about", priority: 0.5, changeFreq: "monthly" as const },
    { path: "/feed", priority: 0.9, changeFreq: "hourly" as const },
    { path: "/video", priority: 0.8, changeFreq: "daily" as const },
    { path: "/global-connect", priority: 0.8, changeFreq: "daily" as const },
    { path: "/newsletter", priority: 0.6, changeFreq: "weekly" as const },
    { path: "/contact", priority: 0.5, changeFreq: "monthly" as const },
    { path: "/stories", priority: 0.8, changeFreq: "daily" as const },
    { path: "/missions", priority: 0.8, changeFreq: "weekly" as const },
    { path: "/apologetics", priority: 0.8, changeFreq: "weekly" as const },
    { path: "/groups", priority: 0.8, changeFreq: "daily" as const },
    { path: "/groups/theology-doctrine", priority: 0.7, changeFreq: "daily" as const },
    { path: "/groups/mental-health-faith", priority: 0.7, changeFreq: "daily" as const },
    { path: "/groups/young-adults", priority: 0.7, changeFreq: "daily" as const },
    { path: "/groups/christian-parenting", priority: 0.7, changeFreq: "daily" as const },
    { path: "/groups/faith-career", priority: 0.7, changeFreq: "daily" as const },
    { path: "/groups/doubts-questions", priority: 0.7, changeFreq: "daily" as const },
    { path: "/groups/fathers-of-faith", priority: 0.7, changeFreq: "daily" as const },
    { path: "/groups/global-prayer-warriors", priority: 0.7, changeFreq: "daily" as const },
    { path: "/groups/biblical-marriage", priority: 0.7, changeFreq: "daily" as const },
    { path: "/groups/women-in-the-word", priority: 0.7, changeFreq: "daily" as const },
    { path: "/groups/college-faith-network", priority: 0.7, changeFreq: "daily" as const },
    { path: "/groups/creative-christians", priority: 0.7, changeFreq: "daily" as const },
    { path: "/groups/grief-hope", priority: 0.7, changeFreq: "daily" as const },
    { path: "/groups/frontier-missions-network", priority: 0.7, changeFreq: "daily" as const },
    { path: "/privacy", priority: 0.4, changeFreq: "yearly" as const },
    { path: "/terms", priority: 0.4, changeFreq: "yearly" as const },
    { path: "/community-guidelines", priority: 0.5, changeFreq: "monthly" as const },
    { path: "/notifications", priority: 0.3, changeFreq: "hourly" as const },
    { path: "/search", priority: 0.7, changeFreq: "daily" as const },
    { path: "/leaderboard", priority: 0.6, changeFreq: "daily" as const },
    { path: "/blog/why-the-resurrection-changes-everything", priority: 0.7, changeFreq: "monthly" as const },
    { path: "/blog/ai-chatgpt-church", priority: 0.7, changeFreq: "monthly" as const },
    { path: "/blog/problem-of-evil", priority: 0.7, changeFreq: "monthly" as const },
    { path: "/blog/digital-sabbath", priority: 0.7, changeFreq: "monthly" as const },
    { path: "/blog/prayer-that-works", priority: 0.7, changeFreq: "monthly" as const },
    { path: "/stories/carlos-mendez-drug-cartel-to-church-planter", priority: 0.7, changeFreq: "monthly" as const },
    { path: "/stories/lydia-bohm-deconstruction", priority: 0.7, changeFreq: "monthly" as const },
    { path: "/stories/amara-osei-widowed-at-28", priority: 0.7, changeFreq: "monthly" as const },
    { path: "/stories/ji-woo-park-kpop-idol-to-pastor", priority: 0.7, changeFreq: "monthly" as const },
    { path: "/stories/samuel-mwangi-from-prosperity-gospel-to-grace", priority: 0.7, changeFreq: "monthly" as const },
    { path: "/giving", priority: 0.8, changeFreq: "weekly" as const },
    { path: "/blog/marriage-covenant-not-contract", priority: 0.7, changeFreq: "monthly" as const },
    { path: "/blog/fasting-spiritual-discipline", priority: 0.7, changeFreq: "monthly" as const },
    { path: "/blog/deconstruction-reconstruction", priority: 0.7, changeFreq: "monthly" as const },
    { path: "/blog/biblical-finances-stewardship", priority: 0.7, changeFreq: "monthly" as const },
    { path: "/blog/servant-leadership-jesus", priority: 0.7, changeFreq: "monthly" as const },
    { path: "/blog/psalms-permission-to-lament", priority: 0.7, changeFreq: "monthly" as const },
    { path: "/discussions/faith-and-doubt-001", priority: 0.7, changeFreq: "daily" as const },
    { path: "/discussions/resurrection-evidence-002", priority: 0.7, changeFreq: "daily" as const },
    { path: "/discussions/free-will-omniscience-003", priority: 0.7, changeFreq: "daily" as const },
    { path: "/discussions/depression-therapy-faith-005", priority: 0.7, changeFreq: "daily" as const },
    { path: "/discussions/cancer-free-praise-005", priority: 0.7, changeFreq: "daily" as const },
    { path: "/discussions/christian-dating-apps-007", priority: 0.7, changeFreq: "daily" as const },
    { path: "/discussions/deconstruction-faith-008", priority: 0.7, changeFreq: "daily" as const },
    { path: "/discussions/prayer-doesnt-feel-real-009", priority: 0.7, changeFreq: "daily" as const },
    { path: "/discussions/tithing-biblical-or-cultural-010", priority: 0.7, changeFreq: "daily" as const },
    { path: "/topics/prayer-fasting", priority: 0.8, changeFreq: "daily" as const },
    { path: "/topics/genz-church", priority: 0.8, changeFreq: "daily" as const },
    { path: "/topics/marriage-faith", priority: 0.8, changeFreq: "daily" as const },
    { path: "/topics/mental-health-god", priority: 0.8, changeFreq: "daily" as const },
    { path: "/topics/christian-ai-ethics", priority: 0.8, changeFreq: "daily" as const },
    { path: "/topics/deconstruction", priority: 0.8, changeFreq: "daily" as const },
    { path: "/events/global-prayer-summit-2026", priority: 0.8, changeFreq: "weekly" as const },
    { path: "/events/apologetics-symposium-faith-reason", priority: 0.7, changeFreq: "weekly" as const },
    { path: "/events/worship-night-heavens-frequency", priority: 0.7, changeFreq: "weekly" as const },
    { path: "/events/online-prayer-summit-24hr", priority: 0.8, changeFreq: "weekly" as const },
    { path: "/creators/ama-christabel", priority: 0.7, changeFreq: "weekly" as const },
    { path: "/creators/marcus-osei", priority: 0.7, changeFreq: "weekly" as const },
    { path: "/creators/tunde-coker", priority: 0.7, changeFreq: "weekly" as const },
    { path: "/creators/eva-van-der-berg", priority: 0.7, changeFreq: "weekly" as const },
    { path: "/creators/ruth-adeyemi", priority: 0.7, changeFreq: "weekly" as const },
  ];

  return routes.map(({ path, priority, changeFreq }) => ({
    url: `${base}${path}`,
    lastModified: now,
    changeFrequency: changeFreq,
    priority,
  }));
}
