"use client";

import { useState, useMemo } from "react";
import Link from "next/link";
import { Search, Hash } from "lucide-react";
import { usePersistedState } from "@/hooks/usePersistedState";

type Topic = {
  label: string;
  slug?: string;
};

const TOPIC_SLUGS: Record<string, string> = {
  Prayer: "prayer-theology-guide",
  Fasting: "fasting",
  Marriage: "christian-marriage",
  Deconstruction: "doubt-faith-guide",
  Depression: "mental-health",
  "Mental Health": "mental-health",
  Resurrection: "resurrection-theology",
  "Gen Z": "youth",
  Discernment: "discernment-gods-will",
  Enneagram: "enneagram-christianity",
  "Generational Trauma": "generational-trauma-faith",
  Introverts: "introverts-faith-church",
  Examen: "ignatian-examen",
  "Digital Detox": "digital-detox-faith",
  "Prosperity Gospel": "prosperity-gospel",
  Complementarianism: "complementarianism-egalitarianism",
  Egalitarianism: "complementarianism-egalitarianism",
  Cessationism: "cessationism-continuationism",
  Continuationism: "cessationism-continuationism",
  Calvinism: "calvinism-arminianism",
  Arminianism: "calvinism-arminianism",
  "Christian Nationalism": "christian-nationalism",
  "Open Theism": "open-theism",
  "Just War": "just-war-pacifism",
  Pacifism: "just-war-pacifism",
  Mindfulness: "christian-mindfulness",
  Meditation: "christian-mindfulness",
  Yoga: "christian-mindfulness",
  Revelation: "revelation-guide",
  Hell: "hell-eternal-judgment",
  Judgment: "hell-eternal-judgment",
  Universalism: "hell-eternal-judgment",
  Theosis: "theosis-union-with-christ",
  "Union with Christ": "theosis-union-with-christ",
  "Covenant Theology": "covenant-theology-guide",
  Dispensationalism: "covenant-dispensationalism",
  Sexuality: "christian-sexuality-theology",
  "Sexual Ethics": "christian-sexuality-theology",
  Christology: "christology",
  Incarnation: "christology",
  "Five Solas": "five-solas",
  Reformation: "five-solas",
  Sin: "hamartiology-guide",
  Hamartiology: "hamartiology-guide",
  Pneumatology: "pneumatology-guide",
  "Holy Spirit Theology": "pneumatology-guide",
  "Assurance": "assurance-salvation",
  "Eternal Security": "assurance-salvation",
  "Religious Liberty": "religious-liberty",
  "Church and State": "religious-liberty",
  "Sacraments": "sacraments-ordinances",
  "Lord's Supper": "sacraments-ordinances",
  "Ordinances": "sacraments-ordinances",
  "Law and Gospel": "law-gospel",
  Antinomianism: "law-gospel",
  Legalism: "law-gospel",
  Burnout: "burnout",
  Anxiety: "anxiety",
  Loneliness: "loneliness",
  Grief: "grief",
  Forgiveness: "theology-of-forgiveness",
  Suffering: "suffering-guide",
  Sabbath: "christian-joy-guide",
  Lament: "lament-guide",
  Addiction: "addiction-recovery",
  Trinity: "trinity-guide",
  Sanctification: "sanctification-guide",
  Apologetics: "apologetics-101",
  Missions: "missions",
  Evangelism: "evangelism-guide",
  Beauty: "theology-of-beauty",
  "Arts": "theology-of-beauty",
  "Aesthetics": "theology-of-beauty",
  Vocation: "calling-vocation",
  "Calling": "calling-vocation",
  Work: "calling-vocation",
  Hermeneutics: "hermeneutics-guide",
  "Bible Interpretation": "hermeneutics-guide",
  Exegesis: "hermeneutics-guide",
  Justification: "justification-by-faith",
  "Sola Fide": "justification-by-faith",
  Imputation: "justification-by-faith",
  Creation: "creation-theology",
  "Creatio Ex Nihilo": "creation-theology",
  "Cultural Mandate": "creation-theology",
  Ethics: "christian-ethics-guide",
  "Natural Law": "christian-ethics-guide",
  "Virtue Ethics": "christian-ethics-guide",
  "Moral Theology": "christian-ethics-guide",
  "Marriage Theology": "marriage-theology",
  "Divorce": "marriage-theology",
  "Covenant Marriage": "christian-marriage-guide",
  "Easter": "resurrection-theology",
  "Church History": "church-history-survey",
  "Reformation History": "church-history-survey",
  "Church Fathers": "church-history-survey",
  Eschatology: "eschatology-guide",
  "End Times": "eschatology-guide",
  Millennium: "eschatology-guide",
  Rapture: "eschatology-guide",
  Atonement: "atonement-guide",
  "Penal Substitution": "atonement-guide",
  "Christus Victor": "atonement-guide",
  Bible: "bibliology-guide",
  Inerrancy: "bibliology-guide",
  "Scripture Authority": "bibliology-guide",
  "Theology of Mental Health": "mental-health-theology",
  "Faith and Psychology": "mental-health-theology",
  "Biblical Counseling": "christian-counseling-guide",
  "Mission Theology": "mission-theology",
  Missiology: "mission-theology",
  "Missio Dei": "mission-theology",
  "Kingdom of God": "kingdom-of-god-guide",
  "Kingdom Theology": "kingdom-of-god-guide",
  "Already Not Yet": "kingdom-of-god-guide",
  Shalom: "kingdom-of-god-guide",
  Salvation: "soteriology-guide",
  "Ordo Salutis": "soteriology-guide",
  "Perseverance of Saints": "soteriology-guide",
  "Person of Christ": "christology-guide",
  "Hypostatic Union": "christology-guide",
  "Two Natures": "christology-guide",
  "Holy Spirit": "pneumatology-guide",
  "Fruit of the Spirit": "pneumatology-guide",
  "Spiritual Gifts Theology": "pneumatology-guide",
  Filioque: "trinity-guide",
  Perichoresis: "trinity-guide",
  "Problem of Evil": "theodicy-guide",
  Theodicy: "theodicy-guide",
  "Suffering Theology": "theodicy-guide",
  Church: "ecclesiology-guide",
  Ecclesiology: "ecclesiology-guide",
  "Church Government": "ecclesiology-guide",
  "Original Sin": "hamartiology-guide",
  "Total Depravity": "hamartiology-guide",
  "New Covenant": "covenant-theology-guide",
  "Covenant of Grace": "covenant-theology-guide",
  "Image of God": "image-of-god-guide",
  "Imago Dei": "image-of-god-guide",
  "Human Dignity": "image-of-god-guide",
  "Biblical Lament": "lament-guide",
  "Lament Psalms": "lament-guide",
  "Crying Out to God": "lament-guide",
  "Spiritual Formation": "spiritual-formation-guide",
  "Spiritual Disciplines": "spiritual-formation-guide",
  "Lectio Divina": "spiritual-formation-guide",
  "Rule of Life": "spiritual-formation-guide",
  "Contemplative Prayer": "prayer-theology-guide",
  "Theology of Prayer": "theology-of-prayer-guide",
  Intercession: "prayer-theology-guide",
  "Lord's Prayer": "theology-of-prayer-guide",
  "Unanswered Prayer": "prayer-theology-guide",
  "Attributes of God": "theology-proper-guide",
  "Theology Proper": "theology-proper-guide",
  "Names of God": "theology-proper-guide",
  "Divine Simplicity": "theology-proper-guide",
  "God's Holiness": "theology-proper-guide",
  Omnipotence: "theology-proper-guide",
  Omniscience: "theology-proper-guide",
  Inspiration: "bibliology-guide",
  "Sola Scriptura": "bibliology-guide",
  Canon: "bibliology-guide",
  "Biblical Inerrancy": "bibliology-guide",
  "Free Will": "christian-anthropology-guide",
  Compatibilism: "christian-anthropology-guide",
  Conscience: "christian-anthropology-guide",
  "Christian Anthropology": "christian-anthropology-guide",
  "Theological Anthropology": "christian-anthropology-guide",
  "Intermediate State": "heaven-guide",
  Angels: "angelology-guide",
  Angelology: "angelology-guide",
  Demons: "angelology-guide",
  Satan: "angelology-guide",
  "Spiritual Warfare": "angelology-guide",
  "Armor of God": "angelology-guide",
  Mortification: "sanctification-guide",
  Vivification: "sanctification-guide",
  Holiness: "sanctification-guide",
  "Means of Grace": "sanctification-guide",
  Preaching: "preaching-guide",
  Homiletics: "preaching-guide",
  "Expository Preaching": "preaching-guide",
  "Sermon Preparation": "preaching-guide",
  Worship: "worship-theology-guide",
  "Worship Theology": "worship-theology-guide",
  Liturgy: "worship-theology-guide",
  "Regulative Principle": "worship-theology-guide",
  "Worship Music": "worship-theology-guide",
  Discipleship: "discipleship-guide",
  "Making Disciples": "discipleship-guide",
  "Cost of Discipleship": "discipleship-guide",
  "Small Groups": "discipleship-guide",
  "Great Commission": "discipleship-guide",
  "Gospel Presentation": "evangelism-guide",
  Witness: "evangelism-guide",
  Heaven: "heaven-guide",
  "New Creation": "heaven-guide",
  "New Jerusalem": "heaven-guide",
  "Resurrection Body": "heaven-guide",
  "Eternal Life": "heaven-guide",
  "Theology of Suffering": "christian-suffering-guide",
  "Suffering Ministry": "suffering-guide",
  "Spiritual Gifts": "spiritual-gifts-guide",
  "Sign Gifts": "spiritual-gifts-guide",
  Tongues: "spiritual-gifts-guide",
  Healing: "spiritual-gifts-guide",
  "Service Gifts": "spiritual-gifts-guide",
  "Beatitudes": "sermon-on-the-mount-guide",
  "Sermon on the Mount": "sermon-on-the-mount-guide",
  "Kingdom Ethics": "sermon-on-the-mount-guide",
  "Golden Rule": "sermon-on-the-mount-guide",
  "Pastoral Care": "pastoral-care-guide",
  Shepherding: "pastoral-care-guide",
  "Church Discipline": "pastoral-care-guide",
  "Cure of Souls": "pastoral-care-guide",
  "Christian Counseling": "christian-counseling-guide",
  "Soul Care": "christian-counseling-guide",
  "Integration": "christian-counseling-guide",
  Romans: "romans-guide",
  "Book of Romans": "romans-guide",
  "No Condemnation": "romans-guide",
  Evolution: "science-faith-guide",
  "Young Earth": "science-faith-guide",
  "BioLogos": "science-faith-guide",
  "Historical Adam": "science-faith-guide",
  "Science and Faith": "science-faith-guide",
  "Big Bang": "science-faith-guide",
  "OT Theology": "old-testament-theology-guide",
  "Biblical Theology": "old-testament-theology-guide",
  Typology: "old-testament-theology-guide",
  "Messianic Prophecy": "old-testament-theology-guide",
  Doubt: "doubt-faith-guide",
  "Dark Night of the Soul": "doubt-faith-guide",
  "Church Hurt": "doubt-faith-guide",
  "Rebuilding Faith": "doubt-faith-guide",
  "Christian Marriage": "christian-marriage-guide",
  Infidelity: "christian-marriage-guide",
  "Marital Communication": "christian-marriage-guide",
  "Gottman Method": "christian-marriage-guide",
  "Gospel of John": "gospel-of-john-guide",
  "I AM Sayings": "gospel-of-john-guide",
  Logos: "gospel-of-john-guide",
  "Farewell Discourse": "gospel-of-john-guide",
  "Word Christology": "gospel-of-john-guide",
  "Seven Signs": "gospel-of-john-guide",
  "Gospel of Matthew": "gospel-of-matthew-guide",
  "New Moses": "gospel-of-matthew-guide",
  "Fulfillment Quotations": "gospel-of-matthew-guide",
  TULIP: "grace-theology-guide",
  "Five Points": "grace-theology-guide",
  "Unconditional Election": "grace-theology-guide",
  "Irresistible Grace": "grace-theology-guide",
  "Common Grace": "grace-theology-guide",
  "Prevenient Grace": "grace-theology-guide",
  Catechesis: "christian-parenting-guide",
  "Family Worship": "christian-parenting-guide",
  "Prodigal Children": "christian-parenting-guide",
  "Home Discipleship": "christian-parenting-guide",
  "Book of Acts": "book-of-acts-guide",
  Pentecost: "book-of-acts-guide",
  "Acts of the Apostles": "acts-of-the-apostles-guide",
  "Missionary Journeys": "acts-of-the-apostles-guide",
  "Jerusalem Council": "acts-of-the-apostles-guide",
  "Paul's Journeys": "acts-of-the-apostles-guide",
  "Early Church": "acts-of-the-apostles-guide",
  Parables: "parables-deep-dive",
  "Kingdom Parables": "parables-deep-dive",
  "Parables of Jesus": "parables-of-jesus",
  "Book of Genesis": "genesis-guide",
  Genesis: "genesis-guide",
  "Proto-Evangelion": "genesis-guide",
  "Abrahamic Covenant": "genesis-guide",
  "Tower of Babel": "genesis-guide",
  "Joseph Story": "genesis-guide",
  Joy: "christian-joy-guide",
  Contentment: "philippians-guide",
  "Joy in Suffering": "christian-joy-guide",
  Gratitude: "christian-joy-guide",
  Hebrews: "hebrews-guide",
  "Book of Hebrews": "hebrews-guide",
  Melchizedek: "hebrews-guide",
  "High Priest": "hebrews-guide",
  "Hall of Faith": "hebrews-guide",
  Galatians: "galatians-guide",
  "Book of Galatians": "galatians-guide",
  Judaizers: "galatians-guide",
  "Christian Freedom": "galatians-guide",
  "Women in the Bible": "women-theology-guide",
  "Women in Ministry": "women-theology-guide",
  "Mary Magdalene": "women-theology-guide",
  Junia: "women-theology-guide",
  Phoebe: "women-theology-guide",
  Priscilla: "women-theology-guide",
  Deborah: "women-theology-guide",
  Philippians: "philippians-guide",
  "Book of Philippians": "philippians-guide",
  Kenosis: "philippians-guide",
  "Christ Hymn": "philippians-guide",
  Ephesians: "ephesians-guide",
  "Book of Ephesians": "ephesians-guide",
  "Mystery of the Church": "ephesians-guide",
  Poiema: "ephesians-guide",
  Predestination: "ephesians-guide",
  Colossians: "colossians-guide",
  "Book of Colossians": "colossians-guide",
  "Colossian Heresy": "colossians-guide",
  "Fullness in Christ": "colossians-guide",
  "Preeminence of Christ": "colossians-guide",
  "1 Corinthians": "first-corinthians-guide",
  "Book of 1 Corinthians": "first-corinthians-guide",
  "Love Chapter": "first-corinthians-guide",
  "1 Corinthians 13": "first-corinthians-guide",
  "Agape Love": "first-corinthians-guide",
  "Wisdom of the Cross": "first-corinthians-guide",
  James: "book-of-james-guide",
  "Book of James": "book-of-james-guide",
  "Faith and Works": "book-of-james-guide",
  "Taming the Tongue": "book-of-james-guide",
  "Wisdom from Above": "book-of-james-guide",
  "Prayer of Faith": "book-of-james-guide",
  "1 Peter": "first-peter-guide",
  "Book of 1 Peter": "first-peter-guide",
  "Living Hope": "first-peter-guide",
  "Royal Priesthood": "first-peter-guide",
  "Elect Exiles": "first-peter-guide",
  "Fiery Trial": "first-peter-guide",
  "Book of Revelation": "revelation-guide",
  "Seven Churches": "revelation-guide",
  "Four Horsemen": "revelation-guide",
  "Mark of the Beast": "revelation-guide",
  "Lamb of God": "revelation-guide",
  "2 Corinthians": "second-corinthians-guide",
  "Book of 2 Corinthians": "second-corinthians-guide",
  "Jars of Clay": "second-corinthians-guide",
  "Thorn in the Flesh": "second-corinthians-guide",
  "Ministry of Reconciliation": "second-corinthians-guide",
  "Power in Weakness": "second-corinthians-guide",
  "Theology of Work": "theology-of-work-guide",
  "Work as Worship": "theology-of-work-guide",
  "Work and Calling": "theology-of-work-guide",
  "Labor and Rest": "theology-of-work-guide",
  "Monday Morning Theology": "theology-of-work-guide",
  Repentance: "confession-repentance-guide",
  Confession: "confession-repentance-guide",
  "Psalm 51": "confession-repentance-guide",
  "Godly Sorrow": "confession-repentance-guide",
  "Prodigal Son": "confession-repentance-guide",
  Metanoia: "confession-repentance-guide",
  "Gospel of Mark": "gospel-of-mark-guide",
  "Book of Mark": "gospel-of-mark-guide",
  "Messianic Secret": "gospel-of-mark-guide",
  "Son of Man": "gospel-of-mark-guide",
  "Ransom for Many": "gospel-of-mark-guide",
  "Cry of Dereliction": "christian-suffering-guide",
  "Book of Job": "christian-suffering-guide",
  "Why Does God Allow Suffering": "christian-suffering-guide",
  "Theologia Crucis": "christian-suffering-guide",
  "Gospel of Luke": "gospel-of-luke-guide",
  "Book of Luke": "gospel-of-luke-guide",
  "Great Reversal": "gospel-of-luke-guide",
  "Good Samaritan": "gospel-of-luke-guide",
  Magnificat: "gospel-of-luke-guide",
  Zacchaeus: "gospel-of-luke-guide",
  "Church as Body of Christ": "christian-community-guide",
  "Spiritual Friendship": "christian-community-guide",
  "One Another Commands": "christian-community-guide",
  "Life Together": "christian-community-guide",
  "Jesus Prayer": "theology-of-prayer-guide",
  "Centering Prayer": "theology-of-prayer-guide",
  Daniel: "daniel-guide",
  "Book of Daniel": "daniel-guide",
  "Four Kingdoms": "daniel-guide",
  "Fiery Furnace": "daniel-guide",
  "Son of Man Vision": "daniel-guide",
  Isaiah: "isaiah-guide",
  "Book of Isaiah": "isaiah-guide",
  "Servant Songs": "isaiah-guide",
  "Isaiah 53": "isaiah-guide",
  "Suffering Servant": "isaiah-guide",
  "Holy One of Israel": "isaiah-guide",
  "New Heavens": "isaiah-guide",
  "Pastoral Epistles": "pastoral-epistles-guide",
  "Elder Qualifications": "pastoral-epistles-guide",
  "Sound Doctrine": "pastoral-epistles-guide",
  "1 Timothy": "pastoral-epistles-guide",
  "2 Timothy": "pastoral-epistles-guide",
  Titus: "pastoral-epistles-guide",
  Proverbs: "proverbs-guide",
  "Book of Proverbs": "proverbs-guide",
  "Fear of the Lord": "proverbs-guide",
  "Lady Wisdom": "proverbs-guide",
  "Proverbs 31": "proverbs-guide",
  "Woman of Valor": "proverbs-guide",
  Ecclesiastes: "ecclesiastes-guide",
  "Book of Ecclesiastes": "ecclesiastes-guide",
  Qoheleth: "ecclesiastes-guide",
  Hebel: "ecclesiastes-guide",
  "Vanity of Vanities": "ecclesiastes-guide",
  "Meaning of Life": "ecclesiastes-guide",
  "Job Study": "job-guide",
  "Innocent Suffering": "job-guide",
  "My Redeemer Lives": "job-guide",
  "Whirlwind Speech": "job-guide",
  Exodus: "exodus-guide",
  "Book of Exodus": "exodus-guide",
  Passover: "exodus-guide",
  "Ten Plagues": "exodus-guide",
  Tabernacle: "exodus-guide",
  "Ten Commandments": "exodus-guide",
  "Sinai Covenant": "exodus-guide",
  "Minor Prophets": "minor-prophets-guide",
  "Book of the Twelve": "minor-prophets-guide",
  Amos: "amos-guide",
  Hosea: "hosea-guide",
  Micah: "micah-guide",
  Jonah: "jonah-guide",
  Habakkuk: "habakkuk-guide",
  Obadiah: "obadiah-guide",
  "Book of Obadiah": "obadiah-guide",
  "Pride Goes Before Destruction": "obadiah-guide",
  Edom: "obadiah-guide",
  Nahum: "nahum-guide",
  "Book of Nahum": "nahum-guide",
  "Fall of Nineveh": "nahum-guide",
  "God Is Slow to Anger": "nahum-guide",
  Leviticus: "leviticus-guide",
  "Book of Leviticus": "leviticus-guide",
  "Day of Atonement": "leviticus-guide",
  "Yom Kippur": "leviticus-guide",
  Jude: "jude-guide",
  "Book of Jude": "jude-guide",
  "Life of Christ": "life-of-christ",
  "Harmony of the Gospels": "life-of-christ",
  "The Gospels": "life-of-christ",
  "1 Chronicles": "chronicles-guide",
  "2 Chronicles": "chronicles-guide",
  Chronicles: "chronicles-guide",
  "If My People": "chronicles-guide",
  "2 Chronicles 7:14": "chronicles-guide",
  "2 Peter": "second-peter-guide",
  "Book of 2 Peter": "second-peter-guide",
  "Divine Nature": "second-peter-guide",
  "Partakers of the Divine Nature": "second-peter-guide",
  "Eyewitness Faith": "second-peter-guide",
  "Contend for the Faith": "jude-guide",
  "Jude Doxology": "jude-guide",
  Zephaniah: "zephaniah-guide",
  "Book of Zephaniah": "zephaniah-guide",
  "Zephaniah 3:17": "zephaniah-guide",
  "God Sings Over You": "zephaniah-guide",
  "Micah 6:8": "micah-guide",
  "God Is Love": "letters-of-john-guide",
  "1 John": "letters-of-john-guide",
  "2 John": "letters-of-john-guide",
  "Letters of John": "letters-of-john-guide",
  "Walking in Light": "letters-of-john-guide",
  "Song of Songs": "song-of-songs-guide",
  "Song of Solomon": "song-of-songs-guide",
  Canticles: "song-of-songs-guide",
  "Covenant Love": "song-of-songs-guide",
  "Love Strong as Death": "song-of-songs-guide",
  Ruth: "ruth-esther-guide",
  Esther: "ruth-esther-guide",
  "Book of Ruth": "ruth-esther-guide",
  "Book of Esther": "ruth-esther-guide",
  "Kinsman Redeemer": "ruth-esther-guide",
  Boaz: "ruth-esther-guide",
  Hesed: "ruth-esther-guide",
  "For Such a Time": "ruth-esther-guide",
  Purim: "ruth-esther-guide",
  Jeremiah: "jeremiah-guide",
  "Book of Jeremiah": "jeremiah-guide",
  "Weeping Prophet": "jeremiah-guide",
  "Jeremiah 29:11": "jeremiah-guide",
  "Potter and Clay": "jeremiah-guide",
  "Letter to the Exiles": "jeremiah-guide",
  Ezekiel: "ezekiel-guide",
  "Book of Ezekiel": "ezekiel-guide",
  "Valley of Dry Bones": "ezekiel-guide",
  Merkabah: "ezekiel-guide",
  "New Heart": "ezekiel-guide",
  "River of Life": "ezekiel-guide",
  "Glory of God": "ezekiel-guide",
  Thessalonians: "thessalonians-guide",
  "1 Thessalonians": "thessalonians-guide",
  "2 Thessalonians": "thessalonians-guide",
  Parousia: "thessalonians-guide",
  "Dead in Christ": "thessalonians-guide",
  "Day of the Lord": "thessalonians-guide",
  "Pray Without Ceasing": "thessalonians-guide",
  Joshua: "joshua-judges-guide",
  Judges: "joshua-judges-guide",
  "Book of Joshua": "joshua-judges-guide",
  "Book of Judges": "joshua-judges-guide",
  Rahab: "joshua-judges-guide",
  Jericho: "joshua-judges-guide",
  Gideon: "joshua-judges-guide",
  Samson: "joshua-judges-guide",
  "Judges Cycle": "joshua-judges-guide",
  Numbers: "numbers-deuteronomy-guide",
  Deuteronomy: "numbers-deuteronomy-guide",
  "Book of Numbers": "numbers-deuteronomy-guide",
  "Book of Deuteronomy": "numbers-deuteronomy-guide",
  Shema: "numbers-deuteronomy-guide",
  "Choose Life": "numbers-deuteronomy-guide",
  "Aaronic Blessing": "numbers-deuteronomy-guide",
  "Bronze Serpent": "numbers-deuteronomy-guide",
  "Balaam": "numbers-deuteronomy-guide",
  "John of the Cross": "christian-dark-night-guide",
  "Spiritual Dryness": "christian-dark-night-guide",
  "Spiritual Desolation": "christian-dark-night-guide",
  "Mother Teresa": "christian-dark-night-guide",
  "Faith in Darkness": "christian-dark-night-guide",
  Samuel: "samuel-guide",
  "1 Samuel": "samuel-guide",
  "2 Samuel": "samuel-guide",
  David: "samuel-guide",
  "King David": "samuel-guide",
  "Davidic Covenant": "samuel-guide",
  Hannah: "samuel-guide",
  Goliath: "samuel-guide",
  Absalom: "samuel-guide",
  "Man After God's Own Heart": "samuel-guide",
  "Jesus Wept": "grief-lament-guide",
  Mourning: "grief-lament-guide",
  "Psalms of Lament": "grief-lament-guide",
  "Grief Guide": "grief-lament-guide",
  Bereavement: "grief-lament-guide",
  Solomon: "kings-guide",
  Elijah: "kings-guide",
  Elisha: "kings-guide",
  Naaman: "kings-guide",
  Hezekiah: "kings-guide",
  "Divided Kingdom": "kings-guide",
  "Still Small Voice": "kings-guide",
  "Solomon's Temple": "kings-guide",
  "How to Pray": "how-to-pray-guide",
  "ACTS Prayer": "how-to-pray-guide",
  "Daily Prayer": "how-to-pray-guide",
  "Prayer Practice": "how-to-pray-guide",
  Ezra: "ezra-nehemiah-guide",
  Nehemiah: "ezra-nehemiah-guide",
  "Book of Ezra": "ezra-nehemiah-guide",
  "Book of Nehemiah": "ezra-nehemiah-guide",
  "Return from Exile": "ezra-nehemiah-guide",
  "Rebuilding Jerusalem": "ezra-nehemiah-guide",
  "Ezra Prayer": "ezra-nehemiah-guide",
  "Nehemiah Wall": "ezra-nehemiah-guide",
  "Covenant Renewal": "ezra-nehemiah-guide",
  Gomer: "hosea-guide",
  "Book of Hosea": "hosea-guide",
  "Spiritual Adultery": "hosea-guide",
  "Hosea 11": "hosea-guide",
  "Marriage Metaphor": "hosea-guide",
  "Valley of Achor": "hosea-guide",
  "Book of Amos": "amos-guide",
  "Amos 5:24": "amos-guide",
  "Social Justice": "amos-guide",
  "Day of the LORD": "amos-guide",
  "Plumb Line": "amos-guide",
  "Book of Micah": "micah-guide",
  "Walk Humbly": "micah-guide",
  "Swords into Plowshares": "micah-guide",
  "Bethlehem Prophecy": "micah-guide",
  "God Who Pardons": "micah-guide",
  "Book of Jonah": "jonah-guide",
  Nineveh: "jonah-guide",
  "Sign of Jonah": "jonah-guide",
  "Running from God": "jonah-guide",
  "Book of Habakkuk": "habakkuk-guide",
  "Habakkuk 3:17": "habakkuk-guide",
  "Though the Fig Tree": "habakkuk-guide",
  "Righteous Live by Faith": "habakkuk-guide",
  "How Long O Lord": "habakkuk-guide",
  Lamentations: "lamentations-guide",
  "Book of Lamentations": "lamentations-guide",
  "Steadfast Love": "lamentations-guide",
  "New Every Morning": "lamentations-guide",
  "Great Is Thy Faithfulness": "lamentations-guide",
  Eikah: "lamentations-guide",
  Zechariah: "zechariah-guide",
  "Book of Zechariah": "zechariah-guide",
  "Not by Might": "zechariah-guide",
  "Triumphal Entry": "zechariah-guide",
  "Thirty Pieces of Silver": "zechariah-guide",
  "Night Visions": "zechariah-guide",
  "The Branch": "zechariah-guide",
  Haggai: "haggai-guide",
  "Book of Haggai": "haggai-guide",
  "Latter Glory": "haggai-guide",
  "Consider Your Ways": "haggai-guide",
  Zerubbabel: "haggai-guide",
  Malachi: "malachi-guide",
  "Book of Malachi": "malachi-guide",
  "Return to Me": "malachi-guide",
  "Sun of Righteousness": "malachi-guide",
  Tithe: "malachi-guide",
  "I Have Loved You": "malachi-guide",
  "400 Years of Silence": "malachi-guide",
};


const ALL_TOPICS: Topic[] = [
  { label: "Addiction" },
  { label: "Anxiety" },
  { label: "Apologetics" },
  { label: "Baptism" },
  { label: "Bible Study" },
  { label: "Career" },
  { label: "Community" },
  { label: "Creation" },
  { label: "Dating" },
  { label: "Depression" },
  { label: "Devotionals" },
  { label: "Doubt" },
  { label: "End Times" },
  { label: "Evangelism" },
  { label: "Family" },
  { label: "Fasting" },
  { label: "Finance" },
  { label: "Forgiveness" },
  { label: "Grief" },
  { label: "Grace" },
  { label: "Holy Spirit" },
  { label: "Hope" },
  { label: "Identity" },
  { label: "Integrity" },
  { label: "Jesus" },
  { label: "Leadership" },
  { label: "Love" },
  { label: "Marriage" },
  { label: "Mental Health" },
  { label: "Ministry" },
  { label: "Miracles" },
  { label: "Missions" },
  { label: "Kingdom of God" },
  { label: "Missiology" },
  { label: "Parenting" },
  { label: "Prayer" },
  { label: "Prophecy" },
  { label: "Purpose" },
  { label: "Relationships" },
  { label: "Repentance" },
  { label: "Resurrection" },
  { label: "Salvation" },
  { label: "Sanctification" },
  { label: "Scripture" },
  { label: "Serving" },
  { label: "Sexuality" },
  { label: "Suffering" },
  { label: "Theology" },
  { label: "Trinity" },
  { label: "Trust" },
  { label: "Unity" },
  { label: "Worship" },
  { label: "Youth" },
  { label: "Discernment" },
  { label: "Enneagram" },
  { label: "Generational Trauma" },
  { label: "Introverts" },
  { label: "Lament" },
  { label: "Examen" },
  { label: "Digital Detox" },
  { label: "Prosperity Gospel" },
  { label: "Complementarianism" },
  { label: "Egalitarianism" },
  { label: "Cessationism" },
  { label: "Continuationism" },
  { label: "Calvinism" },
  { label: "Arminianism" },
  { label: "Christian Nationalism" },
  { label: "Open Theism" },
  { label: "Just War" },
  { label: "Pacifism" },
  { label: "Mindfulness" },
  { label: "Yoga" },
  { label: "Revelation" },
  { label: "Hell" },
  { label: "Universalism" },
  { label: "Theosis" },
  { label: "Covenant Theology" },
  { label: "Dispensationalism" },
  { label: "Sexuality" },
  { label: "Christology" },
  { label: "Incarnation" },
  { label: "Five Solas" },
  { label: "Reformation" },
  { label: "Sin" },
  { label: "Hamartiology" },
  { label: "Pneumatology" },
  { label: "Assurance" },
  { label: "Religious Liberty" },
  { label: "Sacraments" },
  { label: "Law and Gospel" },
  { label: "Legalism" },
  { label: "Beauty" },
  { label: "Arts" },
  { label: "Aesthetics" },
  { label: "Vocation" },
  { label: "Calling" },
  { label: "Work" },
  { label: "Hermeneutics" },
  { label: "Bible Interpretation" },
  { label: "Exegesis" },
  { label: "Justification" },
  { label: "Sola Fide" },
  { label: "Imputation" },
  { label: "Creation" },
  { label: "Cultural Mandate" },
  { label: "Ethics" },
  { label: "Natural Law" },
  { label: "Virtue Ethics" },
  { label: "Moral Theology" },
  { label: "Marriage Theology" },
  { label: "Divorce" },
  { label: "Easter" },
  { label: "Church History" },
  { label: "Church Fathers" },
  { label: "Reformation History" },
  { label: "Eschatology" },
  { label: "End Times" },
  { label: "Millennium" },
  { label: "Rapture" },
  { label: "Atonement" },
  { label: "Penal Substitution" },
  { label: "Inerrancy" },
  { label: "Biblical Lament" },
  { label: "Lament Psalms" },
  { label: "Spiritual Formation" },
  { label: "Spiritual Disciplines" },
  { label: "Lectio Divina" },
  { label: "Rule of Life" },
  { label: "Contemplative Prayer" },
  { label: "Theology of Prayer" },
  { label: "Intercession" },
  { label: "Lord's Prayer" },
  { label: "Unanswered Prayer" },
  { label: "Attributes of God" },
  { label: "Theology Proper" },
  { label: "Names of God" },
  { label: "Divine Simplicity" },
  { label: "Aseity" },
  { label: "Inspiration" },
  { label: "Sola Scriptura" },
  { label: "Biblical Canon" },
  { label: "Free Will" },
  { label: "Compatibilism" },
  { label: "Conscience" },
  { label: "Christian Anthropology" },
  { label: "Angels" },
  { label: "Angelology" },
  { label: "Demons" },
  { label: "Spiritual Warfare" },
  { label: "Armor of God" },
  { label: "Mortification" },
  { label: "Holiness" },
  { label: "Means of Grace" },
  { label: "Preaching" },
  { label: "Homiletics" },
  { label: "Expository Preaching" },
  { label: "Worship Theology" },
  { label: "Liturgy" },
  { label: "Worship Music" },
  { label: "Discipleship" },
  { label: "Cost of Discipleship" },
  { label: "Small Groups" },
  { label: "Great Commission" },
  { label: "Gospel Presentation" },
  { label: "Witness" },
  { label: "Heaven" },
  { label: "New Creation" },
  { label: "Resurrection Body" },
  { label: "New Jerusalem" },
  { label: "Eternal Life" },
  { label: "Theology of Suffering" },
  { label: "Spiritual Gifts" },
  { label: "Sign Gifts" },
  { label: "Tongues" },
  { label: "Healing" },
  { label: "Beatitudes" },
  { label: "Sermon on the Mount" },
  { label: "Kingdom Ethics" },
  { label: "Pastoral Care" },
  { label: "Shepherding" },
  { label: "Church Discipline" },
  { label: "Biblical Counseling" },
  { label: "Soul Care" },
  { label: "Romans" },
  { label: "No Condemnation" },
  { label: "Evolution" },
  { label: "Historical Adam" },
  { label: "Science and Faith" },
  { label: "OT Theology" },
  { label: "Biblical Theology" },
  { label: "Typology" },
  { label: "Messianic Prophecy" },
  { label: "Dark Night of the Soul" },
  { label: "Church Hurt" },
  { label: "Rebuilding Faith" },
  { label: "Christian Marriage" },
  { label: "Infidelity" },
  { label: "Marital Communication" },
  { label: "Gottman Method" },
  { label: "Gospel of John" },
  { label: "I AM Sayings" },
  { label: "Logos" },
  { label: "Farewell Discourse" },
  { label: "Word Christology" },
  { label: "Seven Signs" },
  { label: "Gospel of Matthew" },
  { label: "New Moses" },
  { label: "Fulfillment Quotations" },
  { label: "TULIP" },
  { label: "Five Points" },
  { label: "Unconditional Election" },
  { label: "Irresistible Grace" },
  { label: "Common Grace" },
  { label: "Prevenient Grace" },
  { label: "Catechesis" },
  { label: "Family Worship" },
  { label: "Prodigal Children" },
  { label: "Home Discipleship" },
  { label: "Book of Acts" },
  { label: "Pentecost" },
  { label: "Missionary Journeys" },
  { label: "Jerusalem Council" },
  { label: "Book of Genesis" },
  { label: "Proto-Evangelion" },
  { label: "Abrahamic Covenant" },
  { label: "Tower of Babel" },
  { label: "Joy" },
  { label: "Contentment" },
  { label: "Joy in Suffering" },
  { label: "Gratitude" },
  { label: "Sabbath" },
  { label: "Book of Hebrews" },
  { label: "Melchizedek" },
  { label: "High Priest" },
  { label: "Hall of Faith" },
  { label: "Book of Galatians" },
  { label: "Fruit of the Spirit" },
  { label: "Judaizers" },
  { label: "Christian Freedom" },
  { label: "Women in the Bible" },
  { label: "Women in Ministry" },
  { label: "Mary Magdalene" },
  { label: "Junia" },
  { label: "Phoebe" },
  { label: "Priscilla" },
  { label: "Deborah" },
  { label: "Book of Philippians" },
  { label: "Kenosis" },
  { label: "Christ Hymn" },
  { label: "Philippians 4:7" },
  { label: "Philippians 4:13" },
  { label: "Partnership in the Gospel" },
  { label: "Book of Ephesians" },
  { label: "Mystery of the Church" },
  { label: "Poiema" },
  { label: "Predestination" },
  { label: "Book of Colossians" },
  { label: "Colossian Heresy" },
  { label: "Fullness in Christ" },
  { label: "Preeminence of Christ" },
  { label: "Hope of Glory" },
  { label: "1 Corinthians" },
  { label: "Love Chapter" },
  { label: "1 Corinthians 13" },
  { label: "Agape Love" },
  { label: "Wisdom of the Cross" },
  { label: "Book of James" },
  { label: "Faith and Works" },
  { label: "Taming the Tongue" },
  { label: "Wisdom from Above" },
  { label: "Prayer of Faith" },
  { label: "Book of 1 Peter" },
  { label: "Living Hope" },
  { label: "Royal Priesthood" },
  { label: "Elect Exiles" },
  { label: "Fiery Trial" },
  { label: "Book of Revelation" },
  { label: "Seven Churches" },
  { label: "Four Horsemen" },
  { label: "Mark of the Beast" },
  { label: "Lamb of God" },
  { label: "Book of 2 Corinthians" },
  { label: "Jars of Clay" },
  { label: "Thorn in the Flesh" },
  { label: "Ministry of Reconciliation" },
  { label: "Power in Weakness" },
  { label: "Theology of Work" },
  { label: "Work as Worship" },
  { label: "Work and Calling" },
  { label: "Labor and Rest" },
  { label: "Confession" },
  { label: "Repentance" },
  { label: "Psalm 51" },
  { label: "Godly Sorrow" },
  { label: "Prodigal Son" },
  { label: "Metanoia" },
  { label: "Gospel of Mark" },
  { label: "Messianic Secret" },
  { label: "Son of Man" },
  { label: "Ransom for Many" },
  { label: "Theodicy" },
  { label: "Book of Job" },
  { label: "Theologia Crucis" },
  { label: "Cry of Dereliction" },
  { label: "Gospel of Luke" },
  { label: "Great Reversal" },
  { label: "Good Samaritan" },
  { label: "Magnificat" },
  { label: "Zacchaeus" },
  { label: "Ecclesiology" },
  { label: "Church as Body of Christ" },
  { label: "Spiritual Friendship" },
  { label: "One Another Commands" },
  { label: "Lectio Divina" },
  { label: "Examen" },
  { label: "Jesus Prayer" },
  { label: "Centering Prayer" },
  { label: "Unanswered Prayer" },
  { label: "Contemplative Prayer" },
  { label: "Daniel" },
  { label: "Isaiah" },
  { label: "Servant Songs" },
  { label: "Isaiah 53" },
  { label: "Pastoral Epistles" },
  { label: "Elder Qualifications" },
  { label: "Sound Doctrine" },
  { label: "New Heavens" },
  { label: "Proverbs" },
  { label: "Fear of the Lord" },
  { label: "Lady Wisdom" },
  { label: "Proverbs 31" },
  { label: "Ecclesiastes" },
  { label: "Qoheleth" },
  { label: "Vanity of Vanities" },
  { label: "Innocent Suffering" },
  { label: "Whirlwind Speech" },
  { label: "My Redeemer Lives" },
  { label: "Exodus" },
  { label: "Passover" },
  { label: "Ten Plagues" },
  { label: "Tabernacle" },
  { label: "Ten Commandments" },
  { label: "Minor Prophets" },
  { label: "Amos" },
  { label: "Hosea" },
  { label: "Micah" },
  { label: "Jonah" },
  { label: "Obadiah" },
  { label: "Habakkuk" },
  { label: "Zephaniah" },
  { label: "God Is Love" },
  { label: "1 John" },
  { label: "Letters of John" },
  { label: "Walking in Light" },
  { label: "Song of Songs" },
  { label: "Song of Solomon" },
  { label: "Covenant Love" },
  { label: "Hebrew Love Poetry" },
  { label: "Ruth" },
  { label: "Esther" },
  { label: "Kinsman Redeemer" },
  { label: "Hesed" },
  { label: "For Such a Time as This" },
  { label: "Hidden Providence" },
  { label: "Jeremiah" },
  { label: "New Covenant" },
  { label: "Weeping Prophet" },
  { label: "Jeremiah 29:11" },
  { label: "Potter and Clay" },
  { label: "Ezekiel" },
  { label: "Valley of Dry Bones" },
  { label: "New Heart" },
  { label: "River of Life" },
  { label: "Dry Bones" },
  { label: "1 Thessalonians" },
  { label: "2 Thessalonians" },
  { label: "Parousia" },
  { label: "Dead in Christ" },
  { label: "Pray Without Ceasing" },
  { label: "Joshua" },
  { label: "Judges" },
  { label: "Rahab" },
  { label: "Jericho" },
  { label: "Deborah" },
  { label: "Gideon" },
  { label: "Samson" },
  { label: "Judges Cycle" },
  { label: "Numbers" },
  { label: "Deuteronomy" },
  { label: "Shema" },
  { label: "Choose Life" },
  { label: "Aaronic Blessing" },
  { label: "Bronze Serpent" },
  { label: "Dark Night of the Soul" },
  { label: "John of the Cross" },
  { label: "Spiritual Dryness" },
  { label: "Mother Teresa" },
  { label: "Contemplative Prayer" },
  { label: "Samuel" },
  { label: "1 Samuel" },
  { label: "2 Samuel" },
  { label: "David" },
  { label: "Davidic Covenant" },
  { label: "Hannah" },
  { label: "Goliath" },
  { label: "Absalom" },
  { label: "Man After God's Own Heart" },
  { label: "Jesus Wept" },
  { label: "Mourning" },
  { label: "Psalms of Lament" },
  { label: "Bereavement" },
  { label: "Solomon" },
  { label: "Elijah" },
  { label: "Elisha" },
  { label: "Naaman" },
  { label: "Hezekiah" },
  { label: "Still Small Voice" },
  { label: "Divided Kingdom" },
  { label: "How to Pray" },
  { label: "ACTS Prayer" },
  { label: "Unanswered Prayer" },
  { label: "Daily Prayer" },
  { label: "Intercession" },
  { label: "Ezra" },
  { label: "Nehemiah" },
  { label: "Return from Exile" },
  { label: "Rebuilding Jerusalem" },
  { label: "Covenant Renewal" },
  { label: "Gomer" },
  { label: "Book of Hosea" },
  { label: "Spiritual Adultery" },
  { label: "Valley of Achor" },
  { label: "Hosea 11" },
  { label: "Book of Amos" },
  { label: "Amos 5:24" },
  { label: "Social Justice" },
  { label: "Day of the LORD" },
  { label: "Plumb Line" },
  { label: "Book of Micah" },
  { label: "Micah 6:8" },
  { label: "Walk Humbly" },
  { label: "Swords into Plowshares" },
  { label: "Bethlehem Prophecy" },
  { label: "Book of Jonah" },
  { label: "Nineveh" },
  { label: "Sign of Jonah" },
  { label: "Book of Obadiah" },
  { label: "Edom" },
  { label: "Nahum" },
  { label: "Fall of Nineveh" },
  { label: "Leviticus" },
  { label: "Day of Atonement" },
  { label: "Jude" },
  { label: "Contend for the Faith" },
  { label: "Chronicles" },
  { label: "2 Chronicles 7:14" },
  { label: "2 Peter" },
  { label: "Divine Nature" },
  { label: "Life of Christ" },
  { label: "Harmony of the Gospels" },
  { label: "Book of Habakkuk" },
  { label: "Habakkuk 3:17" },
  { label: "Book of Zephaniah" },
  { label: "Zephaniah 3:17" },
  { label: "God Sings Over You" },
  { label: "Though the Fig Tree" },
  { label: "Righteous Live by Faith" },
  { label: "Lamentations" },
  { label: "Steadfast Love" },
  { label: "New Every Morning" },
  { label: "Zechariah" },
  { label: "Not by Might" },
  { label: "Triumphal Entry" },
  { label: "Night Visions" },
  { label: "The Branch" },
  { label: "Haggai" },
  { label: "Latter Glory" },
  { label: "Consider Your Ways" },
  { label: "Malachi" },
  { label: "Return to Me" },
  { label: "Sun of Righteousness" },
  { label: "Tithe" },
];

const ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");

export default function TopicBrowser() {
  const [activeLetter, setActiveLetter] = usePersistedState("vine_home_topic_letter", "All");
  const [searchQuery, setSearchQuery] = useState("");
  const [suggested, setSuggested] = useState(false);

  const filtered = useMemo(() => {
    if (searchQuery.trim()) {
      const q = searchQuery.toLowerCase();
      return ALL_TOPICS.filter((t) => t.label.toLowerCase().includes(q));
    }
    if (activeLetter !== "All") {
      return ALL_TOPICS.filter((t) => t.label.toUpperCase().startsWith(activeLetter));
    }
    return ALL_TOPICS;
  }, [activeLetter, searchQuery]);

  const handleLetterClick = (letter: string) => {
    setActiveLetter(letter);
    setSearchQuery("");
  };

  return (
    <section
      style={{
        background: "#0a1a0e",
        padding: "100px 4vw",
        borderTop: "0.5px solid rgba(201,162,39,0.18)",
        position: "relative",
        overflow: "hidden",
      }}
    >
      <div
        style={{
          position: "absolute",
          top: "50%",
          left: "50%",
          transform: "translate(-50%, -50%)",
          width: 700,
          height: 500,
          background: "radial-gradient(ellipse, rgba(58,125,86,0.06) 0%, transparent 65%)",
          pointerEvents: "none",
        }}
      />

      <div style={{ maxWidth: 1200, margin: "0 auto", position: "relative", zIndex: 1 }}>
        {/* Header */}
        <div style={{ textAlign: "center", marginBottom: "3rem" }}>
          <div className="vine-eyebrow" style={{ marginBottom: "0.9rem" }}>
            <Hash size={11} style={{ display: "inline", marginRight: 5 }} />
            60+ Topics
          </div>
          <h2
            style={{
              fontFamily: "var(--font-cormorant, 'Cormorant Garamond', Georgia, serif)",
              fontSize: "clamp(2rem, 4vw, 3.4rem)",
              fontWeight: 300,
              color: "#f2e6c8",
              lineHeight: 1.15,
              marginBottom: "1rem",
            }}
          >
            Explore every
            <em style={{ fontStyle: "italic", color: "#e8c162" }}> topic.</em>
          </h2>
          <p
            style={{
              fontFamily: "var(--font-jost, system-ui, sans-serif)",
              fontSize: "0.95rem",
              color: "#9a8f72",
              fontWeight: 300,
              maxWidth: 460,
              margin: "0 auto",
              lineHeight: 1.65,
            }}
          >
            Find discussions, resources, and community around every aspect of
            the Christian life.
          </p>
        </div>

        {/* Search bar */}
        <div style={{ maxWidth: 480, margin: "0 auto 2.5rem", position: "relative" }}>
          <Search
            size={15}
            style={{
              position: "absolute",
              left: 14,
              top: "50%",
              transform: "translateY(-50%)",
              color: "#9a8f72",
              pointerEvents: "none",
            }}
          />
          <input
            type="text"
            placeholder="Search topics..."
            value={searchQuery}
            onChange={(e) => {
              setSearchQuery(e.target.value);
              if (e.target.value) setActiveLetter("All");
            }}
            style={{
              width: "100%",
              padding: "11px 14px 11px 38px",
              borderRadius: 2,
              background: "#050e07",
              border: "0.5px solid rgba(201,162,39,0.2)",
              color: "#f2e6c8",
              fontFamily: "var(--font-jost, system-ui, sans-serif)",
              fontSize: "0.88rem",
              outline: "none",
              transition: "border-color 0.2s",
            }}
            onFocus={(e) => {
              e.target.style.borderColor = "rgba(201,162,39,0.5)";
            }}
            onBlur={(e) => {
              e.target.style.borderColor = "rgba(201,162,39,0.2)";
            }}
          />
        </div>

        {/* Alphabet pills */}
        <div
          style={{
            display: "flex",
            flexWrap: "wrap",
            gap: 5,
            justifyContent: "center",
            marginBottom: "2.5rem",
          }}
        >
          <button
            onClick={() => handleLetterClick("All")}
            style={{
              padding: "5px 14px",
              borderRadius: 2,
              border:
                activeLetter === "All" && !searchQuery
                  ? "0.5px solid rgba(201,162,39,0.55)"
                  : "0.5px solid rgba(201,162,39,0.15)",
              background:
                activeLetter === "All" && !searchQuery
                  ? "rgba(201,162,39,0.1)"
                  : "transparent",
              color:
                activeLetter === "All" && !searchQuery ? "#c9a227" : "#9a8f72",
              fontFamily: "var(--font-jost, system-ui, sans-serif)",
              fontSize: "0.72rem",
              fontWeight: 600,
              cursor: "pointer",
              transition: "all 0.15s",
            }}
          >
            All
          </button>

          {ALPHABET.map((letter) => {
            const hasTopics = ALL_TOPICS.some((t) => t.label.toUpperCase().startsWith(letter));
            const isActive = activeLetter === letter && !searchQuery;
            return (
              <button
                key={letter}
                onClick={() => hasTopics && handleLetterClick(letter)}
                disabled={!hasTopics}
                style={{
                  width: 32,
                  height: 32,
                  borderRadius: 2,
                  border: isActive
                    ? "0.5px solid rgba(201,162,39,0.55)"
                    : "0.5px solid rgba(201,162,39,0.1)",
                  background: isActive ? "rgba(201,162,39,0.1)" : "transparent",
                  color: isActive ? "#c9a227" : hasTopics ? "#9a8f72" : "rgba(201,162,39,0.15)",
                  fontFamily: "var(--font-jost, system-ui, sans-serif)",
                  fontSize: "0.72rem",
                  fontWeight: 600,
                  cursor: hasTopics ? "pointer" : "default",
                  transition: "all 0.15s",
                }}
              >
                {letter}
              </button>
            );
          })}
        </div>

        {/* Count */}
        <p
          style={{
            fontFamily: "var(--font-jost, system-ui, sans-serif)",
            fontSize: "0.72rem",
            color: "#9a8f72",
            textAlign: "center",
            marginBottom: "1.5rem",
            letterSpacing: "0.05em",
          }}
        >
          {searchQuery
            ? `${filtered.length} topic${filtered.length !== 1 ? "s" : ""} matching "${searchQuery}"`
            : activeLetter === "All"
            ? `Showing all ${filtered.length} topics`
            : `${filtered.length} topic${filtered.length !== 1 ? "s" : ""} starting with "${activeLetter}"`}
        </p>

        {/* Topics cloud */}
        <div style={{ display: "flex", flexWrap: "wrap", gap: 8, justifyContent: "center" }}>
          {filtered.map((topic) => {
            const href = TOPIC_SLUGS[topic.label]
              ? `/${TOPIC_SLUGS[topic.label]}`
              : `/discussions?tag=${encodeURIComponent(topic.label)}`;
            return (
              <Link
                key={topic.label}
                href={href}
                style={{
                  display: "inline-flex",
                  alignItems: "center",
                  gap: 6,
                  padding: "7px 16px",
                  borderRadius: 2,
                  background: "transparent",
                  border: "0.5px solid rgba(201,162,39,0.2)",
                  color: "#9a8f72",
                  fontFamily: "var(--font-jost, system-ui, sans-serif)",
                  fontSize: "0.82rem",
                  fontWeight: 400,
                  cursor: "pointer",
                  transition: "all 0.2s",
                  textDecoration: "none",
                }}
                onMouseEnter={(e) => {
                  const el = e.currentTarget as HTMLAnchorElement;
                  el.style.background = "rgba(201,162,39,0.08)";
                  el.style.borderColor = "rgba(201,162,39,0.45)";
                  el.style.color = "#c9a227";
                }}
                onMouseLeave={(e) => {
                  const el = e.currentTarget as HTMLAnchorElement;
                  el.style.background = "transparent";
                  el.style.borderColor = "rgba(201,162,39,0.2)";
                  el.style.color = "#9a8f72";
                }}
              >
                <Hash size={10} style={{ opacity: 0.6 }} />
                {topic.label}
              </Link>
            );
          })}
        </div>

        {filtered.length === 0 && (
          <div style={{ textAlign: "center", padding: "3rem", color: "#9a8f72" }}>
            <Hash size={32} style={{ margin: "0 auto 0.8rem", opacity: 0.25 }} />
            <p
              style={{
                fontFamily: "var(--font-jost, system-ui, sans-serif)",
                fontSize: "0.88rem",
              }}
            >
              No topics found for &ldquo;{searchQuery}&rdquo;
            </p>
          </div>
        )}

        {/* CTA */}
        <div style={{ textAlign: "center", marginTop: "3rem" }}>
          <p
            style={{
              fontFamily: "var(--font-jost, system-ui, sans-serif)",
              fontSize: "0.82rem",
              color: "#9a8f72",
              marginBottom: "1rem",
            }}
          >
            Don&apos;t see your topic? Request it from the community.
          </p>
          <button
            onClick={() => setSuggested(true)}
            disabled={suggested}
            style={{
              padding: "0.7rem 1.8rem",
              borderRadius: 2,
              background: suggested ? "rgba(201,162,39,0.1)" : "transparent",
              border: suggested
                ? "0.5px solid rgba(201,162,39,0.5)"
                : "0.5px solid rgba(201,162,39,0.25)",
              color: suggested ? "#e8c162" : "#c9b98a",
              fontFamily: "var(--font-jost, system-ui, sans-serif)",
              fontSize: "0.78rem",
              fontWeight: 500,
              letterSpacing: "0.08em",
              cursor: suggested ? "default" : "pointer",
              transition: "all 0.2s",
            }}
            onMouseEnter={(e) => {
              if (suggested) return;
              (e.currentTarget as HTMLButtonElement).style.borderColor = "rgba(201,162,39,0.5)";
              (e.currentTarget as HTMLButtonElement).style.color = "#e8c162";
            }}
            onMouseLeave={(e) => {
              if (suggested) return;
              (e.currentTarget as HTMLButtonElement).style.borderColor = "rgba(201,162,39,0.25)";
              (e.currentTarget as HTMLButtonElement).style.color = "#c9b98a";
            }}
          >
            {suggested ? "✓ Thanks — Topic Suggested" : "+ Suggest a Topic"}
          </button>
        </div>
      </div>
    </section>
  );
}
