"use client";
import SectionGuideTemplate, { type SectionGuideData } from "@/components/SectionGuideTemplate";

const TABS: string[] = [
  "Overview",
  "Like Clay in the Potter's Hand",
  "Has My People Forgotten Me?",
  "Plots Against the Intercessor",
  "Application",
];

const sections = [
  {
    id: "Overview",
    heading: "Overview of Jeremiah 18",
    reference: "Jeremiah 18:1&ndash;23",
    paragraphs: [
      "Jeremiah 18 contains one of the most famous images in all of prophecy: the potter's house. God sends Jeremiah down to watch a craftsman at his wheel, and what the prophet sees becomes a living parable of God's dealings with nations and souls. A vessel is spoiled in the potter's hand &mdash; and the potter does not discard the clay but reworks it into another vessel, &lsquo;as it seemed good to the potter to do&rsquo; (18:4). From this ordinary workshop scene God draws an extraordinary declaration: &lsquo;O house of Israel, can I not do with you as this potter has done?&hellip; Behold, like the clay in the potter's hand, so are you in my hand&rsquo; (18:6).",
      "The chapter unfolds in three movements. First, the visit to the potter's house and God's interpretation &mdash; a profound statement of both divine sovereignty and divine responsiveness, for the God who holds absolute rights over the clay also declares that he relents toward nations that repent and reconsiders good toward nations that turn to evil (18:1-12). Second, an oracle marveling at the sheer unnaturalness of Israel's apostasy &mdash; the snow never abandons Lebanon's crags, but God's people have forgotten him and stumbled off the ancient roads (18:13-17). Third, another conspiracy against the prophet &mdash; &lsquo;Come, let us make plots against Jeremiah&rsquo; &mdash; and Jeremiah's anguished prayer, reminding God how he had stood before him to intercede for the very people now digging a pit for his life (18:18-23).",
      "The potter's house holds together two truths that are often torn apart. On one side, God's sovereignty is total: the clay does not instruct the potter, and no nation has standing to veto the Almighty's purposes (Romans 9:20-21 quotes this very scene). On the other side, God's dealings are not fatalistic: &lsquo;If that nation, concerning which I have spoken, turns from its evil, I will relent of the disaster that I intended to do to it&rsquo; (18:8). The wheel is still turning; the clay is still wet; repentance is still possible. Divine sovereignty, rightly understood, is not the closing of the door but the very reason the door can still be opened &mdash; the Potter is free to remake what is marred.",
      "The tragedy of the chapter is the people's answer to this open door: &ldquo;That is in vain! We will follow our own plans, and will everyone act according to the stubbornness of his evil heart&rdquo; (18:12). It is one of the bleakest sentences in Scripture &mdash; not a denial that God is right, but a flat refusal to care. Yet the image of the reworked vessel refuses to die. The gospel announces a Potter who did not throw away the spoiled clay of humanity but, at infinite cost, remakes it: &lsquo;if anyone is in Christ, he is a new creation&rsquo; (2 Corinthians 5:17), and we ourselves are &lsquo;his workmanship, created in Christ Jesus for good works&rsquo; (Ephesians 2:10) &mdash; treasure held, fittingly, &lsquo;in jars of clay&rsquo; (2 Corinthians 4:7).",
    ],
  },
  {
    id: "Like Clay in the Potter's Hand",
    heading: "Can I Not Do with You as This Potter Has Done?",
    reference: "Jeremiah 18:1&ndash;12",
    paragraphs: [
      "The oracle begins with a field trip: &ldquo;Arise, and go down to the potter's house, and there I will let you hear my words&rdquo; (18:2). God teaches his prophet not in the temple but in a workshop, through wet clay and a spinning wheel. &ldquo;And the vessel he was making of clay was spoiled in the potter's hand, and he reworked it into another vessel, as it seemed good to the potter to do&rdquo; (18:4). Every detail matters. The vessel is spoiled <em>in his hand</em> &mdash; the marring happens on the wheel, under the potter's fingers. And the potter's response to spoiled clay is not to hurl it away but to crush it back into a lump and begin again. The same hands that formed the first vessel form the second.",
      "God's interpretation claims the potter's rights for himself: &ldquo;O house of Israel, can I not do with you as this potter has done? declares the Lord. Behold, like the clay in the potter's hand, so are you in my hand, O house of Israel&rdquo; (18:6). This is the bedrock of biblical faith: God is the Potter, we are the clay (Isaiah 64:8), and the creature has no standing to summon the Creator to account. Paul reaches for this exact image when defending God's freedom in election: &lsquo;Has the potter no right over the clay?&rsquo; (Romans 9:21). Whatever else the parable teaches, it begins here &mdash; in the God-ness of God, his unanswerable right to shape history and souls &lsquo;as it seems good&rsquo; to him.",
      "But then the parable takes a turn that pure fatalism could never predict: &ldquo;If at any time I declare concerning a nation&hellip; that I will pluck up and break down and destroy it, and if that nation&hellip; turns from its evil, I will relent of the disaster that I intended to do to it. And if at any time I declare concerning a nation&hellip; that I will build and plant it, and if it does evil in my sight&hellip; I will relent of the good that I had intended&rdquo; (18:7-10). The sovereign Potter is not a blind fate but a living Person who responds to repentance and rebellion. His threats carry an implicit mercy (as Nineveh discovered, Jonah 3:10), and his promises carry an implicit warning. Sovereignty and responsiveness are not rivals in God; the hands on the clay belong to a heart that watches for the slightest turning.",
      "So God makes the appeal explicit: &ldquo;Return, every one from his evil way, and amend your ways and your deeds&rdquo; (18:11). The clay is still on the wheel; the ruin is not yet fired into permanence. And the people's answer is the most chilling in the book: &ldquo;But they say, &lsquo;That is in vain! We will follow our own plans, and will every one act according to the stubbornness of his evil heart&rsquo;&rdquo; (18:12). Not &lsquo;God is wrong,&rsquo; but &lsquo;it is hopeless &mdash; and we prefer our stubbornness anyway.&rsquo; Despair and defiance join hands. Against that refusal, the gospel holds up the Potter who will not give up the clay: he remakes marred vessels into new creations (2 Corinthians 5:17), and no one who returns to his wheel is ever refused &mdash; &lsquo;whoever comes to me I will never cast out&rsquo; (John 6:37).",
    ],
  },
  {
    id: "Has My People Forgotten Me?",
    heading: "The Snow Never Leaves Lebanon",
    reference: "Jeremiah 18:13&ndash;17",
    paragraphs: [
      "God appeals to the jury of the nations: &ldquo;Ask among the nations, who has heard the like of this? The virgin Israel has done a very horrible thing&rdquo; (18:13). Even the pagan world, with all its gods, would be scandalized by Israel's behavior &mdash; for the nations at least stay loyal to their worthless idols (2:10-11), while Israel has abandoned the living God. Apostasy among the covenant people is a horror without parallel: those who knew the true God traded him away.",
      "Then comes the argument from nature's constancy: &ldquo;Does the snow of Lebanon leave the crags of Sirion? Do the mountain waters run dry, the cold flowing streams?&rdquo; (18:14). The high snows of Lebanon never desert their peaks; the cold mountain streams never fail. Nature keeps its appointed faithfulness &mdash; but &ldquo;my people have forgotten me; they make offerings to false gods&rdquo; (18:15). Creation is more constant to its courses than God's people are to their God. It is the same indictment as 8:7, where the migrating stork knows her seasons but Israel does not know the Lord's justice: the unthinking world obeys, while the people of the covenant forget.",
      "The forgetting has practical consequences for their path: &ldquo;they made them stumble in their ways, in the ancient roads, and to walk into side roads, not the highway&rdquo; (18:15). The &lsquo;ancient roads&rsquo; recall 6:16 &mdash; the old, tested paths of covenant faithfulness where rest is found. Idolatry lured Judah off the highway onto crooked byways, and the end of that detour is ruin: &ldquo;making their land a horror, a thing to be hissed at forever&rdquo; (18:16). The judgment fits the sin: &ldquo;Like the east wind I will scatter them before the enemy. I will show them my back, not my face, in the day of their calamity&rdquo; (18:17) &mdash; the people who turned their back on God (2:27) will see his back in the day of trouble.",
      "The oracle's central ache is in one small phrase: &lsquo;my people have forgotten me.&rsquo; Forgetting God is rarely a single dramatic renunciation; it is a slow drift of attention, affection, and habit until the living God becomes a stranger in his own house. Scripture's remedy is deliberate remembering &mdash; &lsquo;Bless the Lord, O my soul, and forget not all his benefits&rsquo; (Psalm 103:2) &mdash; and the Lord Jesus built the remedy into the heart of Christian worship: &lsquo;Do this in remembrance of me&rsquo; (Luke 22:19). The bread and the cup are God's appointed guard against the drift of Jeremiah 18:15, anchoring wandering hearts, week by week, to the God who never forgets his people: &lsquo;Behold, I have engraved you on the palms of my hands&rsquo; (Isaiah 49:16).",
    ],
  },
  {
    id: "Plots Against the Intercessor",
    heading: "Remember How I Stood Before You",
    reference: "Jeremiah 18:18&ndash;23",
    paragraphs: [
      "The response to the potter sermon is not repentance but conspiracy: &ldquo;Then they said, &lsquo;Come, let us make plots against Jeremiah, for the law shall not perish from the priest, nor counsel from the wise, nor the word from the prophet. Come, let us strike him with the tongue, and let us not pay attention to any of his words&rsquo;&rdquo; (18:18). Their logic is revealing: the religious establishment &mdash; priest, sage, prophet &mdash; is secure, they reason, so this lone dissenting voice can be safely destroyed. They will attack him &lsquo;with the tongue&rsquo;: slander, false accusation, a whispering campaign to ruin the man they cannot refute. It is the ancient strategy against every inconvenient truth-teller &mdash; when the message cannot be answered, assassinate the messenger's name.",
      "Jeremiah's prayer in response opens with a plea to be heard: &ldquo;Hear me, O Lord, and listen to the voice of my adversaries. Should good be repaid with evil? Yet they have dug a pit for my life&rdquo; (18:19-20). And then comes the line that gives the passage its lasting poignancy: &ldquo;Remember how I stood before you to speak good for them, to turn away your wrath from them&rdquo; (18:20). Jeremiah had been their intercessor &mdash; standing in the breach, pleading for the very people now digging his grave. The wound is doubled: he is repaid evil for good, hatred for prayer.",
      "What follows is the darkest of Jeremiah's imprecations: he asks God to give their children to famine and the sword, to let their men meet death and their wives lose husbands (18:21-23), and &mdash; most startling &mdash; &ldquo;Forgive not their iniquity, nor blot out their sin from your sight&rdquo; (18:23). These words must be handled honestly. They are the raw cry of a wounded man committing vengeance to God rather than taking it himself (Romans 12:19); they invoke the covenant curses the people had knowingly embraced; and they are recorded, not necessarily commended. Scripture lets us hear the prophet's full anguish without editing &mdash; and then lets a greater Sufferer show a more excellent way.",
      "For the contrast with Christ is surely the point toward which the whole passage leans. Jeremiah, betrayed after interceding, prayed &lsquo;forgive not&rsquo;; Jesus, betrayed after a lifetime of mercy, was repaid evil for good in full measure &mdash; &lsquo;they repaid me evil for good&rsquo; is the psalmist's cry that his passion fulfilled (Psalm 35:12; 109:4-5) &mdash; and from the cross he prayed the opposite prayer: &ldquo;Father, forgive them, for they know not what they do&rdquo; (Luke 23:34). Where Jeremiah's intercession broke under the weight of betrayal, Christ's intercession carried the betrayal itself &mdash; &lsquo;he bore the sin of many, and makes intercession for the transgressors&rsquo; (Isaiah 53:12). The plotters silenced neither prophet nor Word; and the Intercessor they struck down lives forever to plead for all who come to God through him (Hebrews 7:25).",
    ],
  },
  {
    id: "Application",
    heading: "Living Jeremiah 18",
    reference: "Reflections on the Potter and the Clay",
    paragraphs: [
      "<strong>Surrender to the Potter's rights over your life.</strong> &lsquo;Like the clay in the potter's hand, so are you in my hand.&rsquo; Much of our misery comes from arguing with the wheel &mdash; resenting the shape, the timing, the pressure of God's forming work. Yield to the hands that hold you; they are skilled and they are good. &lsquo;But now, O Lord, you are our Father; we are the clay, and you are our potter; we are all the work of your hand&rsquo; (Isaiah 64:8). The clay that fights the potter delays its own completion.",
      "<strong>Never treat God's warnings as fixed fate &mdash; the wheel is still turning.</strong> The same God who announces judgment declares that he relents toward any nation or heart that turns (18:8). If God is dealing severely with you, the message is not &lsquo;it is hopeless&rsquo; but &lsquo;return while the clay is wet.&rsquo; Refuse the despair that says &lsquo;That is in vain&rsquo; (18:12) &mdash; that lie has damned more souls than open rebellion. &lsquo;Whoever comes to me I will never cast out&rsquo; (John 6:37).",
      "<strong>Guard against the slow drift of forgetting God.</strong> The snow never leaves Lebanon, but hearts leave God by inches &mdash; a skipped prayer, a crowded week, a cooling affection &mdash; until the ancient road is lost. Build deliberate remembrance into your life: daily Scripture, honest prayer, the Lord's Table received thoughtfully. &lsquo;Bless the Lord, O my soul, and forget not all his benefits&rsquo; (Psalm 103:2). Stay on the ancient paths, where the good way is.",
      "<strong>When repaid evil for good, entrust the verdict to God &mdash; and pray like Jesus.</strong> Jeremiah interceded for people who dug a pit for his life, and his anguish is allowed its full voice. But the believer has seen further: the Lord who was struck by every tongue prayed, &lsquo;Father, forgive them.&rsquo; Commit your cause to the righteous Judge, and ask for grace to bless those who wound you (Romans 12:14, 19). <strong>Prayer prompt:</strong> &ldquo;Sovereign Potter, I am clay in your hands &mdash; forgive me for fighting the wheel. Where I am marred, do not cast me off but rework me into a vessel that seems good to you. Guard me from the slow forgetting that leaves the ancient road, and from the despair that says returning is vain. And when I am repaid evil for good, keep me from bitterness; let me pray as Jesus prayed, and rest my cause with you. Amen.&rdquo;",
    ],
  },
];

const data: SectionGuideData = {
  accent: "#E11D48",
  badge: "Jeremiah 18",
  title: "Jeremiah 18: Like Clay in the Potter's Hand",
  intro: "God sends Jeremiah down to the potter's house, where a vessel spoiled in the potter's hand is not discarded but reworked into another vessel. The parable holds two truths together: the Potter's absolute rights over the clay -- 'like the clay in the potter's hand, so are you in my hand' -- and his living responsiveness, relenting toward any nation that turns. The people's answer is the bleakest sentence in the book: 'That is in vain! We will follow our own plans.' Then they plot against the prophet who had stood before God to intercede for them.",
  tabs: TABS,
  sections,
  calloutTitle: "The Potter Who Remakes Marred Clay",
  calloutBody: "The vessel is spoiled in the potter's hand -- and the potter does not throw the clay away but crushes it back into a lump and begins again. Divine sovereignty is not the closing of the door but the reason it can still open: the Potter is free to remake what is marred, and he relents toward all who turn (18:8). Paul takes up the image for God's freedom (Rom 9:21); the gospel completes it -- 'if anyone is in Christ, he is a new creation' (2 Cor 5:17), his workmanship (Eph 2:10), treasure in jars of clay (2 Cor 4:7). No one who returns to the wheel is refused.",
};

export default function Page() {
  return <SectionGuideTemplate data={data} />;
}
