"use client";
import SectionGuideTemplate, { type SectionGuideData } from "@/components/SectionGuideTemplate";

const TABS: string[] = [
  "Overview",
  "Though Moses and Samuel Stood",
  "Woe Is Me, My Mother",
  "Your Words Were Found, and I Ate Them",
  "Application",
];

const sections = [
  {
    id: "Overview",
    heading: "Overview of Jeremiah 15",
    reference: "Jeremiah 15:1&ndash;21",
    paragraphs: [
      "Jeremiah 15 opens at the point of no return. In chapter 14 Jeremiah had pleaded for his people through drought and defeat, and now God gives his final answer: &ldquo;Though Moses and Samuel stood before me, yet my heart would not turn toward this people&rdquo; (15:1). The two greatest intercessors in Israel's history &mdash; Moses, who stood in the breach at Sinai, and Samuel, who cried out for Israel at Mizpah &mdash; could not avert this judgment. Four destroyers are appointed, the sins of Manasseh are named as the cause, and God declares, &ldquo;I am weary of relenting&rdquo; (15:6). The city that will not repent has exhausted even divine patience, and the chapter's opening movement traces judgment down to its bitter depth.",
      "But the chapter does not stay with the nation; it descends into the soul of the prophet. Jeremiah laments the day of his birth: &ldquo;Woe is me, my mother, that you bore me, a man of strife and contention to the whole land!&rdquo; (15:10). He has wronged no one &mdash; &lsquo;I have not lent, nor have I borrowed&rsquo; &mdash; yet everyone curses him. Here is the loneliness and cost of the prophetic calling: hated not for wrongdoing but for faithfulness. God answers with a partial reassurance (15:11) and a hard word about iron from the north that cannot be broken (15:12-14).",
      "Then comes the greatest of Jeremiah's confessions. He remembers his treasure &mdash; &ldquo;Your words were found, and I ate them, and your words became to me a joy and the delight of my heart&rdquo; (15:16) &mdash; and his isolation: &ldquo;I sat alone, because your hand was upon me&rdquo; (15:17). And then, shockingly, he accuses God himself: &ldquo;Will you be to me like a deceitful brook, like waters that fail?&rdquo; (15:18). The prophet charges the living God with being a mirage. God's answer is both rebuke and grace: &ldquo;If you return, I will restore you&rdquo; (15:19) &mdash; and then he repeats Jeremiah's original call-promise almost word for word from 1:18-19: &ldquo;I will make you to this people a fortified wall of bronze&hellip; for I am with you to save you and deliver you&rdquo; (15:20).",
      "The chapter thus becomes one of Scripture's deepest studies in how God restores faltering servants: not by discarding them, and not by pretending their accusations were acceptable, but by calling them back and renewing their first commission. The New Testament fulfills every thread. Where Moses and Samuel could not prevail, Christ &lsquo;always lives to make intercession&rsquo; and his plea never fails (Hebrews 7:25). The prophet who ate God's words points to the Word made flesh, on whom we feed (John 1:14; 6:35). The deceitful brook that fails finds its answer in the spring of living water that never runs dry (John 4:14). And the broken servant recommissioned with his original call foreshadows Peter, restored by the risen Jesus with the words, &lsquo;Feed my sheep&rsquo; (John 21:17).",
    ],
  },
  {
    id: "Though Moses and Samuel Stood",
    heading: "My Heart Would Not Turn Toward This People",
    reference: "Jeremiah 15:1&ndash;9",
    paragraphs: [
      "God's answer to Jeremiah's intercession is devastating: &ldquo;Though Moses and Samuel stood before me, yet my heart would not turn toward this people. Send them out of my sight, and let them go!&rdquo; (15:1). Moses and Samuel were Israel's supreme intercessors. When Israel made the golden calf, Moses stood before God and turned away wrath, even offering himself &mdash; &lsquo;blot me out of your book&rsquo; (Exodus 32:32). Samuel cried out to the Lord at Mizpah and Israel was delivered (1 Samuel 7:9), and he counted it sin to cease praying for the people (1 Samuel 12:23). If any prayers could avert judgment, theirs could. Yet God declares that even these two, standing together before him, could not now turn his heart. Judah has passed the point where intercession will hold back the flood.",
      "The judgment is then sorted with terrible precision: &ldquo;Those who are for pestilence, to pestilence, and those who are for the sword, to the sword; those who are for famine, to famine, and those who are for captivity, to captivity&rdquo; (15:2). Four destroyers are appointed: &ldquo;the sword to kill, the dogs to tear, and the birds of the air and the beasts of the earth to devour and destroy&rdquo; (15:3). And the cause is traced to a name: &ldquo;because of what Manasseh the son of Hezekiah, king of Judah, did in Jerusalem&rdquo; (15:4). Manasseh had filled Jerusalem with idolatry and innocent blood (2 Kings 21:1-16), and though Josiah's reforms followed, the nation's heart had settled into the pattern its worst king had set.",
      "Then comes one of the most sobering sentences in the book: &ldquo;You have rejected me, declares the Lord; you keep going backward, so I have stretched out my hand against you and destroyed you &mdash; I am weary of relenting&rdquo; (15:6). Again and again God had relented &mdash; at Moses' prayer, at Samuel's, at every wave of partial repentance &mdash; but Judah only &lsquo;kept going backward.&rsquo; Now God will winnow them &ldquo;with a winnowing fork in the gates of the land&rdquo; (15:7); widows will be made &ldquo;more in number than the sand of the seas&rdquo; (15:8); and &ldquo;she who bore seven has grown feeble; she has fainted away&hellip; her sun went down while it was yet day&rdquo; (15:9). Divine patience is vast, but it is not infinite, and a people can spurn mercy until mercy's hour has passed.",
      "Yet precisely here the gospel shines by contrast. If even Moses and Samuel could not prevail for a hardened people, what hope is there for sinners anywhere? The answer is a greater Intercessor. Moses offered to be blotted out for Israel and was refused; Jesus actually was cut off for his people, bearing their curse in his own body (Galatians 3:13). Because his intercession rests not on his eloquence but on his finished atonement, it never fails: &ldquo;he is able to save to the uttermost those who draw near to God through him, since he always lives to make intercession for them&rdquo; (Hebrews 7:25). Jeremiah 15:1 shows us the outer limit of every merely human mediator &mdash; and makes us treasure the one Mediator between God and men (1 Timothy 2:5) whose plea on behalf of all who come to him is always, eternally heard.",
    ],
  },
  {
    id: "Woe Is Me, My Mother",
    heading: "A Man of Strife to the Whole Land",
    reference: "Jeremiah 15:10&ndash;14",
    paragraphs: [
      "The word of judgment Jeremiah must carry now crushes the carrier, and he cries out in lament over his own existence: &ldquo;Woe is me, my mother, that you bore me, a man of strife and contention to the whole land! I have not lent, nor have I borrowed, yet all of them curse me&rdquo; (15:10). Lending and borrowing were the proverbial breeding ground of quarrels in the ancient world; Jeremiah's point is that he has given no one any personal cause for hostility. He has cheated no one, wronged no one, owes no one. Yet the whole land curses him. His only offense is the message he carries, and for that message he has become a man of strife to everyone he loves. The lament will deepen later into his darkest cry (20:14-18), echoing Job's cursing of his birth day (Job 3).",
      "Here is the loneliness and cost of the prophetic calling laid bare. Jeremiah is not quarrelsome by nature &mdash; he is the weeping prophet, tender enough to wish his head were a fountain of tears (9:1). He is a man of contention because the word he bears contends with everything his culture trusts: its temple presumption, its idols, its politics, its prophets of peace. Faithfulness to God has made him an enemy of his people. Jesus told his disciples to expect exactly this: &ldquo;Do not think that I have come to bring peace to the earth&hellip; but a sword&rdquo; (Matthew 10:34), and he pronounced blessing on those reviled for his sake, &ldquo;for so they persecuted the prophets who were before you&rdquo; (Matthew 5:11-12). Jeremiah stands at the head of that persecuted line, which runs through the apostles to the faithful church today.",
      "God answers his servant with reassurance: &ldquo;Have I not set you free for their good? Have I not pleaded for you before the enemy in the time of trouble and in the time of distress?&rdquo; (15:11). The promise is that God will set Jeremiah free for purposes of good &mdash; his suffering is not meaningless, and his enemies will one day come to him in their distress. The word is quietly fulfilled as the book unfolds: kings who despised Jeremiah send to him begging for prayer and a word from the Lord when Babylon closes in (21:1-2; 37:3; 42:1-3), and the captain of the Babylonian guard treats him with honor when Jerusalem falls (39:11-14). The despised preacher becomes the one man everyone needs.",
      "But the reassurance for the prophet is woven together with an unbending word for the nation: &ldquo;Can one break iron, iron from the north, and bronze?&rdquo; (15:12). The northern power God is bringing cannot be snapped by Judah's strength or diplomacy. &ldquo;Your wealth and your treasures I will give as spoil, without price, for all your sins&rdquo; (15:13), &ldquo;and I will make you serve your enemies in a land that you do not know, for in my anger a fire is kindled that shall burn forever&rdquo; (15:14). The judgment is fixed; the servant's comfort is not that the storm will be canceled but that God will keep him through it and use him in it. So it remains for Christ's servants: &ldquo;do not be surprised at the fiery trial when it comes upon you&hellip; but rejoice insofar as you share Christ's sufferings&rdquo; (1 Peter 4:12-13).",
    ],
  },
  {
    id: "Your Words Were Found, and I Ate Them",
    heading: "If You Return, I Will Restore You",
    reference: "Jeremiah 15:15&ndash;21",
    paragraphs: [
      "Jeremiah's second confession begins with an appeal to the God who knows: &ldquo;O Lord, you know; remember me and visit me, and take vengeance for me on my persecutors&hellip; know that for your sake I bear reproach&rdquo; (15:15). Then he recalls his treasure, in one of the most beautiful sentences in the prophets: &ldquo;Your words were found, and I ate them, and your words became to me a joy and the delight of my heart, for I am called by your name, O Lord, God of hosts&rdquo; (15:16). Many hear in &lsquo;your words were found&rsquo; an echo of the Book of the Law discovered in the temple in Josiah's reign (2 Kings 22:8-13), the event that shaped Jeremiah's youth. Whatever the occasion, the image is unforgettable: the prophet did not merely read God's words; he ate them, took them into himself until they became his food, his joy, his very identity. Ezekiel would receive the same sign (Ezekiel 3:1-3), and John after him (Revelation 10:9-10) &mdash; sweet in the mouth even when the message is bitter to deliver.",
      "But the same word that was his joy became his isolation: &ldquo;I did not sit in the company of revelers, nor did I rejoice; I sat alone, because your hand was upon me, for you had filled me with indignation&rdquo; (15:17). And out of that loneliness erupts the most shocking accusation in all of Jeremiah's confessions: &ldquo;Why is my pain unceasing, my wound incurable, refusing to be healed? Will you be to me like a deceitful brook, like waters that fail?&rdquo; (15:18). A deceitful brook is a desert wadi &mdash; full and glittering in the rainy season, bone dry in summer when the traveler is dying of thirst (Job 6:15-20). Jeremiah is accusing God of being a mirage: the fountain of living waters he preached to others (2:13) has, he charges, failed the preacher himself. It is a breathtaking thing to say to God, and Scripture does not hide it from us.",
      "God's answer is both rebuke and grace, and both are mercy: &ldquo;If you return, I will restore you, and you shall stand before me. If you utter what is precious, and not what is worthless, you shall be as my mouth&rdquo; (15:19). The preacher of repentance must himself repent. God does not coddle the accusation &mdash; calling God a deceitful brook is &lsquo;worthless&rsquo; speech that must be renounced &mdash; but neither does he dismiss his servant. The very word Jeremiah has spent his life preaching to Judah, &lsquo;return&rsquo; (shub), is now spoken to the prophet, with a promise attached: return, and you will again stand before me; speak what is precious, and you shall be as my mouth. And God adds a line that guards every faithful minister: &ldquo;They shall turn to you, but you shall not turn to them&rdquo; (15:19). The messenger must never soften the message to win back the crowd.",
      "Then comes the astonishing conclusion: God repeats Jeremiah's original call-promise almost verbatim from the day he was first commissioned. &ldquo;And I will make you to this people a fortified wall of bronze; they will fight against you, but they shall not prevail over you, for I am with you to save you and deliver you, declares the Lord. I will deliver you out of the hand of the wicked, and redeem you from the grasp of the ruthless&rdquo; (15:20-21; compare 1:18-19). God restores faltering servants by renewing their first calling. This is exactly how the risen Jesus restored Peter after his three denials &mdash; not with probation but with recommissioning: &ldquo;Feed my sheep&rdquo; (John 21:17). And every thread of the confession is fulfilled in Christ: the words we eat point to the Word made flesh, the true bread &mdash; &ldquo;I am the bread of life&hellip; the bread that I will give for the life of the world is my flesh&rdquo; (John 6:35, 51); man lives &ldquo;by every word that comes from the mouth of God&rdquo; (Matthew 4:4); and against every deceitful brook stands his promise: &ldquo;whoever drinks of the water that I will give him will never be thirsty again&hellip; a spring of water welling up to eternal life&rdquo; (John 4:14).",
    ],
  },
  {
    id: "Application",
    heading: "Living Jeremiah 15",
    reference: "Reflections on Judgment, Calling, and Restoration",
    paragraphs: [
      "<strong>Treasure the Intercessor whose plea never fails.</strong> Not even Moses and Samuel could turn God's heart toward a people hardened past repentance (15:1) &mdash; a sobering word against presuming on grace, and a glorious word driving us to Christ. Do not rest your soul on any human mediator, any pedigree, any second-hand faith. Draw near to God through the Son who bore the curse himself and &lsquo;always lives to make intercession&rsquo; (Hebrews 7:25). His prayer for his people is always heard, because it rests on his finished cross.",
      "<strong>Expect the cost of faithfulness and do not be surprised by it.</strong> Jeremiah was a man of strife to the whole land though he had wronged no one (15:10); he was hated purely for the message. If you are faithful to God's word in a culture that resists it, some hostility will find you &mdash; not because you are quarrelsome, but because the word contends with what people love. Receive Jesus' blessing on the reviled (Matthew 5:11-12), refuse to soften the message to win back the crowd &mdash; &lsquo;they shall turn to you, but you shall not turn to them&rsquo; (15:19) &mdash; and trust God to set you free for purposes of good.",
      "<strong>Eat God's words until they become your joy.</strong> Jeremiah did not skim Scripture; he ate it &mdash; &lsquo;your words became to me a joy and the delight of my heart&rsquo; (15:16). Take the word into yourself daily as food, not merely information: read it, memorize it, pray it, feed on it. For the words lead to the Word: &lsquo;I am the bread of life&rsquo; (John 6:35). A believer who feeds on Christ in Scripture will have reserves of joy that loneliness and opposition cannot drain, for man lives &lsquo;by every word that comes from the mouth of God&rsquo; (Matthew 4:4).",
      "<strong>Bring even your accusations to God, and let him restore and recommission you.</strong> Jeremiah told God the worst thing in his heart &mdash; that he seemed a deceitful brook (15:18) &mdash; and God answered with rebuke and grace: return, and I will restore you (15:19), and then he renewed the original call word for word (15:20). When you have grown bitter or burned out in serving God, do not hide it piously or walk away quietly; bring it to him. He does not discard faltering servants; like the risen Christ restoring Peter with &lsquo;Feed my sheep&rsquo; (John 21:17), he restores them to their first calling. <strong>Prayer prompt:</strong> &ldquo;Lord God of hosts, thank you for the true Intercessor whose plea for me never fails. Give me courage to bear the cost of faithfulness without softening your word, and teach me to eat your words until they are the joy and delight of my heart. When my pain tempts me to call you a failing stream, hear my honest cry, forgive my worthless words, and restore me as you restored Jeremiah and Peter &mdash; renew my first calling, stand me on my feet, and be with me to save and deliver me. Amen.&rdquo;",
    ],
  },
];

const data: SectionGuideData = {
  accent: "#0D9488",
  badge: "Jeremiah 15",
  title: "Jeremiah 15: Your Words Became to Me a Joy",
  intro: "Jeremiah 15 plumbs the depth of Judah's judgment and the depth of the prophet's anguish. Not even Moses and Samuel, Israel's greatest intercessors, could avert this judgment -- 'I am weary of relenting,' God declares. Jeremiah laments the day of his birth, a man of strife to the whole land, hated not for wrongdoing but for faithfulness. Then comes his greatest confession: 'Your words were found, and I ate them, and your words became to me a joy' -- followed by his darkest accusation, that God has become like a deceitful brook whose waters fail. God answers with rebuke and grace, renewing Jeremiah's original call word for word: 'I will make you to this people a fortified wall of bronze... for I am with you to save you and deliver you.'",
  tabs: TABS,
  sections,
  calloutTitle: "Grace Restores and Recommissions",
  calloutBody: "The prophet who ate God's words as the joy and delight of his heart (15:16) came to accuse God of being 'a deceitful brook, like waters that fail' (15:18) -- and God answered not by discarding him but by calling him to return and then renewing his commission almost word for word from the day he was first sent: 'I will make you to this people a fortified wall of bronze... for I am with you to save you and deliver you' (15:20; cf. 1:18-19). This is God's way with faltering servants. As the risen Jesus restored Peter after his denials by recommissioning him -- 'Feed my sheep' (John 21:17) -- so grace does not merely forgive the broken; it renews their first calling and puts them back to work.",
};

export default function Page() {
  return <SectionGuideTemplate data={data} />;
}
